package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.model.CarrierType;
import net.muratec.mcs.model.CarrierTypeExample;

public interface CarrierTypeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER_TYPE
     * @mbg.generated
     */
    long countByExample(CarrierTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER_TYPE
     * @mbg.generated
     */
    int deleteByExample(CarrierTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER_TYPE
     * @mbg.generated
     */
    int deleteByPrimaryKey(String carrierTypeId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER_TYPE
     * @mbg.generated
     */
    int insert(CarrierType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER_TYPE
     * @mbg.generated
     */
    int insertSelective(CarrierType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER_TYPE
     * @mbg.generated
     */
    List<CarrierType> selectByExample(CarrierTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER_TYPE
     * @mbg.generated
     */
    CarrierType selectByPrimaryKey(String carrierTypeId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER_TYPE
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CarrierType record, @Param("example") CarrierTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER_TYPE
     * @mbg.generated
     */
    int updateByExample(@Param("record") CarrierType record, @Param("example") CarrierTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER_TYPE
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CarrierType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER_TYPE
     * @mbg.generated
     */
    int updateByPrimaryKey(CarrierType record);

    // =============================
    // MCS Unique Function From Here
    // =============================
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get All CarrierShapeId
     * @param
     * @return      CARRIER_SHAPE_ID
     * @retval      List of String Style
     * @attention
     * @note        Get All CarrierShapeId.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> getCarrierTypeId();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectCarrierTypeList
     * @param     reqEntiry  Request from client
     * @return    carrierTypeList
     * @retval    List
     * @attention
     * @note      Get CarrierType List
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<CarrierType> selectCarrierTypeList(AjaxDataTablesReqBaseEntity reqEntity);
}
