package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.info.ReqGetCarrierListEntity;
import net.muratec.mcs.entity.info.ReqGetCarrierModifyEntity;
import net.muratec.mcs.model.Carrier;
import net.muratec.mcs.model.CarrierExample;
import net.muratec.mcs.model.CarrierModel;
import net.muratec.mcs.model.GuiColor;

public interface CarrierMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    long countByExample(CarrierExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    int deleteByExample(CarrierExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    int deleteByPrimaryKey(String entityId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    int insert(Carrier record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    int insertSelective(Carrier record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    List<Carrier> selectByExample(CarrierExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    Carrier selectByPrimaryKey(String entityId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Carrier record, @Param("example") CarrierExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    int updateByExample(@Param("record") Carrier record, @Param("example") CarrierExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Carrier record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    int updateByPrimaryKey(Carrier record);

    // =============================
    // MCS Unique Function From Here
    // =============================
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select Carrier Info List
     * @param       reqEntity   (search criteria)
     * @return      Carrier Info List
     * @retval      List of CarrierModel Style
     * @attention
     * @note        Select Carrier Info List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<CarrierModel> selectList(ReqGetCarrierListEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select Carrier Info(for Modify Screen)
     * @param       reqEntity   (search criteria)
     * @return      Carrier Info
     * @retval      Carrier Style
     * @attention
     * @note        Select Carrier Info that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    Carrier selectModify(ReqGetCarrierModifyEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get the total number of Carrier Info List
     * @param       reqEntity   (search criteria)
     * @return      the total number of Carrier Info List
     * @retval      int Style
     * @attention
     * @note        Get the total number of Carrier Info List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int getCount(ReqGetCarrierListEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get the value of ActionFlag
     * @param
     * @return      the value List of ActionFlag
     * @retval      List of Short Style
     * @attention
     * @note        Get the value of ActionFlag.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<Short> getActionFlag();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Update Carrier Info by UniqueKey
     * @param       reqEntity   (modify criteria)
     * @return      the number of Mod operation successes
     * @retval      int Style
     * @attention
     * @note        Update Carrier Info by UniqueKey.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int updateByUniqueKey(Carrier reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     getGuiColorList
     * @param     reqEntity     (search criteria)
     * @return    Getting Color Record List
     * @retval    return int form
     * @attention
     * @note      Getting Color Record List that matches search criteria.
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<GuiColor> getGuiColorList(ReqGetCarrierListEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectCarrierIdByCarrierShapeId
     * @param     carrierShapeId  (search cond)
     * @return    Getting CARRIER_ID List by CARRIER_SHAPE_ID
     * @retval    return List of String form
     * @attention
     * @note      Getting CARRIER_ID List by CARRIER_SHAPE_ID
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectCarrierIdByCarrierShapeId(String carrierShapeId);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectCarrierIdByCurrentLoc
     * @param     carrierShapeId  (search cond)
     * @return    Getting CARRIER_ID List by CURRENT_LOC
     * @retval    return List of String form
     * @attention
     * @note      Getting CARRIER_ID List by CURRENT_LOC
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     * MACS4#0206  GUI テストキャリア設定修正(新規作成)                   T.Iga/CSC
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectCarrierIdByCurrentLoc(@Param("portId") String portId);
}
