package net.muratec.mcs.mapper;

import java.util.List;
import net.muratec.mcs.model.DefaultProcess;
import net.muratec.mcs.model.DefaultProcessExample;
import org.apache.ibatis.annotations.Param;

/* プロセスデフォルト対応 - 制御側未対応のため、未使用 */
public interface DefaultProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEFAULT_PROCESS
     *
     * @mbg.generated
     */
    long countByExample(DefaultProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEFAULT_PROCESS
     *
     * @mbg.generated
     */
    int deleteByExample(DefaultProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEFAULT_PROCESS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short procType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEFAULT_PROCESS
     *
     * @mbg.generated
     */
    int insert(DefaultProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEFAULT_PROCESS
     *
     * @mbg.generated
     */
    int insertSelective(DefaultProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEFAULT_PROCESS
     *
     * @mbg.generated
     */
    List<DefaultProcess> selectByExample(DefaultProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEFAULT_PROCESS
     *
     * @mbg.generated
     */
    DefaultProcess selectByPrimaryKey(Short procType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEFAULT_PROCESS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DefaultProcess record, @Param("example") DefaultProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEFAULT_PROCESS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DefaultProcess record, @Param("example") DefaultProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEFAULT_PROCESS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DefaultProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEFAULT_PROCESS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DefaultProcess record);
}