package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.model.EmptyCarrierContami;
import net.muratec.mcs.model.EmptyCarrierContamiExample;

import org.apache.ibatis.annotations.Param;

public interface EmptyCarrierContamiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTAMI
     *
     * @mbg.generated
     */
    long countByExample(EmptyCarrierContamiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTAMI
     *
     * @mbg.generated
     */
    int deleteByExample(EmptyCarrierContamiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTAMI
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String contamiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTAMI
     *
     * @mbg.generated
     */
    int insert(EmptyCarrierContami record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTAMI
     *
     * @mbg.generated
     */
    int insertSelective(EmptyCarrierContami record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTAMI
     *
     * @mbg.generated
     */
    List<EmptyCarrierContami> selectByExample(EmptyCarrierContamiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTAMI
     *
     * @mbg.generated
     */
    EmptyCarrierContami selectByPrimaryKey(String contamiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTAMI
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmptyCarrierContami record, @Param("example") EmptyCarrierContamiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTAMI
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmptyCarrierContami record, @Param("example") EmptyCarrierContamiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTAMI
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmptyCarrierContami record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTAMI
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmptyCarrierContami record);   

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Select EmptyCarrierContami List(RowNum)
     * @return    EmptyCarrierContami List
     * @retval    List<EmptyCarrierContamiModel>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<EmptyCarrierContami> selectEmptyCarrierContamiRowNum(AjaxDataTablesReqBaseEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Select Contami and Purpose Match List
     * @return    Contami equals Purpose List
     * @retval    List<String>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     * 2019/01/08 MACS4#0084  GUI iFoup関連データ自動登録対応             T.Iga/CSC
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectContamiPurposeMatchList();
}