package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.model.EmptyCarrierController;
import net.muratec.mcs.model.EmptyCarrierControllerExample;
import net.muratec.mcs.model.EmptyCarrierControllerModel;

import org.apache.ibatis.annotations.Param;

public interface EmptyCarrierControllerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTROLLER
     *
     * @mbg.generated
     */
    long countByExample(EmptyCarrierControllerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTROLLER
     *
     * @mbg.generated
     */
    int deleteByExample(EmptyCarrierControllerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTROLLER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String controllerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTROLLER
     *
     * @mbg.generated
     */
    int insert(EmptyCarrierController record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTROLLER
     *
     * @mbg.generated
     */
    int insertSelective(EmptyCarrierController record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTROLLER
     *
     * @mbg.generated
     */
    List<EmptyCarrierController> selectByExample(EmptyCarrierControllerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTROLLER
     *
     * @mbg.generated
     */
    EmptyCarrierController selectByPrimaryKey(String controllerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTROLLER
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmptyCarrierController record, @Param("example") EmptyCarrierControllerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTROLLER
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmptyCarrierController record, @Param("example") EmptyCarrierControllerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTROLLER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmptyCarrierController record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_CONTROLLER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmptyCarrierController record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Select EmptyCarrierController List(RowNum)
     * @return    EmptyCarrierController List
     * @retval    List<EmptyCarrierControllerModel>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<EmptyCarrierControllerModel> selectEmptyCarrierControllerRowNum(AjaxDataTablesReqBaseEntity reqEntity);

}