package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.model.AlarmSystemSettingEqpTypeListModel;
import net.muratec.mcs.model.EqpType;
import net.muratec.mcs.model.EqpTypeExample;
import org.apache.ibatis.annotations.Param;

public interface EqpTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQP_TYPE
     *
     * @mbg.generated
     */
    long countByExample(EqpTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQP_TYPE
     *
     * @mbg.generated
     */
    int deleteByExample(EqpTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQP_TYPE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String eqpType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQP_TYPE
     *
     * @mbg.generated
     */
    int insert(EqpType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQP_TYPE
     *
     * @mbg.generated
     */
    int insertSelective(EqpType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQP_TYPE
     *
     * @mbg.generated
     */
    List<EqpType> selectByExample(EqpTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQP_TYPE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EqpType record, @Param("example") EqpTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQP_TYPE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EqpType record, @Param("example") EqpTypeExample example);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectList    (Get EQP TYPE list)function
     * @param     reqEntity  Request from client(Search condition)
     * @return    EQP TYPE list
     * @retval    Return EQP TYPE list
     * @attention
     * @note       Get the EQP TYPE that matched the search condition
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<AlarmSystemSettingEqpTypeListModel> selectAlarmSystemSettingEqpTypeRowNum(AjaxDataTablesReqBaseEntity reqEntity);
}