package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.entity.maint.ReqStockerGroupEntity;
import net.muratec.mcs.model.Grp;
import net.muratec.mcs.model.GrpExample;
import net.muratec.mcs.model.StockerGrpModel;
import net.muratec.mcs.model.UnitGroupModel;

public interface GrpMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GRP
     * @mbg.generated
     */
    long countByExample(GrpExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GRP
     * @mbg.generated
     */
    int deleteByExample(GrpExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GRP
     * @mbg.generated
     */
    int deleteByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GRP
     * @mbg.generated
     */
    int insert(Grp record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GRP
     * @mbg.generated
     */
    int insertSelective(Grp record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GRP
     * @mbg.generated
     */
    List<Grp> selectByExample(GrpExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GRP
     * @mbg.generated
     */
    Grp selectByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GRP
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Grp record, @Param("example") GrpExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GRP
     * @mbg.generated
     */
    int updateByExample(@Param("record") Grp record, @Param("example") GrpExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GRP
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Grp record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GRP
     * @mbg.generated
     */
    int updateByPrimaryKey(Grp record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectList    (Get Stocker Group list)function
     * @param     reqEntity  Request from client(Search condition)
     * @return    Stocker Group list
     * @retval    Return Stocker Group list
     * @attention
     * @note       Get the stocker group that matched the search condition
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<StockerGrpModel> selectList(AjaxDataTablesReqBaseEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectList    (Get the total number of records in the Stocker Group list)functinon
     * @param     reqEntity     Request from client(Search condition)
     * @return    The total number of records in the Stocker Group list
     * @retval    Return in int format
     * @attention
     * @note      Get the total number of records in the Stocker Group that matched the search condition
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int getCount(ReqStockerGroupEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     getPortGroupCount (Get the total number of records in Port Group list)
     * @param
     * @return    The total number of records in Port Group list
     * @retval    Integer Style
     * @attention
     * @note      SQL-0352
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int getPortGroupCount();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectUnitGroupList (get List of GRP and GRP_RLT)
     * @param
     * @return    List of UnitGroupModel
     * @retval    List of GRP and GRP_RLT
     * @attention
     * @note      get List for Unit Group Master Maintenance.
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<UnitGroupModel> selectUnitGroupList(AjaxDataTablesReqBaseEntity reqEntity);

}