package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.model.GuiFuncGroup;
import net.muratec.mcs.model.GuiFuncGroupExample;
import org.apache.ibatis.annotations.Param;

public interface GuiFuncGroupMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GUI_FUNC_GROUP
     * @mbg.generated
     */
    long countByExample(GuiFuncGroupExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GUI_FUNC_GROUP
     * @mbg.generated
     */
    int deleteByExample(GuiFuncGroupExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GUI_FUNC_GROUP
     * @mbg.generated
     */
    int deleteByPrimaryKey(String guiGroupId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GUI_FUNC_GROUP
     * @mbg.generated
     */
    int insert(GuiFuncGroup record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GUI_FUNC_GROUP
     * @mbg.generated
     */
    int insertSelective(GuiFuncGroup record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GUI_FUNC_GROUP
     * @mbg.generated
     */
    List<GuiFuncGroup> selectByExample(GuiFuncGroupExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GUI_FUNC_GROUP
     * @mbg.generated
     */
    GuiFuncGroup selectByPrimaryKey(String guiGroupId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GUI_FUNC_GROUP
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GuiFuncGroup record, @Param("example") GuiFuncGroupExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GUI_FUNC_GROUP
     * @mbg.generated
     */
    int updateByExample(@Param("record") GuiFuncGroup record, @Param("example") GuiFuncGroupExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GUI_FUNC_GROUP
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GuiFuncGroup record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table GUI_FUNC_GROUP
     * @mbg.generated
     */
    int updateByPrimaryKey(GuiFuncGroup record);

    // =============================
    // MCS Unique Function From Here
    // =============================
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select Group Info List
     * @param       reqEntity   (search criteria)
     * @return      Group Info List
     * @retval      List of GuiFuncGroup Style
     * @attention
     * @note        Select Group Info List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<GuiFuncGroup> selectList(AjaxDataTablesReqBaseEntity reqEntity);
}
