package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.model.Host;
import net.muratec.mcs.model.HostExample;
import net.muratec.mcs.model.HostKey;

public interface HostMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST
     * @mbg.generated
     */
    long countByExample(HostExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST
     * @mbg.generated
     */
    int deleteByExample(HostExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST
     * @mbg.generated
     */
    int deleteByPrimaryKey(HostKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST
     * @mbg.generated
     */
    int insert(Host record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST
     * @mbg.generated
     */
    int insertSelective(Host record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST
     * @mbg.generated
     */
    List<Host> selectByExample(HostExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST
     * @mbg.generated
     */
    Host selectByPrimaryKey(HostKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Host record, @Param("example") HostExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST
     * @mbg.generated
     */
    int updateByExample(@Param("record") Host record, @Param("example") HostExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Host record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST
     * @mbg.generated
     */
    int updateByPrimaryKey(Host record);

    // =============================
    // MCS Unique Function From Here
    // =============================
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select HOST Info List by a given number
     * @param       reqEntity   (search criteria)
     * @return      HOST List
     * @retval      List of Host Style
     * @attention
     * @note        Select HOST Info List by a given number.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<Host> selectHostRowNum(AjaxDataTablesReqBaseEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select All HostDrvSrvId List
     * @param
     * @return      HostDrvSrvId List
     * @retval      List of String Style
     * @attention
     * @note        Select all HostDrvSrvId List.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectHostSidList();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select All HOST_NAME List
     * @param
     * @return      HOST_NAME List
     * @retval      List of String Style
     * @attention
     * @note        Select all HOST_NAME List.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectHostNameList();
}
