package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.model.HostAliasExample;
import net.muratec.mcs.model.HostAliasKey;
import net.muratec.mcs.model.HostAliasModel;
import net.muratec.mcs.model.HostAlias;

public interface HostAliasMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALIAS
     * @mbg.generated
     */
    long countByExample(HostAliasExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALIAS
     * @mbg.generated
     */
    int deleteByExample(HostAliasExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALIAS
     * @mbg.generated
     */
    int deleteByPrimaryKey(HostAliasKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALIAS
     * @mbg.generated
     */
    int insert(HostAlias record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALIAS
     * @mbg.generated
     */
    int insertSelective(HostAlias record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALIAS
     * @mbg.generated
     */
    List<HostAlias> selectByExample(HostAliasExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALIAS
     * @mbg.generated
     */
    HostAlias selectByPrimaryKey(HostAliasKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALIAS
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HostAlias record, @Param("example") HostAliasExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALIAS
     * @mbg.generated
     */
    int updateByExample(@Param("record") HostAlias record, @Param("example") HostAliasExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALIAS
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HostAlias record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALIAS
     * @mbg.generated
     */
    int updateByPrimaryKey(HostAlias record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectEqpLocation
     * @param     None
     * @return    List of KEY
     * @retval    Retrun the list of KEY
     * @attention
     * @note      Returns a list of KEY
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     * MACS4#0047  GUI要望分                                              T.Iga/CSC
     ******************************************************************************
     */
    //@formatter:on
//  List<String> selectEqpLocation();   // MACS4#0047 Del

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectEqpLocation
     * @param     None
     * @return    List of KEY
     * @retval    Retrun the list of KEY
     * @attention
     * @note      Returns a list of KEY
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     * MACS4#0047  GUI要望分                                              T.Iga/CSC
     ******************************************************************************
     */
    //@formatter:on
//  List<String> selectEqpPort(java.lang.String eqpId);     // MACS4#0047 Del

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectHostAliasList
     * @oaram     reqEntiry
     * @return    HostAliasList
     * @retval    List
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<HostAliasModel> selectHostAliasList(AjaxDataTablesReqBaseEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     countHostAliasList
     * @return    The count of HostAlias list
     * @retval    List
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    long hostAliasCountByExample(HostAliasExample example);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectHostAliasList
     * @param     Host_Alias table primary key
     * @return    List of KEY
     * @retval    Retrun the list of KEY
     * @attention
     * @note      Returns a list of KEY
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    HostAliasModel modifyHostAliasList(@Param("hostKeyName") String hostKeyName,
            @Param("mcsKeyName") String mcsKeyName);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     insertHostAlias
     * @param     hostAliasModel Request from client
     * @return
     * @retval
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int insertHostAlias(HostAliasModel hostAliasModel);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     updateHostAlias
     * @param     hostAliasModel Request from client
     * @return
     * @retval
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int updateHostAlias(HostAliasModel hostAliasModel);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectMcsAliasByKey
     * @param     key
     * @return    String
     * @retval
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    String selectMcsAliasByKey(String key);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectHostAliasByKey
     * @param     key
     * @return    String
     * @retval
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    String selectHostAliasByKey(String key);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectPGVPortList
     * @param     key
     * @return    List of String
     * @retval
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectPGVPortList(String key);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectOhbPortList
     * @param     key
     * @return    List of String
     * @retval
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectOhbPortList(String key);

    
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get Input Equipment Port Controller
     * @param
     * @return      String List
     * @retval      List of String
     * @attention
     * @note        Get Input Equipment Port Controller
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectInputEQControllerList();
    
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get Output Equipment Port Controller
     * @param
     * @return      String List
     * @retval      List of String
     * @attention
     * @note        Get Output Equipment Port Controller
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectOutputEQControllerList();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectInputEQPortList
     * @param     key
     * @return    List of String
     * @retval
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectInputEQPortList(String key);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectOutputEQPortList
     * @param     key
     * @return    List of String
     * @retval
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectOutputEQPortList(String key);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectOPPPortList
     * @param     key
     * @return    List of String
     * @retval
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectOPPPortList(String key);
    
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get Io Equipment Controller List
     * @param
     * @return      String List
     * @retval      List of String
     * @attention
     * @note        Get Io Equipment Controller List
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectIoEQControllerList();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Get Io Equipment Port List
     * @param     key
     * @return    List of String
     * @retval
     * @attention
     * @note Get Io Equipment Port List
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectIoEQPortList(String key);
}
