package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.model.Node;
import net.muratec.mcs.model.NodeExample;

public interface NodeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table NODE
     * @mbg.generated
     */
    long countByExample(NodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table NODE
     * @mbg.generated
     */
    int deleteByExample(NodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table NODE
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short nodeId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table NODE
     * @mbg.generated
     */
    int insert(Node record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table NODE
     * @mbg.generated
     */
    int insertSelective(Node record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table NODE
     * @mbg.generated
     */
    List<Node> selectByExample(NodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table NODE
     * @mbg.generated
     */
    Node selectByPrimaryKey(Short nodeId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table NODE
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Node record, @Param("example") NodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table NODE
     * @mbg.generated
     */
    int updateByExample(@Param("record") Node record, @Param("example") NodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table NODE
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Node record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table NODE
     * @mbg.generated
     */
    int updateByPrimaryKey(Node record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectNodeRowNum
     * @return    Node List
     * @retval    List<Node>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<Node> selectNodeRowNum(AjaxDataTablesReqBaseEntity reqEntity);
}
