package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.model.Ohb;
import net.muratec.mcs.model.OhbPortGroupModifyModel;
import net.muratec.mcs.model.OhbPortRlt;
import net.muratec.mcs.model.OhbPortRltExample;
import net.muratec.mcs.model.OhbPortRltKey;

public interface OhbPortRltMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OHB_PORT_RLT
     * @mbg.generated
     */
    long countByExample(OhbPortRltExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OHB_PORT_RLT
     * @mbg.generated
     */
    int deleteByExample(OhbPortRltExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OHB_PORT_RLT
     * @mbg.generated
     */
    int deleteByPrimaryKey(OhbPortRltKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OHB_PORT_RLT
     * @mbg.generated
     */
    int insert(OhbPortRlt record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OHB_PORT_RLT
     * @mbg.generated
     */
    int insertSelective(OhbPortRlt record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OHB_PORT_RLT
     * @mbg.generated
     */
    List<OhbPortRlt> selectByExample(OhbPortRltExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OHB_PORT_RLT
     * @mbg.generated
     */
    OhbPortRlt selectByPrimaryKey(OhbPortRltKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OHB_PORT_RLT
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OhbPortRlt record, @Param("example") OhbPortRltExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OHB_PORT_RLT
     * @mbg.generated
     */
    int updateByExample(@Param("record") OhbPortRlt record, @Param("example") OhbPortRltExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OHB_PORT_RLT
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OhbPortRlt record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OHB_PORT_RLT
     * @mbg.generated
     */
    int updateByPrimaryKey(OhbPortRlt record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectPortIdByStockerGrpId (Get List of PORT_ID corresponding to STOCKER_GROUP_ID)function
     * @param     stockerGrpId STOCKER_GROUP_ID (Search condition)
     * @return    List of PORT_ID corresponding to STOCKER_GROUP ID
     * @retval    Return a list of strings
     * @attention
     * @note      Return List of PORT_ID corresponding to STOCKER_GROUP ID
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectPortIdByStockerGrpId(java.lang.String stockerGrpId);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     insertAllOhbPortGroup (insert List of OHB_PORT_RLT)function
     * @param     List of OHB_PORT_RLT
     * @return    count
     * @retval    insert records count.
     * @attention
     * @note      (SQL-346) insert List of OHB_PORT_RLT
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int insertAllOhbPortGroup(@Param("ohbPortRltList") List<OhbPortRlt> ohbPortRltList);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectModifyOhbPortList (Get List of OHB_PORT_RLT)function
     * @param     ohb OHB_PORT_RLT (Search condition)
     * @return    List of OHB_PORT_RLT
     * @retval    Return a list of OhbPortGroupModifyModel
     * @attention
     * @note      Return List of OhbPortGroupModifyModel
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<OhbPortGroupModifyModel> selectModifyOhbPortList(Ohb ohb);
}
