package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.top.ReqGetPortsListEntity;
import net.muratec.mcs.model.Port;
import net.muratec.mcs.model.PortExample;
import net.muratec.mcs.model.PortsModel;

import org.apache.ibatis.annotations.Param;

public interface PortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    long countByExample(PortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int deleteByExample(PortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int deleteByPrimaryKey(String portId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int insert(Port record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int insertSelective(Port record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    List<Port> selectByExample(PortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    Port selectByPrimaryKey(String portId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") Port record, @Param("example") PortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int updateByExample(@Param("record") Port record, @Param("example") PortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int updateByPrimaryKeySelective(Port record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int updateByPrimaryKey(Port record);
 // =============================
    // MCS_v3 Unique Function From Here
    // =============================
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select Ports List
     * @param       reqEntity   (search criteria)
     * @return      Ports List
     * @retval      List of Ports Model Style
     * @attention
     * @note        Select Ports List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<PortsModel> selectList(ReqGetPortsListEntity reqEntity);

	// STD APL 2020.03.03 董 天津村研  MCSV4　GUI開発  Ver3.0 Rev.000 
	// =============================
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select Ports List By tscId
     * @param       reqEntity   (search criteria)
     * @return      Ports List
     * @retval      List of Ports Model Style
     * @attention
     * @note        Select Ports List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     * 2020.03.03 董 天津村研  MCSV4　GUI開発  Ver3.0 Rev.000 
     ******************************************************************************
     */
    //@formatter:on
    List<PortsModel> selectPortList(Port record);
    // END APL 2020.03.03 董 天津村研  MCSV4　GUI開発  Ver3.0 Rev.000 
  //@formatter:off
    /**
     ******************************************************************************
     * @brief     Get the total number of Ports List
     * @param     reqEntity     (search criteria)
     * @return    the total number of Ports List
     * @retval    int Style
     * @attention
     * @note      Get the total number of Ports List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int getCount(ReqGetPortsListEntity reqEntity);
}