package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.entity.maint.ProcessConfEntity;
import net.muratec.mcs.entity.maint.ReqGetProcStateManagementEntity;
import net.muratec.mcs.model.IdListSelectModel;
import net.muratec.mcs.model.ProcStateManagementModel;
import net.muratec.mcs.model.Process;
import net.muratec.mcs.model.ProcessExample;

public interface ProcessMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    long countByExample(ProcessExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    int deleteByExample(ProcessExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer systemId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    int insert(Process record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    int insertSelective(Process record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    List<Process> selectByExample(ProcessExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    Process selectByPrimaryKey(Integer systemId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Process record, @Param("example") ProcessExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    int updateByExample(@Param("record") Process record, @Param("example") ProcessExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Process record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    int updateByPrimaryKey(Process record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     idSelect    (Get ID LIST)function
     * @param     abbreviation       Value of ABBREVIATION
     * @return    A PROCESS and AMHS_NAME listing based on PROC_TYPE
     * @retval
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<IdListSelectModel> idSelect(String abbreviation);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectList    (Get Process list)function
     * @param     reqEntity     Request from client
     * @return    Process list
     * @retval    Return in Process list
     * @attention
     * @note      Get Process list
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<ProcessConfEntity> selectList(AjaxDataTablesReqBaseEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     getCount      (Get the total number of records in the Process list)function
     * @param     reqEntity     Request from client
     * @return    the total number of records in the Process
     * @retval    Return in int format
     * @attention
     * @note      Get the total number of records in the Process list
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int getCount();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     getServiceId  get Service ID function
     * @param
     * @return    Service ID List
     * @retval
     * @attention
     * @note      Get Service ID List
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> getServiceId();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectProcStateManageList function
     * @param
     * @return    ProcStateManagement List
     * @retval
     * @attention
     * @note      Get Process State Management List
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<ProcStateManagementModel> selectProcStateManageList(ReqGetProcStateManagementEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     getProcStateManagementCount function
     * @param
     * @return    ProcStateManagement List Count
     * @retval
     * @attention
     * @note      Get Process State Management List Count
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int getProcStateManagementCount(ReqGetProcStateManagementEntity reqEntity);
}
