package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.entity.maint.ReqGetTransferRoutePatternEntity;
import net.muratec.mcs.model.Route;
import net.muratec.mcs.model.RouteExample;
import net.muratec.mcs.model.RouteKey;
import net.muratec.mcs.model.TransferRoutePatternModel;

public interface RouteMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROUTE
     * @mbg.generated
     */
    long countByExample(RouteExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROUTE
     * @mbg.generated
     */
    int deleteByExample(RouteExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROUTE
     * @mbg.generated
     */
    int deleteByPrimaryKey(RouteKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROUTE
     * @mbg.generated
     */
    int insert(Route record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROUTE
     * @mbg.generated
     */
    int insertSelective(Route record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROUTE
     * @mbg.generated
     */
    List<Route> selectByExample(RouteExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROUTE
     * @mbg.generated
     */
    Route selectByPrimaryKey(RouteKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROUTE
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Route record, @Param("example") RouteExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROUTE
     * @mbg.generated
     */
    int updateByExample(@Param("record") Route record, @Param("example") RouteExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROUTE
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Route record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROUTE
     * @mbg.generated
     */
    int updateByPrimaryKey(Route record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectTransferRouteList (get List of Transfer Route)
     * @param
     * @return    Route List
     * @retval    List<Route>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<Route> selectTransferRouteList(AjaxDataTablesReqBaseEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     getRoutePatternId (get DISTINCT PatternId List of Route)
     * @param
     * @return    Route List (Pattern Id)
     * @retval    List<Route>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> getRoutePatternId();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectPatternList (get List of Transfer Route)
     * @param
     * @return    TransferRoutePattern List
     * @retval    List<TransferRoutePatternModel>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<TransferRoutePatternModel> selectPatternList(AjaxDataTablesReqBaseEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectPattern (get List of Transfer Route)
     * @param
     * @return    TransferRoutePatternModel
     * @retval    TransferRoutePatternModel
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    TransferRoutePatternModel selectPattern(ReqGetTransferRoutePatternEntity reqEntity);
}
