package net.muratec.mcs.mapper;

import java.util.List;
import net.muratec.mcs.model.StockerZone;
import net.muratec.mcs.model.StockerZoneExample;
import net.muratec.mcs.model.StockerZoneKey;
import org.apache.ibatis.annotations.Param;

public interface StockerZoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE
     *
     * @mbg.generated
     */
    long countByExample(StockerZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE
     *
     * @mbg.generated
     */
    int deleteByExample(StockerZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(StockerZoneKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE
     *
     * @mbg.generated
     */
    int insert(StockerZone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE
     *
     * @mbg.generated
     */
    int insertSelective(StockerZone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE
     *
     * @mbg.generated
     */
    List<StockerZone> selectByExample(StockerZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE
     *
     * @mbg.generated
     */
    StockerZone selectByPrimaryKey(StockerZoneKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StockerZone record, @Param("example") StockerZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StockerZone record, @Param("example") StockerZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StockerZone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockerZone record);
}