package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.model.TakeoverRule;
import net.muratec.mcs.model.TakeoverRuleExample;

public interface TakeoverRuleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE
     * @mbg.generated
     */
    long countByExample(TakeoverRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE
     * @mbg.generated
     */
    int deleteByExample(TakeoverRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short ruleNo);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE
     * @mbg.generated
     */
    int insert(TakeoverRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE
     * @mbg.generated
     */
    int insertSelective(TakeoverRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE
     * @mbg.generated
     */
    List<TakeoverRule> selectByExample(TakeoverRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE
     * @mbg.generated
     */
    TakeoverRule selectByPrimaryKey(Short ruleNo);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TakeoverRule record, @Param("example") TakeoverRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE
     * @mbg.generated
     */
    int updateByExample(@Param("record") TakeoverRule record, @Param("example") TakeoverRuleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TakeoverRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE
     * @mbg.generated
     */
    int updateByPrimaryKey(TakeoverRule record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Select TakeoverRuleModel List(RowNum)
     * @return    TakeoverRule List
     * @retval    List<TakeoverRule>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<TakeoverRule> selectTakeoverRuleRowNum(AjaxDataTablesReqBaseEntity reqEntity);
    // Step4P2 2017_11_24：Delete unused method
}