package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.maint.ReqTakeoverRuleRltEntity;
import net.muratec.mcs.model.TakeoverRuleRlt;
import net.muratec.mcs.model.TakeoverRuleRltExample;
import net.muratec.mcs.model.TakeoverRuleRltKey;

public interface TakeoverRuleRltMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE_RLT
     * @mbg.generated
     */
    long countByExample(TakeoverRuleRltExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE_RLT
     * @mbg.generated
     */
    int deleteByExample(TakeoverRuleRltExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE_RLT
     * @mbg.generated
     */
    int deleteByPrimaryKey(TakeoverRuleRltKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE_RLT
     * @mbg.generated
     */
    int insert(TakeoverRuleRlt record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE_RLT
     * @mbg.generated
     */
    int insertSelective(TakeoverRuleRlt record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE_RLT
     * @mbg.generated
     */
    List<TakeoverRuleRlt> selectByExample(TakeoverRuleRltExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE_RLT
     * @mbg.generated
     */
    TakeoverRuleRlt selectByPrimaryKey(TakeoverRuleRltKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE_RLT
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TakeoverRuleRlt record,
            @Param("example") TakeoverRuleRltExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE_RLT
     * @mbg.generated
     */
    int updateByExample(@Param("record") TakeoverRuleRlt record, @Param("example") TakeoverRuleRltExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE_RLT
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TakeoverRuleRlt record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table TAKEOVER_RULE_RLT
     * @mbg.generated
     */
    int updateByPrimaryKey(TakeoverRuleRlt record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectByDefaultTransGrpId (Get list of DefaultTransGrpId) function
     * @param
     * @return    List of DefaultTransGrpId
     * @retval
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectByDefaultTransGrpId();

  //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectByAMHSGrpId (Get list of AMHSGrpId) function
     * @param
     * @return    List of AMHSGrpId
     * @retval
     * @attention
     * @note      Retrieve logs matching search criteria.
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectByAMHSGrpId();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Add TakeoverRuleRlt
     * @param       destination   (Add Criterion)
     * @param       reqEntity     (Additional Data)
     * @return      the number of operation successes
     * @retval      int Style
     * @attention
     * @note        Add TakeoverRuleRlt.
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    void addTakeoverRltMemberList(@Param("ruleNo") short ruleNo,
            @Param("reqEntity") List<ReqTakeoverRuleRltEntity> reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get TakeoverRuleMemberList
     * @param       ruleNo (PK)
     * @return      Takeover Rule Member List
     * @retval      List<TakeoverRuleRlt>
     * @attention
     * @note        Get TakeoverRuleMemberList.
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<TakeoverRuleRlt> getTakeoverRltMemberList(@Param("ruleNo") Short ruleNo);

}
