package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.entity.maint.ReqUnitGroupMemberEntity;
import net.muratec.mcs.entity.maint.ModuleIdEntity;

import net.muratec.mcs.model.Unit;
import net.muratec.mcs.model.UnitExample;
import net.muratec.mcs.model.UnitModel;

import org.apache.ibatis.annotations.Param;

public interface UnitMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table UNIT
     * @mbg.generated
     */
    long countByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table UNIT
     * @mbg.generated
     */
    int deleteByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table UNIT
     * @mbg.generated
     */
    int deleteByPrimaryKey(String unitId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table UNIT
     * @mbg.generated
     */
    int insert(Unit record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table UNIT
     * @mbg.generated
     */
    int insertSelective(Unit record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table UNIT
     * @mbg.generated
     */
    List<Unit> selectByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table UNIT
     * @mbg.generated
     */
    Unit selectByPrimaryKey(String unitId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table UNIT
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Unit record, @Param("example") UnitExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table UNIT
     * @mbg.generated
     */
    int updateByExample(@Param("record") Unit record, @Param("example") UnitExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table UNIT
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Unit record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table UNIT
     * @mbg.generated
     */
    int updateByPrimaryKey(Unit record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Select Unit List(RowNum)
     * @return    Unit List
     * @retval    List<UnitModel>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<UnitModel> selectUnitRowNum(AjaxDataTablesReqBaseEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Select Unit List(RowNum)
     * @return    Unit List
     * @retval    List<UnitModel>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<UnitModel> selectUnitAllList();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get Unit L State by UNIT_ID
     * @param       unitId   (search criterion)
     * @return      UNIT_L_STATE(String)
     * @retval      String
     * @attention
     * @note        Get Unit Logical State by UNIT_ID.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    String selectUnitLStateByUnitId(String unitId);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get AMHS_ID List by UNIT_ID
     * @param       unitList   (search criterion)
     * @return      AMHS_ID
     * @retval      List<String>
     * @attention
     * @note        Get AMHS ID List by UNIT_ID.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectAmhsIdByUnitId(@Param("unitList")List<ReqUnitGroupMemberEntity> unitList);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     updateDelModuleId function
     * @param     reqEntity  Request Unit
     * @return
     * @retval
     * @attention
     * @note      Update MODULE_ID is null
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int updateDelModuleId(@Param("unitId") String unitId);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get UNIT_ID List by MODULE_ID
     * @param       moduleList   (search criterion)
     * @return      UNIT_ID
     * @retval      List<String>
     * @attention
     * @note        Get UNIT_ID List by MODULE_ID.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectUnitIdByModuleId(@Param("moduleList") List<ModuleIdEntity> moduleList);

    
}
