package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.top.ReqGetVehiclesListEntity;
import net.muratec.mcs.model.Vehicle;
import net.muratec.mcs.model.VehicleExample;
import net.muratec.mcs.model.VehicleKey;
import net.muratec.mcs.model.VehiclesModel;

import org.apache.ibatis.annotations.Param;

public interface VehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    long countByExample(VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int deleteByExample(VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int deleteByPrimaryKey(VehicleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int insert(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int insertSelective(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    List<Vehicle> selectByExample(VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    Vehicle selectByPrimaryKey(VehicleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") Vehicle record, @Param("example") VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int updateByExample(@Param("record") Vehicle record, @Param("example") VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int updateByPrimaryKeySelective(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    int updateByPrimaryKey(Vehicle record);
    // =============================
    // MCS_v3 Unique Function From Here
    // =============================
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select Vehicles List
     * @param       reqEntity   (search criteria)
     * @return      Vehicles List
     * @retval      List of Vehicles Model Style
     * @attention
     * @note        Select Vehicles List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<VehiclesModel> selectList(ReqGetVehiclesListEntity reqEntity);
 
    /******************************************************************************
    * @brief       Select Vehicles List By llcId
    * @param       reqEntity   (search criteria)
    * @return      Vehicles List
    * @retval      List of Vehicles Model Style
    * @attention
    * @note        Select Vehicles List that matches search criteria.
    * ----------------------------------------------------------------------------
    * DATE       VER.        DESCRIPTION                                    AUTHOR
    * ----------------------------------------------------------------------------
    * 2020.03.03 董 天津村研  MCSV4　GUI開発  Ver3.0 Rev.000 
    ******************************************************************************
    */
   //@formatter:on
   List<Vehicle> selectVehicleList(VehicleExample example);
    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Get the total number of Vehicles List
     * @param     reqEntity     (search criteria)
     * @return    the total number of Vehicles List
     * @retval    int Style
     * @attention
     * @note      Get the total number of Vehicles List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int getCount(ReqGetVehiclesListEntity reqEntity);
}