package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.model.Vip;
import net.muratec.mcs.model.VipExample;
import net.muratec.mcs.model.VipConfModel;

public interface VipMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table VIP
     * @mbg.generated
     */
    long countByExample(VipExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table VIP
     * @mbg.generated
     */
    int deleteByExample(VipExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table VIP
     * @mbg.generated
     */
    int deleteByPrimaryKey(String vipId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table VIP
     * @mbg.generated
     */
    int insert(Vip record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table VIP
     * @mbg.generated
     */
    int insertSelective(Vip record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table VIP
     * @mbg.generated
     */
    List<Vip> selectByExample(VipExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table VIP
     * @mbg.generated
     */
    Vip selectByPrimaryKey(String vipId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table VIP
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Vip record, @Param("example") VipExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table VIP
     * @mbg.generated
     */
    int updateByExample(@Param("record") Vip record, @Param("example") VipExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table VIP
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Vip record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table VIP
     * @mbg.generated
     */
    int updateByPrimaryKey(Vip record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Select VipConfModel List(RowNum)
     * @return    VipConfModel List
     * @retval    List<VipConfModel>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<VipConfModel> selectVipRowNum(AjaxDataTablesReqBaseEntity reqEntity);
}
