package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.model.Zone;
import net.muratec.mcs.model.ZoneExample;
import net.muratec.mcs.model.ZoneModel;

public interface ZoneMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ZONE
     * @mbg.generated
     */
    long countByExample(ZoneExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ZONE
     * @mbg.generated
     */
    int deleteByExample(ZoneExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ZONE
     * @mbg.generated
     */
    int deleteByPrimaryKey(String zoneId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ZONE
     * @mbg.generated
     */
    int insert(Zone record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ZONE
     * @mbg.generated
     */
    int insertSelective(Zone record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ZONE
     * @mbg.generated
     */
    List<Zone> selectByExample(ZoneExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ZONE
     * @mbg.generated
     */
    Zone selectByPrimaryKey(String zoneId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ZONE
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Zone record, @Param("example") ZoneExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ZONE
     * @mbg.generated
     */
    int updateByExample(@Param("record") Zone record, @Param("example") ZoneExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ZONE
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Zone record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ZONE
     * @mbg.generated
     */
    int updateByPrimaryKey(Zone record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Select Zone List(RowNum)
     * @return    Zone List
     * @retval    List<ZoneModel>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<ZoneModel> selectZoneRowNum(AjaxDataTablesReqBaseEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Select Zone List(RowNum)
     * @return    Zone List
     * @retval    List<ZoneModel>
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<ZoneModel> selectAllList();

}
