package net.muratec.mcs.model;

import java.sql.Timestamp;

/* 無効化機能：先行着手をした結果、不要になった機能 */
public class AlarmReportHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM_REPORT_HISTORY.TIME
     *
     * @mbg.generated
     */
    private Timestamp time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM_REPORT_HISTORY.MCS_ALARM_ID
     *
     * @mbg.generated
     */
    private Long mcsAlarmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM_REPORT_HISTORY.RESULT
     *
     * @mbg.generated
     */
    private Long result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM_REPORT_HISTORY.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM_REPORT_HISTORY.TIME
     *
     * @return the value of ALARM_REPORT_HISTORY.TIME
     *
     * @mbg.generated
     */
    public Timestamp getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM_REPORT_HISTORY.TIME
     *
     * @param time the value for ALARM_REPORT_HISTORY.TIME
     *
     * @mbg.generated
     */
    public void setTime(Timestamp time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM_REPORT_HISTORY.MCS_ALARM_ID
     *
     * @return the value of ALARM_REPORT_HISTORY.MCS_ALARM_ID
     *
     * @mbg.generated
     */
    public Long getMcsAlarmId() {
        return mcsAlarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM_REPORT_HISTORY.MCS_ALARM_ID
     *
     * @param mcsAlarmId the value for ALARM_REPORT_HISTORY.MCS_ALARM_ID
     *
     * @mbg.generated
     */
    public void setMcsAlarmId(Long mcsAlarmId) {
        this.mcsAlarmId = mcsAlarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM_REPORT_HISTORY.RESULT
     *
     * @return the value of ALARM_REPORT_HISTORY.RESULT
     *
     * @mbg.generated
     */
    public Long getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM_REPORT_HISTORY.RESULT
     *
     * @param result the value for ALARM_REPORT_HISTORY.RESULT
     *
     * @mbg.generated
     */
    public void setResult(Long result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM_REPORT_HISTORY.CONTENT
     *
     * @return the value of ALARM_REPORT_HISTORY.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM_REPORT_HISTORY.CONTENT
     *
     * @param content the value for ALARM_REPORT_HISTORY.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }
}