package net.muratec.mcs.model;

import java.util.ArrayList;
import java.util.List;

public class AltDeviceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    public AltDeviceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAltSrcElementIdIsNull() {
            addCriterion("ALT_SRC_ELEMENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdIsNotNull() {
            addCriterion("ALT_SRC_ELEMENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdEqualTo(String value) {
            addCriterion("ALT_SRC_ELEMENT_ID =", value, "altSrcElementId");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdNotEqualTo(String value) {
            addCriterion("ALT_SRC_ELEMENT_ID <>", value, "altSrcElementId");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdGreaterThan(String value) {
            addCriterion("ALT_SRC_ELEMENT_ID >", value, "altSrcElementId");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdGreaterThanOrEqualTo(String value) {
            addCriterion("ALT_SRC_ELEMENT_ID >=", value, "altSrcElementId");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdLessThan(String value) {
            addCriterion("ALT_SRC_ELEMENT_ID <", value, "altSrcElementId");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdLessThanOrEqualTo(String value) {
            addCriterion("ALT_SRC_ELEMENT_ID <=", value, "altSrcElementId");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdLike(String value) {
            addCriterion("ALT_SRC_ELEMENT_ID like", value, "altSrcElementId");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdNotLike(String value) {
            addCriterion("ALT_SRC_ELEMENT_ID not like", value, "altSrcElementId");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdIn(List<String> values) {
            addCriterion("ALT_SRC_ELEMENT_ID in", values, "altSrcElementId");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdNotIn(List<String> values) {
            addCriterion("ALT_SRC_ELEMENT_ID not in", values, "altSrcElementId");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdBetween(String value1, String value2) {
            addCriterion("ALT_SRC_ELEMENT_ID between", value1, value2, "altSrcElementId");
            return (Criteria) this;
        }

        public Criteria andAltSrcElementIdNotBetween(String value1, String value2) {
            addCriterion("ALT_SRC_ELEMENT_ID not between", value1, value2, "altSrcElementId");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyIsNull() {
            addCriterion("ALT_SRC_KEY is null");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyIsNotNull() {
            addCriterion("ALT_SRC_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyEqualTo(String value) {
            addCriterion("ALT_SRC_KEY =", value, "altSrcKey");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyNotEqualTo(String value) {
            addCriterion("ALT_SRC_KEY <>", value, "altSrcKey");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyGreaterThan(String value) {
            addCriterion("ALT_SRC_KEY >", value, "altSrcKey");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyGreaterThanOrEqualTo(String value) {
            addCriterion("ALT_SRC_KEY >=", value, "altSrcKey");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyLessThan(String value) {
            addCriterion("ALT_SRC_KEY <", value, "altSrcKey");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyLessThanOrEqualTo(String value) {
            addCriterion("ALT_SRC_KEY <=", value, "altSrcKey");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyLike(String value) {
            addCriterion("ALT_SRC_KEY like", value, "altSrcKey");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyNotLike(String value) {
            addCriterion("ALT_SRC_KEY not like", value, "altSrcKey");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyIn(List<String> values) {
            addCriterion("ALT_SRC_KEY in", values, "altSrcKey");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyNotIn(List<String> values) {
            addCriterion("ALT_SRC_KEY not in", values, "altSrcKey");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyBetween(String value1, String value2) {
            addCriterion("ALT_SRC_KEY between", value1, value2, "altSrcKey");
            return (Criteria) this;
        }

        public Criteria andAltSrcKeyNotBetween(String value1, String value2) {
            addCriterion("ALT_SRC_KEY not between", value1, value2, "altSrcKey");
            return (Criteria) this;
        }

        public Criteria andAltPriorityIsNull() {
            addCriterion("ALT_PRIORITY is null");
            return (Criteria) this;
        }

        public Criteria andAltPriorityIsNotNull() {
            addCriterion("ALT_PRIORITY is not null");
            return (Criteria) this;
        }

        public Criteria andAltPriorityEqualTo(Short value) {
            addCriterion("ALT_PRIORITY =", value, "altPriority");
            return (Criteria) this;
        }

        public Criteria andAltPriorityNotEqualTo(Short value) {
            addCriterion("ALT_PRIORITY <>", value, "altPriority");
            return (Criteria) this;
        }

        public Criteria andAltPriorityGreaterThan(Short value) {
            addCriterion("ALT_PRIORITY >", value, "altPriority");
            return (Criteria) this;
        }

        public Criteria andAltPriorityGreaterThanOrEqualTo(Short value) {
            addCriterion("ALT_PRIORITY >=", value, "altPriority");
            return (Criteria) this;
        }

        public Criteria andAltPriorityLessThan(Short value) {
            addCriterion("ALT_PRIORITY <", value, "altPriority");
            return (Criteria) this;
        }

        public Criteria andAltPriorityLessThanOrEqualTo(Short value) {
            addCriterion("ALT_PRIORITY <=", value, "altPriority");
            return (Criteria) this;
        }

        public Criteria andAltPriorityIn(List<Short> values) {
            addCriterion("ALT_PRIORITY in", values, "altPriority");
            return (Criteria) this;
        }

        public Criteria andAltPriorityNotIn(List<Short> values) {
            addCriterion("ALT_PRIORITY not in", values, "altPriority");
            return (Criteria) this;
        }

        public Criteria andAltPriorityBetween(Short value1, Short value2) {
            addCriterion("ALT_PRIORITY between", value1, value2, "altPriority");
            return (Criteria) this;
        }

        public Criteria andAltPriorityNotBetween(Short value1, Short value2) {
            addCriterion("ALT_PRIORITY not between", value1, value2, "altPriority");
            return (Criteria) this;
        }

        public Criteria andAltSrcTypeIsNull() {
            addCriterion("ALT_SRC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAltSrcTypeIsNotNull() {
            addCriterion("ALT_SRC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAltSrcTypeEqualTo(Short value) {
            addCriterion("ALT_SRC_TYPE =", value, "altSrcType");
            return (Criteria) this;
        }

        public Criteria andAltSrcTypeNotEqualTo(Short value) {
            addCriterion("ALT_SRC_TYPE <>", value, "altSrcType");
            return (Criteria) this;
        }

        public Criteria andAltSrcTypeGreaterThan(Short value) {
            addCriterion("ALT_SRC_TYPE >", value, "altSrcType");
            return (Criteria) this;
        }

        public Criteria andAltSrcTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("ALT_SRC_TYPE >=", value, "altSrcType");
            return (Criteria) this;
        }

        public Criteria andAltSrcTypeLessThan(Short value) {
            addCriterion("ALT_SRC_TYPE <", value, "altSrcType");
            return (Criteria) this;
        }

        public Criteria andAltSrcTypeLessThanOrEqualTo(Short value) {
            addCriterion("ALT_SRC_TYPE <=", value, "altSrcType");
            return (Criteria) this;
        }

        public Criteria andAltSrcTypeIn(List<Short> values) {
            addCriterion("ALT_SRC_TYPE in", values, "altSrcType");
            return (Criteria) this;
        }

        public Criteria andAltSrcTypeNotIn(List<Short> values) {
            addCriterion("ALT_SRC_TYPE not in", values, "altSrcType");
            return (Criteria) this;
        }

        public Criteria andAltSrcTypeBetween(Short value1, Short value2) {
            addCriterion("ALT_SRC_TYPE between", value1, value2, "altSrcType");
            return (Criteria) this;
        }

        public Criteria andAltSrcTypeNotBetween(Short value1, Short value2) {
            addCriterion("ALT_SRC_TYPE not between", value1, value2, "altSrcType");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Short value) {
            addCriterion("FLAG =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Short value) {
            addCriterion("FLAG <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Short value) {
            addCriterion("FLAG >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("FLAG >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Short value) {
            addCriterion("FLAG <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Short value) {
            addCriterion("FLAG <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Short> values) {
            addCriterion("FLAG in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Short> values) {
            addCriterion("FLAG not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Short value1, Short value2) {
            addCriterion("FLAG between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Short value1, Short value2) {
            addCriterion("FLAG not between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andAltDeviceIsNull() {
            addCriterion("ALT_DEVICE is null");
            return (Criteria) this;
        }

        public Criteria andAltDeviceIsNotNull() {
            addCriterion("ALT_DEVICE is not null");
            return (Criteria) this;
        }

        public Criteria andAltDeviceEqualTo(String value) {
            addCriterion("ALT_DEVICE =", value, "altDevice");
            return (Criteria) this;
        }

        public Criteria andAltDeviceNotEqualTo(String value) {
            addCriterion("ALT_DEVICE <>", value, "altDevice");
            return (Criteria) this;
        }

        public Criteria andAltDeviceGreaterThan(String value) {
            addCriterion("ALT_DEVICE >", value, "altDevice");
            return (Criteria) this;
        }

        public Criteria andAltDeviceGreaterThanOrEqualTo(String value) {
            addCriterion("ALT_DEVICE >=", value, "altDevice");
            return (Criteria) this;
        }

        public Criteria andAltDeviceLessThan(String value) {
            addCriterion("ALT_DEVICE <", value, "altDevice");
            return (Criteria) this;
        }

        public Criteria andAltDeviceLessThanOrEqualTo(String value) {
            addCriterion("ALT_DEVICE <=", value, "altDevice");
            return (Criteria) this;
        }

        public Criteria andAltDeviceLike(String value) {
            addCriterion("ALT_DEVICE like", value, "altDevice");
            return (Criteria) this;
        }

        public Criteria andAltDeviceNotLike(String value) {
            addCriterion("ALT_DEVICE not like", value, "altDevice");
            return (Criteria) this;
        }

        public Criteria andAltDeviceIn(List<String> values) {
            addCriterion("ALT_DEVICE in", values, "altDevice");
            return (Criteria) this;
        }

        public Criteria andAltDeviceNotIn(List<String> values) {
            addCriterion("ALT_DEVICE not in", values, "altDevice");
            return (Criteria) this;
        }

        public Criteria andAltDeviceBetween(String value1, String value2) {
            addCriterion("ALT_DEVICE between", value1, value2, "altDevice");
            return (Criteria) this;
        }

        public Criteria andAltDeviceNotBetween(String value1, String value2) {
            addCriterion("ALT_DEVICE not between", value1, value2, "altDevice");
            return (Criteria) this;
        }

        public Criteria andEnableFlagIsNull() {
            addCriterion("ENABLE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andEnableFlagIsNotNull() {
            addCriterion("ENABLE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andEnableFlagEqualTo(Short value) {
            addCriterion("ENABLE_FLAG =", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagNotEqualTo(Short value) {
            addCriterion("ENABLE_FLAG <>", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagGreaterThan(Short value) {
            addCriterion("ENABLE_FLAG >", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("ENABLE_FLAG >=", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagLessThan(Short value) {
            addCriterion("ENABLE_FLAG <", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagLessThanOrEqualTo(Short value) {
            addCriterion("ENABLE_FLAG <=", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagIn(List<Short> values) {
            addCriterion("ENABLE_FLAG in", values, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagNotIn(List<Short> values) {
            addCriterion("ENABLE_FLAG not in", values, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagBetween(Short value1, Short value2) {
            addCriterion("ENABLE_FLAG between", value1, value2, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagNotBetween(Short value1, Short value2) {
            addCriterion("ENABLE_FLAG not between", value1, value2, "enableFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ALT_DEVICE
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}