package net.muratec.mcs.model;

import java.sql.Timestamp;

public class AstarHeuristicCost extends AstarHeuristicCostKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ASTAR_HEURISTIC_COST.AVE_TIME
     * @mbg.generated
     */
    private Integer aveTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ASTAR_HEURISTIC_COST.LAST_MODIFIED_TIME
     * @mbg.generated
     */
    private Timestamp lastModifiedTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ASTAR_HEURISTIC_COST.PASSED_COUNT
     * @mbg.generated
     */
    private Long passedCount;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ASTAR_HEURISTIC_COST.AVE_TIME
     * @return  the value of ASTAR_HEURISTIC_COST.AVE_TIME
     * @mbg.generated
     */
    public Integer getAveTime() {

        return aveTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ASTAR_HEURISTIC_COST.AVE_TIME
     * @param aveTime  the value for ASTAR_HEURISTIC_COST.AVE_TIME
     * @mbg.generated
     */
    public void setAveTime(Integer aveTime) {

        this.aveTime = aveTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ASTAR_HEURISTIC_COST.LAST_MODIFIED_TIME
     * @return  the value of ASTAR_HEURISTIC_COST.LAST_MODIFIED_TIME
     * @mbg.generated
     */
    public Timestamp getLastModifiedTime() {

        return lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ASTAR_HEURISTIC_COST.LAST_MODIFIED_TIME
     * @param lastModifiedTime  the value for ASTAR_HEURISTIC_COST.LAST_MODIFIED_TIME
     * @mbg.generated
     */
    public void setLastModifiedTime(Timestamp lastModifiedTime) {

        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ASTAR_HEURISTIC_COST.PASSED_COUNT
     * @return  the value of ASTAR_HEURISTIC_COST.PASSED_COUNT
     * @mbg.generated
     */
    public Long getPassedCount() {

        return passedCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ASTAR_HEURISTIC_COST.PASSED_COUNT
     * @param passedCount  the value for ASTAR_HEURISTIC_COST.PASSED_COUNT
     * @mbg.generated
     */
    public void setPassedCount(Long passedCount) {

        this.passedCount = passedCount;
    }
}
