package net.muratec.mcs.model;

import java.util.ArrayList;
import java.util.List;
import java.sql.Timestamp;

public class AstarHeuristicCostExample {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    public AstarHeuristicCostExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {

        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    public String getOrderByClause() {

        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {

        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    public boolean isDistinct() {

        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {

        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    public void or(Criteria criteria) {

        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    public Criteria or() {

        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    public Criteria createCriteria() {

        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {

        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    public void clear() {

        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {

            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {

            return criteria;
        }

        public List<Criterion> getCriteria() {

            return criteria;
        }

        protected void addCriterion(String condition) {

            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {

            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {

            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSrcAmhsIdIsNull() {

            addCriterion("SRC_AMHS_ID is null");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdIsNotNull() {

            addCriterion("SRC_AMHS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdEqualTo(String value) {

            addCriterion("SRC_AMHS_ID =", value, "srcAmhsId");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdNotEqualTo(String value) {

            addCriterion("SRC_AMHS_ID <>", value, "srcAmhsId");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdGreaterThan(String value) {

            addCriterion("SRC_AMHS_ID >", value, "srcAmhsId");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdGreaterThanOrEqualTo(String value) {

            addCriterion("SRC_AMHS_ID >=", value, "srcAmhsId");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdLessThan(String value) {

            addCriterion("SRC_AMHS_ID <", value, "srcAmhsId");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdLessThanOrEqualTo(String value) {

            addCriterion("SRC_AMHS_ID <=", value, "srcAmhsId");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdLike(String value) {

            addCriterion("SRC_AMHS_ID like", value, "srcAmhsId");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdNotLike(String value) {

            addCriterion("SRC_AMHS_ID not like", value, "srcAmhsId");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdIn(List<String> values) {

            addCriterion("SRC_AMHS_ID in", values, "srcAmhsId");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdNotIn(List<String> values) {

            addCriterion("SRC_AMHS_ID not in", values, "srcAmhsId");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdBetween(String value1, String value2) {

            addCriterion("SRC_AMHS_ID between", value1, value2, "srcAmhsId");
            return (Criteria) this;
        }

        public Criteria andSrcAmhsIdNotBetween(String value1, String value2) {

            addCriterion("SRC_AMHS_ID not between", value1, value2, "srcAmhsId");
            return (Criteria) this;
        }

        public Criteria andSrcLocIsNull() {

            addCriterion("SRC_LOC is null");
            return (Criteria) this;
        }

        public Criteria andSrcLocIsNotNull() {

            addCriterion("SRC_LOC is not null");
            return (Criteria) this;
        }

        public Criteria andSrcLocEqualTo(String value) {

            addCriterion("SRC_LOC =", value, "srcLoc");
            return (Criteria) this;
        }

        public Criteria andSrcLocNotEqualTo(String value) {

            addCriterion("SRC_LOC <>", value, "srcLoc");
            return (Criteria) this;
        }

        public Criteria andSrcLocGreaterThan(String value) {

            addCriterion("SRC_LOC >", value, "srcLoc");
            return (Criteria) this;
        }

        public Criteria andSrcLocGreaterThanOrEqualTo(String value) {

            addCriterion("SRC_LOC >=", value, "srcLoc");
            return (Criteria) this;
        }

        public Criteria andSrcLocLessThan(String value) {

            addCriterion("SRC_LOC <", value, "srcLoc");
            return (Criteria) this;
        }

        public Criteria andSrcLocLessThanOrEqualTo(String value) {

            addCriterion("SRC_LOC <=", value, "srcLoc");
            return (Criteria) this;
        }

        public Criteria andSrcLocLike(String value) {

            addCriterion("SRC_LOC like", value, "srcLoc");
            return (Criteria) this;
        }

        public Criteria andSrcLocNotLike(String value) {

            addCriterion("SRC_LOC not like", value, "srcLoc");
            return (Criteria) this;
        }

        public Criteria andSrcLocIn(List<String> values) {

            addCriterion("SRC_LOC in", values, "srcLoc");
            return (Criteria) this;
        }

        public Criteria andSrcLocNotIn(List<String> values) {

            addCriterion("SRC_LOC not in", values, "srcLoc");
            return (Criteria) this;
        }

        public Criteria andSrcLocBetween(String value1, String value2) {

            addCriterion("SRC_LOC between", value1, value2, "srcLoc");
            return (Criteria) this;
        }

        public Criteria andSrcLocNotBetween(String value1, String value2) {

            addCriterion("SRC_LOC not between", value1, value2, "srcLoc");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdIsNull() {

            addCriterion("DST_AMHS_ID is null");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdIsNotNull() {

            addCriterion("DST_AMHS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdEqualTo(String value) {

            addCriterion("DST_AMHS_ID =", value, "dstAmhsId");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdNotEqualTo(String value) {

            addCriterion("DST_AMHS_ID <>", value, "dstAmhsId");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdGreaterThan(String value) {

            addCriterion("DST_AMHS_ID >", value, "dstAmhsId");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdGreaterThanOrEqualTo(String value) {

            addCriterion("DST_AMHS_ID >=", value, "dstAmhsId");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdLessThan(String value) {

            addCriterion("DST_AMHS_ID <", value, "dstAmhsId");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdLessThanOrEqualTo(String value) {

            addCriterion("DST_AMHS_ID <=", value, "dstAmhsId");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdLike(String value) {

            addCriterion("DST_AMHS_ID like", value, "dstAmhsId");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdNotLike(String value) {

            addCriterion("DST_AMHS_ID not like", value, "dstAmhsId");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdIn(List<String> values) {

            addCriterion("DST_AMHS_ID in", values, "dstAmhsId");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdNotIn(List<String> values) {

            addCriterion("DST_AMHS_ID not in", values, "dstAmhsId");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdBetween(String value1, String value2) {

            addCriterion("DST_AMHS_ID between", value1, value2, "dstAmhsId");
            return (Criteria) this;
        }

        public Criteria andDstAmhsIdNotBetween(String value1, String value2) {

            addCriterion("DST_AMHS_ID not between", value1, value2, "dstAmhsId");
            return (Criteria) this;
        }

        public Criteria andDstLocIsNull() {

            addCriterion("DST_LOC is null");
            return (Criteria) this;
        }

        public Criteria andDstLocIsNotNull() {

            addCriterion("DST_LOC is not null");
            return (Criteria) this;
        }

        public Criteria andDstLocEqualTo(String value) {

            addCriterion("DST_LOC =", value, "dstLoc");
            return (Criteria) this;
        }

        public Criteria andDstLocNotEqualTo(String value) {

            addCriterion("DST_LOC <>", value, "dstLoc");
            return (Criteria) this;
        }

        public Criteria andDstLocGreaterThan(String value) {

            addCriterion("DST_LOC >", value, "dstLoc");
            return (Criteria) this;
        }

        public Criteria andDstLocGreaterThanOrEqualTo(String value) {

            addCriterion("DST_LOC >=", value, "dstLoc");
            return (Criteria) this;
        }

        public Criteria andDstLocLessThan(String value) {

            addCriterion("DST_LOC <", value, "dstLoc");
            return (Criteria) this;
        }

        public Criteria andDstLocLessThanOrEqualTo(String value) {

            addCriterion("DST_LOC <=", value, "dstLoc");
            return (Criteria) this;
        }

        public Criteria andDstLocLike(String value) {

            addCriterion("DST_LOC like", value, "dstLoc");
            return (Criteria) this;
        }

        public Criteria andDstLocNotLike(String value) {

            addCriterion("DST_LOC not like", value, "dstLoc");
            return (Criteria) this;
        }

        public Criteria andDstLocIn(List<String> values) {

            addCriterion("DST_LOC in", values, "dstLoc");
            return (Criteria) this;
        }

        public Criteria andDstLocNotIn(List<String> values) {

            addCriterion("DST_LOC not in", values, "dstLoc");
            return (Criteria) this;
        }

        public Criteria andDstLocBetween(String value1, String value2) {

            addCriterion("DST_LOC between", value1, value2, "dstLoc");
            return (Criteria) this;
        }

        public Criteria andDstLocNotBetween(String value1, String value2) {

            addCriterion("DST_LOC not between", value1, value2, "dstLoc");
            return (Criteria) this;
        }

        public Criteria andAveTimeIsNull() {

            addCriterion("AVE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andAveTimeIsNotNull() {

            addCriterion("AVE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andAveTimeEqualTo(Integer value) {

            addCriterion("AVE_TIME =", value, "aveTime");
            return (Criteria) this;
        }

        public Criteria andAveTimeNotEqualTo(Integer value) {

            addCriterion("AVE_TIME <>", value, "aveTime");
            return (Criteria) this;
        }

        public Criteria andAveTimeGreaterThan(Integer value) {

            addCriterion("AVE_TIME >", value, "aveTime");
            return (Criteria) this;
        }

        public Criteria andAveTimeGreaterThanOrEqualTo(Integer value) {

            addCriterion("AVE_TIME >=", value, "aveTime");
            return (Criteria) this;
        }

        public Criteria andAveTimeLessThan(Integer value) {

            addCriterion("AVE_TIME <", value, "aveTime");
            return (Criteria) this;
        }

        public Criteria andAveTimeLessThanOrEqualTo(Integer value) {

            addCriterion("AVE_TIME <=", value, "aveTime");
            return (Criteria) this;
        }

        public Criteria andAveTimeIn(List<Integer> values) {

            addCriterion("AVE_TIME in", values, "aveTime");
            return (Criteria) this;
        }

        public Criteria andAveTimeNotIn(List<Integer> values) {

            addCriterion("AVE_TIME not in", values, "aveTime");
            return (Criteria) this;
        }

        public Criteria andAveTimeBetween(Integer value1, Integer value2) {

            addCriterion("AVE_TIME between", value1, value2, "aveTime");
            return (Criteria) this;
        }

        public Criteria andAveTimeNotBetween(Integer value1, Integer value2) {

            addCriterion("AVE_TIME not between", value1, value2, "aveTime");
            return (Criteria) this;
        }

        public Criteria andLastModifiedTimeIsNull() {

            addCriterion("LAST_MODIFIED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedTimeIsNotNull() {

            addCriterion("LAST_MODIFIED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedTimeEqualTo(Timestamp value) {

            addCriterion("LAST_MODIFIED_TIME =", value, "lastModifiedTime");
            return (Criteria) this;
        }

        public Criteria andLastModifiedTimeNotEqualTo(Timestamp value) {

            addCriterion("LAST_MODIFIED_TIME <>", value, "lastModifiedTime");
            return (Criteria) this;
        }

        public Criteria andLastModifiedTimeGreaterThan(Timestamp value) {

            addCriterion("LAST_MODIFIED_TIME >", value, "lastModifiedTime");
            return (Criteria) this;
        }

        public Criteria andLastModifiedTimeGreaterThanOrEqualTo(Timestamp value) {

            addCriterion("LAST_MODIFIED_TIME >=", value, "lastModifiedTime");
            return (Criteria) this;
        }

        public Criteria andLastModifiedTimeLessThan(Timestamp value) {

            addCriterion("LAST_MODIFIED_TIME <", value, "lastModifiedTime");
            return (Criteria) this;
        }

        public Criteria andLastModifiedTimeLessThanOrEqualTo(Timestamp value) {

            addCriterion("LAST_MODIFIED_TIME <=", value, "lastModifiedTime");
            return (Criteria) this;
        }

        public Criteria andLastModifiedTimeIn(List<Timestamp> values) {

            addCriterion("LAST_MODIFIED_TIME in", values, "lastModifiedTime");
            return (Criteria) this;
        }

        public Criteria andLastModifiedTimeNotIn(List<Timestamp> values) {

            addCriterion("LAST_MODIFIED_TIME not in", values, "lastModifiedTime");
            return (Criteria) this;
        }

        public Criteria andLastModifiedTimeBetween(Timestamp value1, Timestamp value2) {

            addCriterion("LAST_MODIFIED_TIME between", value1, value2, "lastModifiedTime");
            return (Criteria) this;
        }

        public Criteria andLastModifiedTimeNotBetween(Timestamp value1, Timestamp value2) {

            addCriterion("LAST_MODIFIED_TIME not between", value1, value2, "lastModifiedTime");
            return (Criteria) this;
        }

        public Criteria andPassedCountIsNull() {

            addCriterion("PASSED_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andPassedCountIsNotNull() {

            addCriterion("PASSED_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andPassedCountEqualTo(Long value) {

            addCriterion("PASSED_COUNT =", value, "passedCount");
            return (Criteria) this;
        }

        public Criteria andPassedCountNotEqualTo(Long value) {

            addCriterion("PASSED_COUNT <>", value, "passedCount");
            return (Criteria) this;
        }

        public Criteria andPassedCountGreaterThan(Long value) {

            addCriterion("PASSED_COUNT >", value, "passedCount");
            return (Criteria) this;
        }

        public Criteria andPassedCountGreaterThanOrEqualTo(Long value) {

            addCriterion("PASSED_COUNT >=", value, "passedCount");
            return (Criteria) this;
        }

        public Criteria andPassedCountLessThan(Long value) {

            addCriterion("PASSED_COUNT <", value, "passedCount");
            return (Criteria) this;
        }

        public Criteria andPassedCountLessThanOrEqualTo(Long value) {

            addCriterion("PASSED_COUNT <=", value, "passedCount");
            return (Criteria) this;
        }

        public Criteria andPassedCountIn(List<Long> values) {

            addCriterion("PASSED_COUNT in", values, "passedCount");
            return (Criteria) this;
        }

        public Criteria andPassedCountNotIn(List<Long> values) {

            addCriterion("PASSED_COUNT not in", values, "passedCount");
            return (Criteria) this;
        }

        public Criteria andPassedCountBetween(Long value1, Long value2) {

            addCriterion("PASSED_COUNT between", value1, value2, "passedCount");
            return (Criteria) this;
        }

        public Criteria andPassedCountNotBetween(Long value1, Long value2) {

            addCriterion("PASSED_COUNT not between", value1, value2, "passedCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table ASTAR_HEURISTIC_COST
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {

            return condition;
        }

        public Object getValue() {

            return value;
        }

        public Object getSecondValue() {

            return secondValue;
        }

        public boolean isNoValue() {

            return noValue;
        }

        public boolean isSingleValue() {

            return singleValue;
        }

        public boolean isBetweenValue() {

            return betweenValue;
        }

        public boolean isListValue() {

            return listValue;
        }

        public String getTypeHandler() {

            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table ASTAR_HEURISTIC_COST
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 21 21:04:21 JST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}
