package net.muratec.mcs.model;

import java.util.ArrayList;
import java.util.List;
import java.sql.Timestamp;

public class CarrierExample {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table CARRIER
     * @mbg.generated
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table CARRIER
     * @mbg.generated
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table CARRIER
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    public CarrierExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {

        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    public String getOrderByClause() {

        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {

        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    public boolean isDistinct() {

        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {

        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    public void or(Criteria criteria) {

        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    public Criteria or() {

        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    public Criteria createCriteria() {

        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {

        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table CARRIER
     * @mbg.generated
     */
    public void clear() {

        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table CARRIER
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {

            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {

            return criteria;
        }

        public List<Criterion> getCriteria() {

            return criteria;
        }

        protected void addCriterion(String condition) {

            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {

            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {

            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEntityIdIsNull() {

            addCriterion("ENTITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andEntityIdIsNotNull() {

            addCriterion("ENTITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEntityIdEqualTo(String value) {

            addCriterion("ENTITY_ID =", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotEqualTo(String value) {

            addCriterion("ENTITY_ID <>", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdGreaterThan(String value) {

            addCriterion("ENTITY_ID >", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdGreaterThanOrEqualTo(String value) {

            addCriterion("ENTITY_ID >=", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLessThan(String value) {

            addCriterion("ENTITY_ID <", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLessThanOrEqualTo(String value) {

            addCriterion("ENTITY_ID <=", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLike(String value) {

            addCriterion("ENTITY_ID like", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotLike(String value) {

            addCriterion("ENTITY_ID not like", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdIn(List<String> values) {

            addCriterion("ENTITY_ID in", values, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotIn(List<String> values) {

            addCriterion("ENTITY_ID not in", values, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdBetween(String value1, String value2) {

            addCriterion("ENTITY_ID between", value1, value2, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotBetween(String value1, String value2) {

            addCriterion("ENTITY_ID not between", value1, value2, "entityId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdIsNull() {

            addCriterion("CARRIER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCarrierIdIsNotNull() {

            addCriterion("CARRIER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCarrierIdEqualTo(String value) {

            addCriterion("CARRIER_ID =", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdNotEqualTo(String value) {

            addCriterion("CARRIER_ID <>", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdGreaterThan(String value) {

            addCriterion("CARRIER_ID >", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdGreaterThanOrEqualTo(String value) {

            addCriterion("CARRIER_ID >=", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdLessThan(String value) {

            addCriterion("CARRIER_ID <", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdLessThanOrEqualTo(String value) {

            addCriterion("CARRIER_ID <=", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdLike(String value) {

            addCriterion("CARRIER_ID like", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdNotLike(String value) {

            addCriterion("CARRIER_ID not like", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdIn(List<String> values) {

            addCriterion("CARRIER_ID in", values, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdNotIn(List<String> values) {

            addCriterion("CARRIER_ID not in", values, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdBetween(String value1, String value2) {

            addCriterion("CARRIER_ID between", value1, value2, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdNotBetween(String value1, String value2) {

            addCriterion("CARRIER_ID not between", value1, value2, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierStateIsNull() {

            addCriterion("CARRIER_STATE is null");
            return (Criteria) this;
        }

        public Criteria andCarrierStateIsNotNull() {

            addCriterion("CARRIER_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andCarrierStateEqualTo(Short value) {

            addCriterion("CARRIER_STATE =", value, "carrierState");
            return (Criteria) this;
        }

        public Criteria andCarrierStateNotEqualTo(Short value) {

            addCriterion("CARRIER_STATE <>", value, "carrierState");
            return (Criteria) this;
        }

        public Criteria andCarrierStateGreaterThan(Short value) {

            addCriterion("CARRIER_STATE >", value, "carrierState");
            return (Criteria) this;
        }

        public Criteria andCarrierStateGreaterThanOrEqualTo(Short value) {

            addCriterion("CARRIER_STATE >=", value, "carrierState");
            return (Criteria) this;
        }

        public Criteria andCarrierStateLessThan(Short value) {

            addCriterion("CARRIER_STATE <", value, "carrierState");
            return (Criteria) this;
        }

        public Criteria andCarrierStateLessThanOrEqualTo(Short value) {

            addCriterion("CARRIER_STATE <=", value, "carrierState");
            return (Criteria) this;
        }

        public Criteria andCarrierStateIn(List<Short> values) {

            addCriterion("CARRIER_STATE in", values, "carrierState");
            return (Criteria) this;
        }

        public Criteria andCarrierStateNotIn(List<Short> values) {

            addCriterion("CARRIER_STATE not in", values, "carrierState");
            return (Criteria) this;
        }

        public Criteria andCarrierStateBetween(Short value1, Short value2) {

            addCriterion("CARRIER_STATE between", value1, value2, "carrierState");
            return (Criteria) this;
        }

        public Criteria andCarrierStateNotBetween(Short value1, Short value2) {

            addCriterion("CARRIER_STATE not between", value1, value2, "carrierState");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierStateIsNull() {

            addCriterion("PREV_CARRIER_STATE is null");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierStateIsNotNull() {

            addCriterion("PREV_CARRIER_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierStateEqualTo(Short value) {

            addCriterion("PREV_CARRIER_STATE =", value, "prevCarrierState");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierStateNotEqualTo(Short value) {

            addCriterion("PREV_CARRIER_STATE <>", value, "prevCarrierState");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierStateGreaterThan(Short value) {

            addCriterion("PREV_CARRIER_STATE >", value, "prevCarrierState");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierStateGreaterThanOrEqualTo(Short value) {

            addCriterion("PREV_CARRIER_STATE >=", value, "prevCarrierState");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierStateLessThan(Short value) {

            addCriterion("PREV_CARRIER_STATE <", value, "prevCarrierState");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierStateLessThanOrEqualTo(Short value) {

            addCriterion("PREV_CARRIER_STATE <=", value, "prevCarrierState");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierStateIn(List<Short> values) {

            addCriterion("PREV_CARRIER_STATE in", values, "prevCarrierState");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierStateNotIn(List<Short> values) {

            addCriterion("PREV_CARRIER_STATE not in", values, "prevCarrierState");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierStateBetween(Short value1, Short value2) {

            addCriterion("PREV_CARRIER_STATE between", value1, value2, "prevCarrierState");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierStateNotBetween(Short value1, Short value2) {

            addCriterion("PREV_CARRIER_STATE not between", value1, value2, "prevCarrierState");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdIsNull() {

            addCriterion("CARRIER_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdIsNotNull() {

            addCriterion("CARRIER_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdEqualTo(String value) {

            addCriterion("CARRIER_TYPE_ID =", value, "carrierTypeId");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdNotEqualTo(String value) {

            addCriterion("CARRIER_TYPE_ID <>", value, "carrierTypeId");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdGreaterThan(String value) {

            addCriterion("CARRIER_TYPE_ID >", value, "carrierTypeId");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdGreaterThanOrEqualTo(String value) {

            addCriterion("CARRIER_TYPE_ID >=", value, "carrierTypeId");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdLessThan(String value) {

            addCriterion("CARRIER_TYPE_ID <", value, "carrierTypeId");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdLessThanOrEqualTo(String value) {

            addCriterion("CARRIER_TYPE_ID <=", value, "carrierTypeId");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdLike(String value) {

            addCriterion("CARRIER_TYPE_ID like", value, "carrierTypeId");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdNotLike(String value) {

            addCriterion("CARRIER_TYPE_ID not like", value, "carrierTypeId");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdIn(List<String> values) {

            addCriterion("CARRIER_TYPE_ID in", values, "carrierTypeId");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdNotIn(List<String> values) {

            addCriterion("CARRIER_TYPE_ID not in", values, "carrierTypeId");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdBetween(String value1, String value2) {

            addCriterion("CARRIER_TYPE_ID between", value1, value2, "carrierTypeId");
            return (Criteria) this;
        }

        public Criteria andCarrierTypeIdNotBetween(String value1, String value2) {

            addCriterion("CARRIER_TYPE_ID not between", value1, value2, "carrierTypeId");
            return (Criteria) this;
        }

        public Criteria andCarrierShapeIdIsNull() {

            addCriterion("CARRIER_SHAPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCarrierShapeIdIsNotNull() {

            addCriterion("CARRIER_SHAPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCarrierShapeIdEqualTo(Short value) {

            addCriterion("CARRIER_SHAPE_ID =", value, "carrierShapeId");
            return (Criteria) this;
        }

        public Criteria andCarrierShapeIdNotEqualTo(Short value) {

            addCriterion("CARRIER_SHAPE_ID <>", value, "carrierShapeId");
            return (Criteria) this;
        }

        public Criteria andCarrierShapeIdGreaterThan(Short value) {

            addCriterion("CARRIER_SHAPE_ID >", value, "carrierShapeId");
            return (Criteria) this;
        }

        public Criteria andCarrierShapeIdGreaterThanOrEqualTo(Short value) {

            addCriterion("CARRIER_SHAPE_ID >=", value, "carrierShapeId");
            return (Criteria) this;
        }

        public Criteria andCarrierShapeIdLessThan(Short value) {

            addCriterion("CARRIER_SHAPE_ID <", value, "carrierShapeId");
            return (Criteria) this;
        }

        public Criteria andCarrierShapeIdLessThanOrEqualTo(Short value) {

            addCriterion("CARRIER_SHAPE_ID <=", value, "carrierShapeId");
            return (Criteria) this;
        }

        public Criteria andCarrierShapeIdIn(List<Short> values) {

            addCriterion("CARRIER_SHAPE_ID in", values, "carrierShapeId");
            return (Criteria) this;
        }

        public Criteria andCarrierShapeIdNotIn(List<Short> values) {

            addCriterion("CARRIER_SHAPE_ID not in", values, "carrierShapeId");
            return (Criteria) this;
        }

        public Criteria andCarrierShapeIdBetween(Short value1, Short value2) {

            addCriterion("CARRIER_SHAPE_ID between", value1, value2, "carrierShapeId");
            return (Criteria) this;
        }

        public Criteria andCarrierShapeIdNotBetween(Short value1, Short value2) {

            addCriterion("CARRIER_SHAPE_ID not between", value1, value2, "carrierShapeId");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdIsNull() {

            addCriterion("CURRENT_AMHS_ID is null");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdIsNotNull() {

            addCriterion("CURRENT_AMHS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdEqualTo(String value) {

            addCriterion("CURRENT_AMHS_ID =", value, "currentAmhsId");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdNotEqualTo(String value) {

            addCriterion("CURRENT_AMHS_ID <>", value, "currentAmhsId");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdGreaterThan(String value) {

            addCriterion("CURRENT_AMHS_ID >", value, "currentAmhsId");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdGreaterThanOrEqualTo(String value) {

            addCriterion("CURRENT_AMHS_ID >=", value, "currentAmhsId");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdLessThan(String value) {

            addCriterion("CURRENT_AMHS_ID <", value, "currentAmhsId");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdLessThanOrEqualTo(String value) {

            addCriterion("CURRENT_AMHS_ID <=", value, "currentAmhsId");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdLike(String value) {

            addCriterion("CURRENT_AMHS_ID like", value, "currentAmhsId");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdNotLike(String value) {

            addCriterion("CURRENT_AMHS_ID not like", value, "currentAmhsId");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdIn(List<String> values) {

            addCriterion("CURRENT_AMHS_ID in", values, "currentAmhsId");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdNotIn(List<String> values) {

            addCriterion("CURRENT_AMHS_ID not in", values, "currentAmhsId");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdBetween(String value1, String value2) {

            addCriterion("CURRENT_AMHS_ID between", value1, value2, "currentAmhsId");
            return (Criteria) this;
        }

        public Criteria andCurrentAmhsIdNotBetween(String value1, String value2) {

            addCriterion("CURRENT_AMHS_ID not between", value1, value2, "currentAmhsId");
            return (Criteria) this;
        }

        public Criteria andCurrentLocTypeIsNull() {

            addCriterion("CURRENT_LOC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCurrentLocTypeIsNotNull() {

            addCriterion("CURRENT_LOC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentLocTypeEqualTo(Short value) {

            addCriterion("CURRENT_LOC_TYPE =", value, "currentLocType");
            return (Criteria) this;
        }

        public Criteria andCurrentLocTypeNotEqualTo(Short value) {

            addCriterion("CURRENT_LOC_TYPE <>", value, "currentLocType");
            return (Criteria) this;
        }

        public Criteria andCurrentLocTypeGreaterThan(Short value) {

            addCriterion("CURRENT_LOC_TYPE >", value, "currentLocType");
            return (Criteria) this;
        }

        public Criteria andCurrentLocTypeGreaterThanOrEqualTo(Short value) {

            addCriterion("CURRENT_LOC_TYPE >=", value, "currentLocType");
            return (Criteria) this;
        }

        public Criteria andCurrentLocTypeLessThan(Short value) {

            addCriterion("CURRENT_LOC_TYPE <", value, "currentLocType");
            return (Criteria) this;
        }

        public Criteria andCurrentLocTypeLessThanOrEqualTo(Short value) {

            addCriterion("CURRENT_LOC_TYPE <=", value, "currentLocType");
            return (Criteria) this;
        }

        public Criteria andCurrentLocTypeIn(List<Short> values) {

            addCriterion("CURRENT_LOC_TYPE in", values, "currentLocType");
            return (Criteria) this;
        }

        public Criteria andCurrentLocTypeNotIn(List<Short> values) {

            addCriterion("CURRENT_LOC_TYPE not in", values, "currentLocType");
            return (Criteria) this;
        }

        public Criteria andCurrentLocTypeBetween(Short value1, Short value2) {

            addCriterion("CURRENT_LOC_TYPE between", value1, value2, "currentLocType");
            return (Criteria) this;
        }

        public Criteria andCurrentLocTypeNotBetween(Short value1, Short value2) {

            addCriterion("CURRENT_LOC_TYPE not between", value1, value2, "currentLocType");
            return (Criteria) this;
        }

        public Criteria andCurrentLocIsNull() {

            addCriterion("CURRENT_LOC is null");
            return (Criteria) this;
        }

        public Criteria andCurrentLocIsNotNull() {

            addCriterion("CURRENT_LOC is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentLocEqualTo(String value) {

            addCriterion("CURRENT_LOC =", value, "currentLoc");
            return (Criteria) this;
        }

        public Criteria andCurrentLocNotEqualTo(String value) {

            addCriterion("CURRENT_LOC <>", value, "currentLoc");
            return (Criteria) this;
        }

        public Criteria andCurrentLocGreaterThan(String value) {

            addCriterion("CURRENT_LOC >", value, "currentLoc");
            return (Criteria) this;
        }

        public Criteria andCurrentLocGreaterThanOrEqualTo(String value) {

            addCriterion("CURRENT_LOC >=", value, "currentLoc");
            return (Criteria) this;
        }

        public Criteria andCurrentLocLessThan(String value) {

            addCriterion("CURRENT_LOC <", value, "currentLoc");
            return (Criteria) this;
        }

        public Criteria andCurrentLocLessThanOrEqualTo(String value) {

            addCriterion("CURRENT_LOC <=", value, "currentLoc");
            return (Criteria) this;
        }

        public Criteria andCurrentLocLike(String value) {

            addCriterion("CURRENT_LOC like", value, "currentLoc");
            return (Criteria) this;
        }

        public Criteria andCurrentLocNotLike(String value) {

            addCriterion("CURRENT_LOC not like", value, "currentLoc");
            return (Criteria) this;
        }

        public Criteria andCurrentLocIn(List<String> values) {

            addCriterion("CURRENT_LOC in", values, "currentLoc");
            return (Criteria) this;
        }

        public Criteria andCurrentLocNotIn(List<String> values) {

            addCriterion("CURRENT_LOC not in", values, "currentLoc");
            return (Criteria) this;
        }

        public Criteria andCurrentLocBetween(String value1, String value2) {

            addCriterion("CURRENT_LOC between", value1, value2, "currentLoc");
            return (Criteria) this;
        }

        public Criteria andCurrentLocNotBetween(String value1, String value2) {

            addCriterion("CURRENT_LOC not between", value1, value2, "currentLoc");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdIsNull() {

            addCriterion("HOST_ZONE_ID is null");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdIsNotNull() {

            addCriterion("HOST_ZONE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdEqualTo(String value) {

            addCriterion("HOST_ZONE_ID =", value, "hostZoneId");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdNotEqualTo(String value) {

            addCriterion("HOST_ZONE_ID <>", value, "hostZoneId");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdGreaterThan(String value) {

            addCriterion("HOST_ZONE_ID >", value, "hostZoneId");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdGreaterThanOrEqualTo(String value) {

            addCriterion("HOST_ZONE_ID >=", value, "hostZoneId");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdLessThan(String value) {

            addCriterion("HOST_ZONE_ID <", value, "hostZoneId");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdLessThanOrEqualTo(String value) {

            addCriterion("HOST_ZONE_ID <=", value, "hostZoneId");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdLike(String value) {

            addCriterion("HOST_ZONE_ID like", value, "hostZoneId");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdNotLike(String value) {

            addCriterion("HOST_ZONE_ID not like", value, "hostZoneId");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdIn(List<String> values) {

            addCriterion("HOST_ZONE_ID in", values, "hostZoneId");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdNotIn(List<String> values) {

            addCriterion("HOST_ZONE_ID not in", values, "hostZoneId");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdBetween(String value1, String value2) {

            addCriterion("HOST_ZONE_ID between", value1, value2, "hostZoneId");
            return (Criteria) this;
        }

        public Criteria andHostZoneIdNotBetween(String value1, String value2) {

            addCriterion("HOST_ZONE_ID not between", value1, value2, "hostZoneId");
            return (Criteria) this;
        }

        public Criteria andShelfNoIsNull() {

            addCriterion("SHELF_NO is null");
            return (Criteria) this;
        }

        public Criteria andShelfNoIsNotNull() {

            addCriterion("SHELF_NO is not null");
            return (Criteria) this;
        }

        public Criteria andShelfNoEqualTo(String value) {

            addCriterion("SHELF_NO =", value, "shelfNo");
            return (Criteria) this;
        }

        public Criteria andShelfNoNotEqualTo(String value) {

            addCriterion("SHELF_NO <>", value, "shelfNo");
            return (Criteria) this;
        }

        public Criteria andShelfNoGreaterThan(String value) {

            addCriterion("SHELF_NO >", value, "shelfNo");
            return (Criteria) this;
        }

        public Criteria andShelfNoGreaterThanOrEqualTo(String value) {

            addCriterion("SHELF_NO >=", value, "shelfNo");
            return (Criteria) this;
        }

        public Criteria andShelfNoLessThan(String value) {

            addCriterion("SHELF_NO <", value, "shelfNo");
            return (Criteria) this;
        }

        public Criteria andShelfNoLessThanOrEqualTo(String value) {

            addCriterion("SHELF_NO <=", value, "shelfNo");
            return (Criteria) this;
        }

        public Criteria andShelfNoLike(String value) {

            addCriterion("SHELF_NO like", value, "shelfNo");
            return (Criteria) this;
        }

        public Criteria andShelfNoNotLike(String value) {

            addCriterion("SHELF_NO not like", value, "shelfNo");
            return (Criteria) this;
        }

        public Criteria andShelfNoIn(List<String> values) {

            addCriterion("SHELF_NO in", values, "shelfNo");
            return (Criteria) this;
        }

        public Criteria andShelfNoNotIn(List<String> values) {

            addCriterion("SHELF_NO not in", values, "shelfNo");
            return (Criteria) this;
        }

        public Criteria andShelfNoBetween(String value1, String value2) {

            addCriterion("SHELF_NO between", value1, value2, "shelfNo");
            return (Criteria) this;
        }

        public Criteria andShelfNoNotBetween(String value1, String value2) {

            addCriterion("SHELF_NO not between", value1, value2, "shelfNo");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdIsNull() {

            addCriterion("PREV_AMHS_ID is null");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdIsNotNull() {

            addCriterion("PREV_AMHS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdEqualTo(String value) {

            addCriterion("PREV_AMHS_ID =", value, "prevAmhsId");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdNotEqualTo(String value) {

            addCriterion("PREV_AMHS_ID <>", value, "prevAmhsId");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdGreaterThan(String value) {

            addCriterion("PREV_AMHS_ID >", value, "prevAmhsId");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdGreaterThanOrEqualTo(String value) {

            addCriterion("PREV_AMHS_ID >=", value, "prevAmhsId");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdLessThan(String value) {

            addCriterion("PREV_AMHS_ID <", value, "prevAmhsId");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdLessThanOrEqualTo(String value) {

            addCriterion("PREV_AMHS_ID <=", value, "prevAmhsId");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdLike(String value) {

            addCriterion("PREV_AMHS_ID like", value, "prevAmhsId");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdNotLike(String value) {

            addCriterion("PREV_AMHS_ID not like", value, "prevAmhsId");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdIn(List<String> values) {

            addCriterion("PREV_AMHS_ID in", values, "prevAmhsId");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdNotIn(List<String> values) {

            addCriterion("PREV_AMHS_ID not in", values, "prevAmhsId");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdBetween(String value1, String value2) {

            addCriterion("PREV_AMHS_ID between", value1, value2, "prevAmhsId");
            return (Criteria) this;
        }

        public Criteria andPrevAmhsIdNotBetween(String value1, String value2) {

            addCriterion("PREV_AMHS_ID not between", value1, value2, "prevAmhsId");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocTypeIsNull() {

            addCriterion("PREV_CARRIER_LOC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocTypeIsNotNull() {

            addCriterion("PREV_CARRIER_LOC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocTypeEqualTo(Short value) {

            addCriterion("PREV_CARRIER_LOC_TYPE =", value, "prevCarrierLocType");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocTypeNotEqualTo(Short value) {

            addCriterion("PREV_CARRIER_LOC_TYPE <>", value, "prevCarrierLocType");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocTypeGreaterThan(Short value) {

            addCriterion("PREV_CARRIER_LOC_TYPE >", value, "prevCarrierLocType");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocTypeGreaterThanOrEqualTo(Short value) {

            addCriterion("PREV_CARRIER_LOC_TYPE >=", value, "prevCarrierLocType");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocTypeLessThan(Short value) {

            addCriterion("PREV_CARRIER_LOC_TYPE <", value, "prevCarrierLocType");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocTypeLessThanOrEqualTo(Short value) {

            addCriterion("PREV_CARRIER_LOC_TYPE <=", value, "prevCarrierLocType");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocTypeIn(List<Short> values) {

            addCriterion("PREV_CARRIER_LOC_TYPE in", values, "prevCarrierLocType");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocTypeNotIn(List<Short> values) {

            addCriterion("PREV_CARRIER_LOC_TYPE not in", values, "prevCarrierLocType");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocTypeBetween(Short value1, Short value2) {

            addCriterion("PREV_CARRIER_LOC_TYPE between", value1, value2, "prevCarrierLocType");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocTypeNotBetween(Short value1, Short value2) {

            addCriterion("PREV_CARRIER_LOC_TYPE not between", value1, value2, "prevCarrierLocType");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocIsNull() {

            addCriterion("PREV_CARRIER_LOC is null");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocIsNotNull() {

            addCriterion("PREV_CARRIER_LOC is not null");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocEqualTo(String value) {

            addCriterion("PREV_CARRIER_LOC =", value, "prevCarrierLoc");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocNotEqualTo(String value) {

            addCriterion("PREV_CARRIER_LOC <>", value, "prevCarrierLoc");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocGreaterThan(String value) {

            addCriterion("PREV_CARRIER_LOC >", value, "prevCarrierLoc");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocGreaterThanOrEqualTo(String value) {

            addCriterion("PREV_CARRIER_LOC >=", value, "prevCarrierLoc");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocLessThan(String value) {

            addCriterion("PREV_CARRIER_LOC <", value, "prevCarrierLoc");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocLessThanOrEqualTo(String value) {

            addCriterion("PREV_CARRIER_LOC <=", value, "prevCarrierLoc");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocLike(String value) {

            addCriterion("PREV_CARRIER_LOC like", value, "prevCarrierLoc");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocNotLike(String value) {

            addCriterion("PREV_CARRIER_LOC not like", value, "prevCarrierLoc");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocIn(List<String> values) {

            addCriterion("PREV_CARRIER_LOC in", values, "prevCarrierLoc");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocNotIn(List<String> values) {

            addCriterion("PREV_CARRIER_LOC not in", values, "prevCarrierLoc");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocBetween(String value1, String value2) {

            addCriterion("PREV_CARRIER_LOC between", value1, value2, "prevCarrierLoc");
            return (Criteria) this;
        }

        public Criteria andPrevCarrierLocNotBetween(String value1, String value2) {

            addCriterion("PREV_CARRIER_LOC not between", value1, value2, "prevCarrierLoc");
            return (Criteria) this;
        }

        public Criteria andStoredTimeIsNull() {

            addCriterion("STORED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andStoredTimeIsNotNull() {

            addCriterion("STORED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andStoredTimeEqualTo(Timestamp value) {

            addCriterion("STORED_TIME =", value, "storedTime");
            return (Criteria) this;
        }

        public Criteria andStoredTimeNotEqualTo(Timestamp value) {

            addCriterion("STORED_TIME <>", value, "storedTime");
            return (Criteria) this;
        }

        public Criteria andStoredTimeGreaterThan(Timestamp value) {

            addCriterion("STORED_TIME >", value, "storedTime");
            return (Criteria) this;
        }

        public Criteria andStoredTimeGreaterThanOrEqualTo(Timestamp value) {

            addCriterion("STORED_TIME >=", value, "storedTime");
            return (Criteria) this;
        }

        public Criteria andStoredTimeLessThan(Timestamp value) {

            addCriterion("STORED_TIME <", value, "storedTime");
            return (Criteria) this;
        }

        public Criteria andStoredTimeLessThanOrEqualTo(Timestamp value) {

            addCriterion("STORED_TIME <=", value, "storedTime");
            return (Criteria) this;
        }

        public Criteria andStoredTimeIn(List<Timestamp> values) {

            addCriterion("STORED_TIME in", values, "storedTime");
            return (Criteria) this;
        }

        public Criteria andStoredTimeNotIn(List<Timestamp> values) {

            addCriterion("STORED_TIME not in", values, "storedTime");
            return (Criteria) this;
        }

        public Criteria andStoredTimeBetween(Timestamp value1, Timestamp value2) {

            addCriterion("STORED_TIME between", value1, value2, "storedTime");
            return (Criteria) this;
        }

        public Criteria andStoredTimeNotBetween(Timestamp value1, Timestamp value2) {

            addCriterion("STORED_TIME not between", value1, value2, "storedTime");
            return (Criteria) this;
        }

        public Criteria andCarrierEmptyIsNull() {

            addCriterion("CARRIER_EMPTY is null");
            return (Criteria) this;
        }

        public Criteria andCarrierEmptyIsNotNull() {

            addCriterion("CARRIER_EMPTY is not null");
            return (Criteria) this;
        }

        public Criteria andCarrierEmptyEqualTo(Short value) {

            addCriterion("CARRIER_EMPTY =", value, "carrierEmpty");
            return (Criteria) this;
        }

        public Criteria andCarrierEmptyNotEqualTo(Short value) {

            addCriterion("CARRIER_EMPTY <>", value, "carrierEmpty");
            return (Criteria) this;
        }

        public Criteria andCarrierEmptyGreaterThan(Short value) {

            addCriterion("CARRIER_EMPTY >", value, "carrierEmpty");
            return (Criteria) this;
        }

        public Criteria andCarrierEmptyGreaterThanOrEqualTo(Short value) {

            addCriterion("CARRIER_EMPTY >=", value, "carrierEmpty");
            return (Criteria) this;
        }

        public Criteria andCarrierEmptyLessThan(Short value) {

            addCriterion("CARRIER_EMPTY <", value, "carrierEmpty");
            return (Criteria) this;
        }

        public Criteria andCarrierEmptyLessThanOrEqualTo(Short value) {

            addCriterion("CARRIER_EMPTY <=", value, "carrierEmpty");
            return (Criteria) this;
        }

        public Criteria andCarrierEmptyIn(List<Short> values) {

            addCriterion("CARRIER_EMPTY in", values, "carrierEmpty");
            return (Criteria) this;
        }

        public Criteria andCarrierEmptyNotIn(List<Short> values) {

            addCriterion("CARRIER_EMPTY not in", values, "carrierEmpty");
            return (Criteria) this;
        }

        public Criteria andCarrierEmptyBetween(Short value1, Short value2) {

            addCriterion("CARRIER_EMPTY between", value1, value2, "carrierEmpty");
            return (Criteria) this;
        }

        public Criteria andCarrierEmptyNotBetween(Short value1, Short value2) {

            addCriterion("CARRIER_EMPTY not between", value1, value2, "carrierEmpty");
            return (Criteria) this;
        }

        public Criteria andWaitInTimeIsNull() {

            addCriterion("WAIT_IN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andWaitInTimeIsNotNull() {

            addCriterion("WAIT_IN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andWaitInTimeEqualTo(Timestamp value) {

            addCriterion("WAIT_IN_TIME =", value, "waitInTime");
            return (Criteria) this;
        }

        public Criteria andWaitInTimeNotEqualTo(Timestamp value) {

            addCriterion("WAIT_IN_TIME <>", value, "waitInTime");
            return (Criteria) this;
        }

        public Criteria andWaitInTimeGreaterThan(Timestamp value) {

            addCriterion("WAIT_IN_TIME >", value, "waitInTime");
            return (Criteria) this;
        }

        public Criteria andWaitInTimeGreaterThanOrEqualTo(Timestamp value) {

            addCriterion("WAIT_IN_TIME >=", value, "waitInTime");
            return (Criteria) this;
        }

        public Criteria andWaitInTimeLessThan(Timestamp value) {

            addCriterion("WAIT_IN_TIME <", value, "waitInTime");
            return (Criteria) this;
        }

        public Criteria andWaitInTimeLessThanOrEqualTo(Timestamp value) {

            addCriterion("WAIT_IN_TIME <=", value, "waitInTime");
            return (Criteria) this;
        }

        public Criteria andWaitInTimeIn(List<Timestamp> values) {

            addCriterion("WAIT_IN_TIME in", values, "waitInTime");
            return (Criteria) this;
        }

        public Criteria andWaitInTimeNotIn(List<Timestamp> values) {

            addCriterion("WAIT_IN_TIME not in", values, "waitInTime");
            return (Criteria) this;
        }

        public Criteria andWaitInTimeBetween(Timestamp value1, Timestamp value2) {

            addCriterion("WAIT_IN_TIME between", value1, value2, "waitInTime");
            return (Criteria) this;
        }

        public Criteria andWaitInTimeNotBetween(Timestamp value1, Timestamp value2) {

            addCriterion("WAIT_IN_TIME not between", value1, value2, "waitInTime");
            return (Criteria) this;
        }

        public Criteria andWaitOutTimeIsNull() {

            addCriterion("WAIT_OUT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andWaitOutTimeIsNotNull() {

            addCriterion("WAIT_OUT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andWaitOutTimeEqualTo(Timestamp value) {

            addCriterion("WAIT_OUT_TIME =", value, "waitOutTime");
            return (Criteria) this;
        }

        public Criteria andWaitOutTimeNotEqualTo(Timestamp value) {

            addCriterion("WAIT_OUT_TIME <>", value, "waitOutTime");
            return (Criteria) this;
        }

        public Criteria andWaitOutTimeGreaterThan(Timestamp value) {

            addCriterion("WAIT_OUT_TIME >", value, "waitOutTime");
            return (Criteria) this;
        }

        public Criteria andWaitOutTimeGreaterThanOrEqualTo(Timestamp value) {

            addCriterion("WAIT_OUT_TIME >=", value, "waitOutTime");
            return (Criteria) this;
        }

        public Criteria andWaitOutTimeLessThan(Timestamp value) {

            addCriterion("WAIT_OUT_TIME <", value, "waitOutTime");
            return (Criteria) this;
        }

        public Criteria andWaitOutTimeLessThanOrEqualTo(Timestamp value) {

            addCriterion("WAIT_OUT_TIME <=", value, "waitOutTime");
            return (Criteria) this;
        }

        public Criteria andWaitOutTimeIn(List<Timestamp> values) {

            addCriterion("WAIT_OUT_TIME in", values, "waitOutTime");
            return (Criteria) this;
        }

        public Criteria andWaitOutTimeNotIn(List<Timestamp> values) {

            addCriterion("WAIT_OUT_TIME not in", values, "waitOutTime");
            return (Criteria) this;
        }

        public Criteria andWaitOutTimeBetween(Timestamp value1, Timestamp value2) {

            addCriterion("WAIT_OUT_TIME between", value1, value2, "waitOutTime");
            return (Criteria) this;
        }

        public Criteria andWaitOutTimeNotBetween(Timestamp value1, Timestamp value2) {

            addCriterion("WAIT_OUT_TIME not between", value1, value2, "waitOutTime");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdIsNull() {

            addCriterion("INSYSTEM_CARRIER_ID is null");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdIsNotNull() {

            addCriterion("INSYSTEM_CARRIER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdEqualTo(String value) {

            addCriterion("INSYSTEM_CARRIER_ID =", value, "insystemCarrierId");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdNotEqualTo(String value) {

            addCriterion("INSYSTEM_CARRIER_ID <>", value, "insystemCarrierId");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdGreaterThan(String value) {

            addCriterion("INSYSTEM_CARRIER_ID >", value, "insystemCarrierId");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdGreaterThanOrEqualTo(String value) {

            addCriterion("INSYSTEM_CARRIER_ID >=", value, "insystemCarrierId");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdLessThan(String value) {

            addCriterion("INSYSTEM_CARRIER_ID <", value, "insystemCarrierId");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdLessThanOrEqualTo(String value) {

            addCriterion("INSYSTEM_CARRIER_ID <=", value, "insystemCarrierId");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdLike(String value) {

            addCriterion("INSYSTEM_CARRIER_ID like", value, "insystemCarrierId");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdNotLike(String value) {

            addCriterion("INSYSTEM_CARRIER_ID not like", value, "insystemCarrierId");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdIn(List<String> values) {

            addCriterion("INSYSTEM_CARRIER_ID in", values, "insystemCarrierId");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdNotIn(List<String> values) {

            addCriterion("INSYSTEM_CARRIER_ID not in", values, "insystemCarrierId");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdBetween(String value1, String value2) {

            addCriterion("INSYSTEM_CARRIER_ID between", value1, value2, "insystemCarrierId");
            return (Criteria) this;
        }

        public Criteria andInsystemCarrierIdNotBetween(String value1, String value2) {

            addCriterion("INSYSTEM_CARRIER_ID not between", value1, value2, "insystemCarrierId");
            return (Criteria) this;
        }

        public Criteria andInsystemTimeIsNull() {

            addCriterion("INSYSTEM_TIME is null");
            return (Criteria) this;
        }

        public Criteria andInsystemTimeIsNotNull() {

            addCriterion("INSYSTEM_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andInsystemTimeEqualTo(Timestamp value) {

            addCriterion("INSYSTEM_TIME =", value, "insystemTime");
            return (Criteria) this;
        }

        public Criteria andInsystemTimeNotEqualTo(Timestamp value) {

            addCriterion("INSYSTEM_TIME <>", value, "insystemTime");
            return (Criteria) this;
        }

        public Criteria andInsystemTimeGreaterThan(Timestamp value) {

            addCriterion("INSYSTEM_TIME >", value, "insystemTime");
            return (Criteria) this;
        }

        public Criteria andInsystemTimeGreaterThanOrEqualTo(Timestamp value) {

            addCriterion("INSYSTEM_TIME >=", value, "insystemTime");
            return (Criteria) this;
        }

        public Criteria andInsystemTimeLessThan(Timestamp value) {

            addCriterion("INSYSTEM_TIME <", value, "insystemTime");
            return (Criteria) this;
        }

        public Criteria andInsystemTimeLessThanOrEqualTo(Timestamp value) {

            addCriterion("INSYSTEM_TIME <=", value, "insystemTime");
            return (Criteria) this;
        }

        public Criteria andInsystemTimeIn(List<Timestamp> values) {

            addCriterion("INSYSTEM_TIME in", values, "insystemTime");
            return (Criteria) this;
        }

        public Criteria andInsystemTimeNotIn(List<Timestamp> values) {

            addCriterion("INSYSTEM_TIME not in", values, "insystemTime");
            return (Criteria) this;
        }

        public Criteria andInsystemTimeBetween(Timestamp value1, Timestamp value2) {

            addCriterion("INSYSTEM_TIME between", value1, value2, "insystemTime");
            return (Criteria) this;
        }

        public Criteria andInsystemTimeNotBetween(Timestamp value1, Timestamp value2) {

            addCriterion("INSYSTEM_TIME not between", value1, value2, "insystemTime");
            return (Criteria) this;
        }

        public Criteria andCarrierAlarmIsNull() {

            addCriterion("CARRIER_ALARM is null");
            return (Criteria) this;
        }

        public Criteria andCarrierAlarmIsNotNull() {

            addCriterion("CARRIER_ALARM is not null");
            return (Criteria) this;
        }

        public Criteria andCarrierAlarmEqualTo(Short value) {

            addCriterion("CARRIER_ALARM =", value, "carrierAlarm");
            return (Criteria) this;
        }

        public Criteria andCarrierAlarmNotEqualTo(Short value) {

            addCriterion("CARRIER_ALARM <>", value, "carrierAlarm");
            return (Criteria) this;
        }

        public Criteria andCarrierAlarmGreaterThan(Short value) {

            addCriterion("CARRIER_ALARM >", value, "carrierAlarm");
            return (Criteria) this;
        }

        public Criteria andCarrierAlarmGreaterThanOrEqualTo(Short value) {

            addCriterion("CARRIER_ALARM >=", value, "carrierAlarm");
            return (Criteria) this;
        }

        public Criteria andCarrierAlarmLessThan(Short value) {

            addCriterion("CARRIER_ALARM <", value, "carrierAlarm");
            return (Criteria) this;
        }

        public Criteria andCarrierAlarmLessThanOrEqualTo(Short value) {

            addCriterion("CARRIER_ALARM <=", value, "carrierAlarm");
            return (Criteria) this;
        }

        public Criteria andCarrierAlarmIn(List<Short> values) {

            addCriterion("CARRIER_ALARM in", values, "carrierAlarm");
            return (Criteria) this;
        }

        public Criteria andCarrierAlarmNotIn(List<Short> values) {

            addCriterion("CARRIER_ALARM not in", values, "carrierAlarm");
            return (Criteria) this;
        }

        public Criteria andCarrierAlarmBetween(Short value1, Short value2) {

            addCriterion("CARRIER_ALARM between", value1, value2, "carrierAlarm");
            return (Criteria) this;
        }

        public Criteria andCarrierAlarmNotBetween(Short value1, Short value2) {

            addCriterion("CARRIER_ALARM not between", value1, value2, "carrierAlarm");
            return (Criteria) this;
        }

        public Criteria andPassingModeIsNull() {

            addCriterion("PASSING_MODE is null");
            return (Criteria) this;
        }

        public Criteria andPassingModeIsNotNull() {

            addCriterion("PASSING_MODE is not null");
            return (Criteria) this;
        }

        public Criteria andPassingModeEqualTo(Short value) {

            addCriterion("PASSING_MODE =", value, "passingMode");
            return (Criteria) this;
        }

        public Criteria andPassingModeNotEqualTo(Short value) {

            addCriterion("PASSING_MODE <>", value, "passingMode");
            return (Criteria) this;
        }

        public Criteria andPassingModeGreaterThan(Short value) {

            addCriterion("PASSING_MODE >", value, "passingMode");
            return (Criteria) this;
        }

        public Criteria andPassingModeGreaterThanOrEqualTo(Short value) {

            addCriterion("PASSING_MODE >=", value, "passingMode");
            return (Criteria) this;
        }

        public Criteria andPassingModeLessThan(Short value) {

            addCriterion("PASSING_MODE <", value, "passingMode");
            return (Criteria) this;
        }

        public Criteria andPassingModeLessThanOrEqualTo(Short value) {

            addCriterion("PASSING_MODE <=", value, "passingMode");
            return (Criteria) this;
        }

        public Criteria andPassingModeIn(List<Short> values) {

            addCriterion("PASSING_MODE in", values, "passingMode");
            return (Criteria) this;
        }

        public Criteria andPassingModeNotIn(List<Short> values) {

            addCriterion("PASSING_MODE not in", values, "passingMode");
            return (Criteria) this;
        }

        public Criteria andPassingModeBetween(Short value1, Short value2) {

            addCriterion("PASSING_MODE between", value1, value2, "passingMode");
            return (Criteria) this;
        }

        public Criteria andPassingModeNotBetween(Short value1, Short value2) {

            addCriterion("PASSING_MODE not between", value1, value2, "passingMode");
            return (Criteria) this;
        }

        public Criteria andCarrierActionCtrlIsNull() {

            addCriterion("CARRIER_ACTION_CTRL is null");
            return (Criteria) this;
        }

        public Criteria andCarrierActionCtrlIsNotNull() {

            addCriterion("CARRIER_ACTION_CTRL is not null");
            return (Criteria) this;
        }

        public Criteria andCarrierActionCtrlEqualTo(Short value) {

            addCriterion("CARRIER_ACTION_CTRL =", value, "carrierActionCtrl");
            return (Criteria) this;
        }

        public Criteria andCarrierActionCtrlNotEqualTo(Short value) {

            addCriterion("CARRIER_ACTION_CTRL <>", value, "carrierActionCtrl");
            return (Criteria) this;
        }

        public Criteria andCarrierActionCtrlGreaterThan(Short value) {

            addCriterion("CARRIER_ACTION_CTRL >", value, "carrierActionCtrl");
            return (Criteria) this;
        }

        public Criteria andCarrierActionCtrlGreaterThanOrEqualTo(Short value) {

            addCriterion("CARRIER_ACTION_CTRL >=", value, "carrierActionCtrl");
            return (Criteria) this;
        }

        public Criteria andCarrierActionCtrlLessThan(Short value) {

            addCriterion("CARRIER_ACTION_CTRL <", value, "carrierActionCtrl");
            return (Criteria) this;
        }

        public Criteria andCarrierActionCtrlLessThanOrEqualTo(Short value) {

            addCriterion("CARRIER_ACTION_CTRL <=", value, "carrierActionCtrl");
            return (Criteria) this;
        }

        public Criteria andCarrierActionCtrlIn(List<Short> values) {

            addCriterion("CARRIER_ACTION_CTRL in", values, "carrierActionCtrl");
            return (Criteria) this;
        }

        public Criteria andCarrierActionCtrlNotIn(List<Short> values) {

            addCriterion("CARRIER_ACTION_CTRL not in", values, "carrierActionCtrl");
            return (Criteria) this;
        }

        public Criteria andCarrierActionCtrlBetween(Short value1, Short value2) {

            addCriterion("CARRIER_ACTION_CTRL between", value1, value2, "carrierActionCtrl");
            return (Criteria) this;
        }

        public Criteria andCarrierActionCtrlNotBetween(Short value1, Short value2) {

            addCriterion("CARRIER_ACTION_CTRL not between", value1, value2, "carrierActionCtrl");
            return (Criteria) this;
        }

        public Criteria andCleanRequestIsNull() {
            addCriterion("CLEAN_REQUEST is null");
            return (Criteria) this;
        }

        public Criteria andCleanRequestIsNotNull() {
            addCriterion("CLEAN_REQUEST is not null");
            return (Criteria) this;
        }

        public Criteria andCleanRequestEqualTo(Short value) {
            addCriterion("CLEAN_REQUEST =", value, "cleanRequest");
            return (Criteria) this;
        }

        public Criteria andCleanRequestNotEqualTo(Short value) {
            addCriterion("CLEAN_REQUEST <>", value, "cleanRequest");
            return (Criteria) this;
        }

        public Criteria andCleanRequestGreaterThan(Short value) {
            addCriterion("CLEAN_REQUEST >", value, "cleanRequest");
            return (Criteria) this;
        }

        public Criteria andCleanRequestGreaterThanOrEqualTo(Short value) {
            addCriterion("CLEAN_REQUEST >=", value, "cleanRequest");
            return (Criteria) this;
        }

        public Criteria andCleanRequestLessThan(Short value) {
            addCriterion("CLEAN_REQUEST <", value, "cleanRequest");
            return (Criteria) this;
        }

        public Criteria andCleanRequestLessThanOrEqualTo(Short value) {
            addCriterion("CLEAN_REQUEST <=", value, "cleanRequest");
            return (Criteria) this;
        }

        public Criteria andCleanRequestIn(List<Short> values) {
            addCriterion("CLEAN_REQUEST in", values, "cleanRequest");
            return (Criteria) this;
        }

        public Criteria andCleanRequestNotIn(List<Short> values) {
            addCriterion("CLEAN_REQUEST not in", values, "cleanRequest");
            return (Criteria) this;
        }

        public Criteria andCleanRequestBetween(Short value1, Short value2) {
            addCriterion("CLEAN_REQUEST between", value1, value2, "cleanRequest");
            return (Criteria) this;
        }

        public Criteria andCleanRequestNotBetween(Short value1, Short value2) {
            addCriterion("CLEAN_REQUEST not between", value1, value2, "cleanRequest");
            return (Criteria) this;
        }

        public Criteria andContamiIdIsNull() {
            addCriterion("CONTAMI_ID is null");
            return (Criteria) this;
        }

        public Criteria andContamiIdIsNotNull() {
            addCriterion("CONTAMI_ID is not null");
            return (Criteria) this;
        }

        public Criteria andContamiIdEqualTo(String value) {
            addCriterion("CONTAMI_ID =", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdNotEqualTo(String value) {
            addCriterion("CONTAMI_ID <>", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdGreaterThan(String value) {
            addCriterion("CONTAMI_ID >", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdGreaterThanOrEqualTo(String value) {
            addCriterion("CONTAMI_ID >=", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdLessThan(String value) {
            addCriterion("CONTAMI_ID <", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdLessThanOrEqualTo(String value) {
            addCriterion("CONTAMI_ID <=", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdLike(String value) {
            addCriterion("CONTAMI_ID like", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdNotLike(String value) {
            addCriterion("CONTAMI_ID not like", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdIn(List<String> values) {
            addCriterion("CONTAMI_ID in", values, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdNotIn(List<String> values) {
            addCriterion("CONTAMI_ID not in", values, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdBetween(String value1, String value2) {
            addCriterion("CONTAMI_ID between", value1, value2, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdNotBetween(String value1, String value2) {
            addCriterion("CONTAMI_ID not between", value1, value2, "contamiId");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeIsNull() {
            addCriterion("PURPOSE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeIsNotNull() {
            addCriterion("PURPOSE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeEqualTo(String value) {
            addCriterion("PURPOSE_TYPE =", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeNotEqualTo(String value) {
            addCriterion("PURPOSE_TYPE <>", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeGreaterThan(String value) {
            addCriterion("PURPOSE_TYPE >", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PURPOSE_TYPE >=", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeLessThan(String value) {
            addCriterion("PURPOSE_TYPE <", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeLessThanOrEqualTo(String value) {
            addCriterion("PURPOSE_TYPE <=", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeLike(String value) {
            addCriterion("PURPOSE_TYPE like", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeNotLike(String value) {
            addCriterion("PURPOSE_TYPE not like", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeIn(List<String> values) {
            addCriterion("PURPOSE_TYPE in", values, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeNotIn(List<String> values) {
            addCriterion("PURPOSE_TYPE not in", values, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeBetween(String value1, String value2) {
            addCriterion("PURPOSE_TYPE between", value1, value2, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeNotBetween(String value1, String value2) {
            addCriterion("PURPOSE_TYPE not between", value1, value2, "purposeType");
            return (Criteria) this;
        }

        public Criteria andCarrierActionTimeIsNull() {
            addCriterion("CARRIER_ACTION_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCarrierActionTimeIsNotNull() {

            addCriterion("CARRIER_ACTION_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCarrierActionTimeEqualTo(Timestamp value) {

            addCriterion("CARRIER_ACTION_TIME =", value, "carrierActionTime");
            return (Criteria) this;
        }

        public Criteria andCarrierActionTimeNotEqualTo(Timestamp value) {

            addCriterion("CARRIER_ACTION_TIME <>", value, "carrierActionTime");
            return (Criteria) this;
        }

        public Criteria andCarrierActionTimeGreaterThan(Timestamp value) {

            addCriterion("CARRIER_ACTION_TIME >", value, "carrierActionTime");
            return (Criteria) this;
        }

        public Criteria andCarrierActionTimeGreaterThanOrEqualTo(Timestamp value) {

            addCriterion("CARRIER_ACTION_TIME >=", value, "carrierActionTime");
            return (Criteria) this;
        }

        public Criteria andCarrierActionTimeLessThan(Timestamp value) {

            addCriterion("CARRIER_ACTION_TIME <", value, "carrierActionTime");
            return (Criteria) this;
        }

        public Criteria andCarrierActionTimeLessThanOrEqualTo(Timestamp value) {

            addCriterion("CARRIER_ACTION_TIME <=", value, "carrierActionTime");
            return (Criteria) this;
        }

        public Criteria andCarrierActionTimeIn(List<Timestamp> values) {

            addCriterion("CARRIER_ACTION_TIME in", values, "carrierActionTime");
            return (Criteria) this;
        }

        public Criteria andCarrierActionTimeNotIn(List<Timestamp> values) {

            addCriterion("CARRIER_ACTION_TIME not in", values, "carrierActionTime");
            return (Criteria) this;
        }

        public Criteria andCarrierActionTimeBetween(Timestamp value1, Timestamp value2) {

            addCriterion("CARRIER_ACTION_TIME between", value1, value2, "carrierActionTime");
            return (Criteria) this;
        }

        public Criteria andCarrierActionTimeNotBetween(Timestamp value1, Timestamp value2) {

            addCriterion("CARRIER_ACTION_TIME not between", value1, value2, "carrierActionTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table CARRIER
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {

            return condition;
        }

        public Object getValue() {

            return value;
        }

        public Object getSecondValue() {

            return secondValue;
        }

        public boolean isNoValue() {

            return noValue;
        }

        public boolean isSingleValue() {

            return singleValue;
        }

        public boolean isBetweenValue() {

            return betweenValue;
        }

        public boolean isListValue() {

            return listValue;
        }

        public String getTypeHandler() {

            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table CARRIER
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 07 15:13:24 JST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}
