package net.muratec.mcs.model;

import java.sql.Timestamp;

public class CarrierJobProgress extends CarrierJobProgressKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.AMHS_ID
     * @mbg.generated
     */
    private String amhsId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.SRC_LOC_TYPE
     * @mbg.generated
     */
    private Short srcLocType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.SRC_LOC
     * @mbg.generated
     */
    private String srcLoc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.DST_LOC_TYPE
     * @mbg.generated
     */
    private Short dstLocType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.DST_LOC
     * @mbg.generated
     */
    private String dstLoc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.PRIORITY
     * @mbg.generated
     */
    private Short priority;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.REQ_TIME
     * @mbg.generated
     */
    private Timestamp reqTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.ANS_TIME
     * @mbg.generated
     */
    private Timestamp ansTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.INI_TIME
     * @mbg.generated
     */
    private Timestamp iniTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.ASSIGNED_TIME
     * @mbg.generated
     */
    private Timestamp assignedTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.SRC_ARRIVED_TIME
     * @mbg.generated
     */
    private Timestamp srcArrivedTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.ACQ_START_TIME
     * @mbg.generated
     */
    private Timestamp acqStartTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.ACQ_COMP_TIME
     * @mbg.generated
     */
    private Timestamp acqCompTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.DEPARTED_TIME
     * @mbg.generated
     */
    private Timestamp departedTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.DST_ARRIVED_TIME
     * @mbg.generated
     */
    private Timestamp dstArrivedTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.DEPO_START_TIME
     * @mbg.generated
     */
    private Timestamp depoStartTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.DEPO_COMP_TIME
     * @mbg.generated
     */
    private Timestamp depoCompTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.UNASSIGNED_TIME
     * @mbg.generated
     */
    private Timestamp unassignedTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.WAIT_IN_TIME
     * @mbg.generated
     */
    private Object waitInTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.CRANE_ACTIVE_TIME
     * @mbg.generated
     */
    private Timestamp craneActiveTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.CRANE_IDLE_TIME
     * @mbg.generated
     */
    private Timestamp craneIdleTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.COMP_TIME
     * @mbg.generated
     */
    private Timestamp compTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.ABORT_REQ_TIME
     * @mbg.generated
     */
    private Timestamp abortReqTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.ABORT_ANS_TIME
     * @mbg.generated
     */
    private Timestamp abortAnsTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.ABORT_INIT_TIME
     * @mbg.generated
     */
    private Timestamp abortInitTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.ABORT_COMP_TIME
     * @mbg.generated
     */
    private Timestamp abortCompTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.ABORT_REASON
     * @mbg.generated
     */
    private String abortReason;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.UNCOMP_FLAG
     * @mbg.generated
     */
    private Short uncompFlag;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.MACHINE_ID
     * @mbg.generated
     */
    private String machineId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.EST_PASS_TIME
     * @mbg.generated
     */
    private Timestamp estPassTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.PASSED_TIME
     * @mbg.generated
     */
    private Timestamp passedTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.CARRIER_JOB_STATE
     * @mbg.generated
     */
    private Short carrierJobState;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column CARRIER_JOB_PROGRESS.COMMAND_ID
     * @mbg.generated
     */
    private String commandId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.AMHS_ID
     * @return  the value of CARRIER_JOB_PROGRESS.AMHS_ID
     * @mbg.generated
     */
    public String getAmhsId() {

        return amhsId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.AMHS_ID
     * @param amhsId  the value for CARRIER_JOB_PROGRESS.AMHS_ID
     * @mbg.generated
     */
    public void setAmhsId(String amhsId) {

        this.amhsId = amhsId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.SRC_LOC_TYPE
     * @return  the value of CARRIER_JOB_PROGRESS.SRC_LOC_TYPE
     * @mbg.generated
     */
    public Short getSrcLocType() {

        return srcLocType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.SRC_LOC_TYPE
     * @param srcLocType  the value for CARRIER_JOB_PROGRESS.SRC_LOC_TYPE
     * @mbg.generated
     */
    public void setSrcLocType(Short srcLocType) {

        this.srcLocType = srcLocType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.SRC_LOC
     * @return  the value of CARRIER_JOB_PROGRESS.SRC_LOC
     * @mbg.generated
     */
    public String getSrcLoc() {

        return srcLoc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.SRC_LOC
     * @param srcLoc  the value for CARRIER_JOB_PROGRESS.SRC_LOC
     * @mbg.generated
     */
    public void setSrcLoc(String srcLoc) {

        this.srcLoc = srcLoc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.DST_LOC_TYPE
     * @return  the value of CARRIER_JOB_PROGRESS.DST_LOC_TYPE
     * @mbg.generated
     */
    public Short getDstLocType() {

        return dstLocType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.DST_LOC_TYPE
     * @param dstLocType  the value for CARRIER_JOB_PROGRESS.DST_LOC_TYPE
     * @mbg.generated
     */
    public void setDstLocType(Short dstLocType) {

        this.dstLocType = dstLocType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.DST_LOC
     * @return  the value of CARRIER_JOB_PROGRESS.DST_LOC
     * @mbg.generated
     */
    public String getDstLoc() {

        return dstLoc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.DST_LOC
     * @param dstLoc  the value for CARRIER_JOB_PROGRESS.DST_LOC
     * @mbg.generated
     */
    public void setDstLoc(String dstLoc) {

        this.dstLoc = dstLoc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.PRIORITY
     * @return  the value of CARRIER_JOB_PROGRESS.PRIORITY
     * @mbg.generated
     */
    public Short getPriority() {

        return priority;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.PRIORITY
     * @param priority  the value for CARRIER_JOB_PROGRESS.PRIORITY
     * @mbg.generated
     */
    public void setPriority(Short priority) {

        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.REQ_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.REQ_TIME
     * @mbg.generated
     */
    public Timestamp getReqTime() {

        return reqTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.REQ_TIME
     * @param reqTime  the value for CARRIER_JOB_PROGRESS.REQ_TIME
     * @mbg.generated
     */
    public void setReqTime(Timestamp reqTime) {

        this.reqTime = reqTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.ANS_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.ANS_TIME
     * @mbg.generated
     */
    public Timestamp getAnsTime() {

        return ansTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.ANS_TIME
     * @param ansTime  the value for CARRIER_JOB_PROGRESS.ANS_TIME
     * @mbg.generated
     */
    public void setAnsTime(Timestamp ansTime) {

        this.ansTime = ansTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.INI_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.INI_TIME
     * @mbg.generated
     */
    public Timestamp getIniTime() {

        return iniTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.INI_TIME
     * @param iniTime  the value for CARRIER_JOB_PROGRESS.INI_TIME
     * @mbg.generated
     */
    public void setIniTime(Timestamp iniTime) {

        this.iniTime = iniTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.ASSIGNED_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.ASSIGNED_TIME
     * @mbg.generated
     */
    public Timestamp getAssignedTime() {

        return assignedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.ASSIGNED_TIME
     * @param assignedTime  the value for CARRIER_JOB_PROGRESS.ASSIGNED_TIME
     * @mbg.generated
     */
    public void setAssignedTime(Timestamp assignedTime) {

        this.assignedTime = assignedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.SRC_ARRIVED_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.SRC_ARRIVED_TIME
     * @mbg.generated
     */
    public Timestamp getSrcArrivedTime() {

        return srcArrivedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.SRC_ARRIVED_TIME
     * @param srcArrivedTime  the value for CARRIER_JOB_PROGRESS.SRC_ARRIVED_TIME
     * @mbg.generated
     */
    public void setSrcArrivedTime(Timestamp srcArrivedTime) {

        this.srcArrivedTime = srcArrivedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.ACQ_START_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.ACQ_START_TIME
     * @mbg.generated
     */
    public Timestamp getAcqStartTime() {

        return acqStartTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.ACQ_START_TIME
     * @param acqStartTime  the value for CARRIER_JOB_PROGRESS.ACQ_START_TIME
     * @mbg.generated
     */
    public void setAcqStartTime(Timestamp acqStartTime) {

        this.acqStartTime = acqStartTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.ACQ_COMP_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.ACQ_COMP_TIME
     * @mbg.generated
     */
    public Timestamp getAcqCompTime() {

        return acqCompTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.ACQ_COMP_TIME
     * @param acqCompTime  the value for CARRIER_JOB_PROGRESS.ACQ_COMP_TIME
     * @mbg.generated
     */
    public void setAcqCompTime(Timestamp acqCompTime) {

        this.acqCompTime = acqCompTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.DEPARTED_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.DEPARTED_TIME
     * @mbg.generated
     */
    public Timestamp getDepartedTime() {

        return departedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.DEPARTED_TIME
     * @param departedTime  the value for CARRIER_JOB_PROGRESS.DEPARTED_TIME
     * @mbg.generated
     */
    public void setDepartedTime(Timestamp departedTime) {

        this.departedTime = departedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.DST_ARRIVED_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.DST_ARRIVED_TIME
     * @mbg.generated
     */
    public Timestamp getDstArrivedTime() {

        return dstArrivedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.DST_ARRIVED_TIME
     * @param dstArrivedTime  the value for CARRIER_JOB_PROGRESS.DST_ARRIVED_TIME
     * @mbg.generated
     */
    public void setDstArrivedTime(Timestamp dstArrivedTime) {

        this.dstArrivedTime = dstArrivedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.DEPO_START_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.DEPO_START_TIME
     * @mbg.generated
     */
    public Timestamp getDepoStartTime() {

        return depoStartTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.DEPO_START_TIME
     * @param depoStartTime  the value for CARRIER_JOB_PROGRESS.DEPO_START_TIME
     * @mbg.generated
     */
    public void setDepoStartTime(Timestamp depoStartTime) {

        this.depoStartTime = depoStartTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.DEPO_COMP_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.DEPO_COMP_TIME
     * @mbg.generated
     */
    public Timestamp getDepoCompTime() {

        return depoCompTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.DEPO_COMP_TIME
     * @param depoCompTime  the value for CARRIER_JOB_PROGRESS.DEPO_COMP_TIME
     * @mbg.generated
     */
    public void setDepoCompTime(Timestamp depoCompTime) {

        this.depoCompTime = depoCompTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.UNASSIGNED_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.UNASSIGNED_TIME
     * @mbg.generated
     */
    public Timestamp getUnassignedTime() {

        return unassignedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.UNASSIGNED_TIME
     * @param unassignedTime  the value for CARRIER_JOB_PROGRESS.UNASSIGNED_TIME
     * @mbg.generated
     */
    public void setUnassignedTime(Timestamp unassignedTime) {

        this.unassignedTime = unassignedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.WAIT_IN_TIME
     * @return the value of CARRIER_JOB_PROGRESS.WAIT_IN_TIME
     * @mbg.generated
     */
    public Object getWaitInTime() {

        return waitInTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.WAIT_IN_TIME
     * @param waitInTime the value for CARRIER_JOB_PROGRESS.WAIT_IN_TIME
     * @mbg.generated
     */
    public void setWaitInTime(Object waitInTime) {

        this.waitInTime = waitInTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.CRANE_ACTIVE_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.CRANE_ACTIVE_TIME
     * @mbg.generated
     */
    public Timestamp getCraneActiveTime() {

        return craneActiveTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.CRANE_ACTIVE_TIME
     * @param craneActiveTime  the value for CARRIER_JOB_PROGRESS.CRANE_ACTIVE_TIME
     * @mbg.generated
     */
    public void setCraneActiveTime(Timestamp craneActiveTime) {

        this.craneActiveTime = craneActiveTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.CRANE_IDLE_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.CRANE_IDLE_TIME
     * @mbg.generated
     */
    public Timestamp getCraneIdleTime() {

        return craneIdleTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.CRANE_IDLE_TIME
     * @param craneIdleTime  the value for CARRIER_JOB_PROGRESS.CRANE_IDLE_TIME
     * @mbg.generated
     */
    public void setCraneIdleTime(Timestamp craneIdleTime) {

        this.craneIdleTime = craneIdleTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.COMP_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.COMP_TIME
     * @mbg.generated
     */
    public Timestamp getCompTime() {

        return compTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.COMP_TIME
     * @param compTime  the value for CARRIER_JOB_PROGRESS.COMP_TIME
     * @mbg.generated
     */
    public void setCompTime(Timestamp compTime) {

        this.compTime = compTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.ABORT_REQ_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.ABORT_REQ_TIME
     * @mbg.generated
     */
    public Timestamp getAbortReqTime() {

        return abortReqTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.ABORT_REQ_TIME
     * @param abortReqTime  the value for CARRIER_JOB_PROGRESS.ABORT_REQ_TIME
     * @mbg.generated
     */
    public void setAbortReqTime(Timestamp abortReqTime) {

        this.abortReqTime = abortReqTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.ABORT_ANS_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.ABORT_ANS_TIME
     * @mbg.generated
     */
    public Timestamp getAbortAnsTime() {

        return abortAnsTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.ABORT_ANS_TIME
     * @param abortAnsTime  the value for CARRIER_JOB_PROGRESS.ABORT_ANS_TIME
     * @mbg.generated
     */
    public void setAbortAnsTime(Timestamp abortAnsTime) {

        this.abortAnsTime = abortAnsTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.ABORT_INIT_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.ABORT_INIT_TIME
     * @mbg.generated
     */
    public Timestamp getAbortInitTime() {

        return abortInitTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.ABORT_INIT_TIME
     * @param abortInitTime  the value for CARRIER_JOB_PROGRESS.ABORT_INIT_TIME
     * @mbg.generated
     */
    public void setAbortInitTime(Timestamp abortInitTime) {

        this.abortInitTime = abortInitTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.ABORT_COMP_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.ABORT_COMP_TIME
     * @mbg.generated
     */
    public Timestamp getAbortCompTime() {

        return abortCompTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.ABORT_COMP_TIME
     * @param abortCompTime  the value for CARRIER_JOB_PROGRESS.ABORT_COMP_TIME
     * @mbg.generated
     */
    public void setAbortCompTime(Timestamp abortCompTime) {

        this.abortCompTime = abortCompTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.ABORT_REASON
     * @return  the value of CARRIER_JOB_PROGRESS.ABORT_REASON
     * @mbg.generated
     */
    public String getAbortReason() {

        return abortReason;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.ABORT_REASON
     * @param abortReason  the value for CARRIER_JOB_PROGRESS.ABORT_REASON
     * @mbg.generated
     */
    public void setAbortReason(String abortReason) {

        this.abortReason = abortReason;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.UNCOMP_FLAG
     * @return  the value of CARRIER_JOB_PROGRESS.UNCOMP_FLAG
     * @mbg.generated
     */
    public Short getUncompFlag() {

        return uncompFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.UNCOMP_FLAG
     * @param uncompFlag  the value for CARRIER_JOB_PROGRESS.UNCOMP_FLAG
     * @mbg.generated
     */
    public void setUncompFlag(Short uncompFlag) {

        this.uncompFlag = uncompFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.MACHINE_ID
     * @return  the value of CARRIER_JOB_PROGRESS.MACHINE_ID
     * @mbg.generated
     */
    public String getMachineId() {

        return machineId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.MACHINE_ID
     * @param machineId  the value for CARRIER_JOB_PROGRESS.MACHINE_ID
     * @mbg.generated
     */
    public void setMachineId(String machineId) {

        this.machineId = machineId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.EST_PASS_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.EST_PASS_TIME
     * @mbg.generated
     */
    public Timestamp getEstPassTime() {

        return estPassTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.EST_PASS_TIME
     * @param estPassTime  the value for CARRIER_JOB_PROGRESS.EST_PASS_TIME
     * @mbg.generated
     */
    public void setEstPassTime(Timestamp estPassTime) {

        this.estPassTime = estPassTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.PASSED_TIME
     * @return  the value of CARRIER_JOB_PROGRESS.PASSED_TIME
     * @mbg.generated
     */
    public Timestamp getPassedTime() {

        return passedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.PASSED_TIME
     * @param passedTime  the value for CARRIER_JOB_PROGRESS.PASSED_TIME
     * @mbg.generated
     */
    public void setPassedTime(Timestamp passedTime) {

        this.passedTime = passedTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.CARRIER_JOB_STATE
     * @return  the value of CARRIER_JOB_PROGRESS.CARRIER_JOB_STATE
     * @mbg.generated
     */
    public Short getCarrierJobState() {

        return carrierJobState;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.CARRIER_JOB_STATE
     * @param carrierJobState  the value for CARRIER_JOB_PROGRESS.CARRIER_JOB_STATE
     * @mbg.generated
     */
    public void setCarrierJobState(Short carrierJobState) {

        this.carrierJobState = carrierJobState;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column CARRIER_JOB_PROGRESS.COMMAND_ID
     * @return  the value of CARRIER_JOB_PROGRESS.COMMAND_ID
     * @mbg.generated
     */
    public String getCommandId() {

        return commandId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column CARRIER_JOB_PROGRESS.COMMAND_ID
     * @param commandId  the value for CARRIER_JOB_PROGRESS.COMMAND_ID
     * @mbg.generated
     */
    public void setCommandId(String commandId) {

        this.commandId = commandId;
    }
}
