package net.muratec.mcs.model;

import java.util.ArrayList;
import java.util.List;

public class DestinationExample {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table DESTINATION
     * @mbg.generated
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table DESTINATION
     * @mbg.generated
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table DESTINATION
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DESTINATION
     * @mbg.generated
     */
    public DestinationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DESTINATION
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {

        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DESTINATION
     * @mbg.generated
     */
    public String getOrderByClause() {

        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DESTINATION
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {

        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DESTINATION
     * @mbg.generated
     */
    public boolean isDistinct() {

        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DESTINATION
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {

        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DESTINATION
     * @mbg.generated
     */
    public void or(Criteria criteria) {

        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DESTINATION
     * @mbg.generated
     */
    public Criteria or() {

        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DESTINATION
     * @mbg.generated
     */
    public Criteria createCriteria() {

        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DESTINATION
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {

        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DESTINATION
     * @mbg.generated
     */
    public void clear() {

        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table DESTINATION
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {

            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {

            return criteria;
        }

        public List<Criterion> getCriteria() {

            return criteria;
        }

        protected void addCriterion(String condition) {

            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {

            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {

            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCarrierJobIdIsNull() {

            addCriterion("CARRIER_JOB_ID is null");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdIsNotNull() {

            addCriterion("CARRIER_JOB_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdEqualTo(String value) {

            addCriterion("CARRIER_JOB_ID =", value, "carrierJobId");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdNotEqualTo(String value) {

            addCriterion("CARRIER_JOB_ID <>", value, "carrierJobId");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdGreaterThan(String value) {

            addCriterion("CARRIER_JOB_ID >", value, "carrierJobId");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdGreaterThanOrEqualTo(String value) {

            addCriterion("CARRIER_JOB_ID >=", value, "carrierJobId");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdLessThan(String value) {

            addCriterion("CARRIER_JOB_ID <", value, "carrierJobId");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdLessThanOrEqualTo(String value) {

            addCriterion("CARRIER_JOB_ID <=", value, "carrierJobId");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdLike(String value) {

            addCriterion("CARRIER_JOB_ID like", value, "carrierJobId");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdNotLike(String value) {

            addCriterion("CARRIER_JOB_ID not like", value, "carrierJobId");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdIn(List<String> values) {

            addCriterion("CARRIER_JOB_ID in", values, "carrierJobId");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdNotIn(List<String> values) {

            addCriterion("CARRIER_JOB_ID not in", values, "carrierJobId");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdBetween(String value1, String value2) {

            addCriterion("CARRIER_JOB_ID between", value1, value2, "carrierJobId");
            return (Criteria) this;
        }

        public Criteria andCarrierJobIdNotBetween(String value1, String value2) {

            addCriterion("CARRIER_JOB_ID not between", value1, value2, "carrierJobId");
            return (Criteria) this;
        }

        public Criteria andSeqNoIsNull() {

            addCriterion("SEQ_NO is null");
            return (Criteria) this;
        }

        public Criteria andSeqNoIsNotNull() {

            addCriterion("SEQ_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSeqNoEqualTo(Integer value) {

            addCriterion("SEQ_NO =", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotEqualTo(Integer value) {

            addCriterion("SEQ_NO <>", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoGreaterThan(Integer value) {

            addCriterion("SEQ_NO >", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoGreaterThanOrEqualTo(Integer value) {

            addCriterion("SEQ_NO >=", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLessThan(Integer value) {

            addCriterion("SEQ_NO <", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLessThanOrEqualTo(Integer value) {

            addCriterion("SEQ_NO <=", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoIn(List<Integer> values) {

            addCriterion("SEQ_NO in", values, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotIn(List<Integer> values) {

            addCriterion("SEQ_NO not in", values, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoBetween(Integer value1, Integer value2) {

            addCriterion("SEQ_NO between", value1, value2, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotBetween(Integer value1, Integer value2) {

            addCriterion("SEQ_NO not between", value1, value2, "seqNo");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdIsNull() {

            addCriterion("MACRO_DST_GROUP_ID is null");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdIsNotNull() {

            addCriterion("MACRO_DST_GROUP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdEqualTo(String value) {

            addCriterion("MACRO_DST_GROUP_ID =", value, "macroDstGroupId");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdNotEqualTo(String value) {

            addCriterion("MACRO_DST_GROUP_ID <>", value, "macroDstGroupId");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdGreaterThan(String value) {

            addCriterion("MACRO_DST_GROUP_ID >", value, "macroDstGroupId");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdGreaterThanOrEqualTo(String value) {

            addCriterion("MACRO_DST_GROUP_ID >=", value, "macroDstGroupId");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdLessThan(String value) {

            addCriterion("MACRO_DST_GROUP_ID <", value, "macroDstGroupId");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdLessThanOrEqualTo(String value) {

            addCriterion("MACRO_DST_GROUP_ID <=", value, "macroDstGroupId");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdLike(String value) {

            addCriterion("MACRO_DST_GROUP_ID like", value, "macroDstGroupId");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdNotLike(String value) {

            addCriterion("MACRO_DST_GROUP_ID not like", value, "macroDstGroupId");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdIn(List<String> values) {

            addCriterion("MACRO_DST_GROUP_ID in", values, "macroDstGroupId");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdNotIn(List<String> values) {

            addCriterion("MACRO_DST_GROUP_ID not in", values, "macroDstGroupId");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdBetween(String value1, String value2) {

            addCriterion("MACRO_DST_GROUP_ID between", value1, value2, "macroDstGroupId");
            return (Criteria) this;
        }

        public Criteria andMacroDstGroupIdNotBetween(String value1, String value2) {

            addCriterion("MACRO_DST_GROUP_ID not between", value1, value2, "macroDstGroupId");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdIsNull() {

            addCriterion("MACRO_DST_AMHS_ID is null");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdIsNotNull() {

            addCriterion("MACRO_DST_AMHS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdEqualTo(String value) {

            addCriterion("MACRO_DST_AMHS_ID =", value, "macroDstAmhsId");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdNotEqualTo(String value) {

            addCriterion("MACRO_DST_AMHS_ID <>", value, "macroDstAmhsId");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdGreaterThan(String value) {

            addCriterion("MACRO_DST_AMHS_ID >", value, "macroDstAmhsId");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdGreaterThanOrEqualTo(String value) {

            addCriterion("MACRO_DST_AMHS_ID >=", value, "macroDstAmhsId");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdLessThan(String value) {

            addCriterion("MACRO_DST_AMHS_ID <", value, "macroDstAmhsId");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdLessThanOrEqualTo(String value) {

            addCriterion("MACRO_DST_AMHS_ID <=", value, "macroDstAmhsId");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdLike(String value) {

            addCriterion("MACRO_DST_AMHS_ID like", value, "macroDstAmhsId");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdNotLike(String value) {

            addCriterion("MACRO_DST_AMHS_ID not like", value, "macroDstAmhsId");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdIn(List<String> values) {

            addCriterion("MACRO_DST_AMHS_ID in", values, "macroDstAmhsId");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdNotIn(List<String> values) {

            addCriterion("MACRO_DST_AMHS_ID not in", values, "macroDstAmhsId");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdBetween(String value1, String value2) {

            addCriterion("MACRO_DST_AMHS_ID between", value1, value2, "macroDstAmhsId");
            return (Criteria) this;
        }

        public Criteria andMacroDstAmhsIdNotBetween(String value1, String value2) {

            addCriterion("MACRO_DST_AMHS_ID not between", value1, value2, "macroDstAmhsId");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocTypeIsNull() {

            addCriterion("MACRO_DST_LOC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocTypeIsNotNull() {

            addCriterion("MACRO_DST_LOC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocTypeEqualTo(Short value) {

            addCriterion("MACRO_DST_LOC_TYPE =", value, "macroDstLocType");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocTypeNotEqualTo(Short value) {

            addCriterion("MACRO_DST_LOC_TYPE <>", value, "macroDstLocType");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocTypeGreaterThan(Short value) {

            addCriterion("MACRO_DST_LOC_TYPE >", value, "macroDstLocType");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocTypeGreaterThanOrEqualTo(Short value) {

            addCriterion("MACRO_DST_LOC_TYPE >=", value, "macroDstLocType");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocTypeLessThan(Short value) {

            addCriterion("MACRO_DST_LOC_TYPE <", value, "macroDstLocType");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocTypeLessThanOrEqualTo(Short value) {

            addCriterion("MACRO_DST_LOC_TYPE <=", value, "macroDstLocType");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocTypeIn(List<Short> values) {

            addCriterion("MACRO_DST_LOC_TYPE in", values, "macroDstLocType");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocTypeNotIn(List<Short> values) {

            addCriterion("MACRO_DST_LOC_TYPE not in", values, "macroDstLocType");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocTypeBetween(Short value1, Short value2) {

            addCriterion("MACRO_DST_LOC_TYPE between", value1, value2, "macroDstLocType");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocTypeNotBetween(Short value1, Short value2) {

            addCriterion("MACRO_DST_LOC_TYPE not between", value1, value2, "macroDstLocType");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocIsNull() {

            addCriterion("MACRO_DST_LOC is null");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocIsNotNull() {

            addCriterion("MACRO_DST_LOC is not null");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocEqualTo(String value) {

            addCriterion("MACRO_DST_LOC =", value, "macroDstLoc");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocNotEqualTo(String value) {

            addCriterion("MACRO_DST_LOC <>", value, "macroDstLoc");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocGreaterThan(String value) {

            addCriterion("MACRO_DST_LOC >", value, "macroDstLoc");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocGreaterThanOrEqualTo(String value) {

            addCriterion("MACRO_DST_LOC >=", value, "macroDstLoc");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocLessThan(String value) {

            addCriterion("MACRO_DST_LOC <", value, "macroDstLoc");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocLessThanOrEqualTo(String value) {

            addCriterion("MACRO_DST_LOC <=", value, "macroDstLoc");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocLike(String value) {

            addCriterion("MACRO_DST_LOC like", value, "macroDstLoc");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocNotLike(String value) {

            addCriterion("MACRO_DST_LOC not like", value, "macroDstLoc");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocIn(List<String> values) {

            addCriterion("MACRO_DST_LOC in", values, "macroDstLoc");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocNotIn(List<String> values) {

            addCriterion("MACRO_DST_LOC not in", values, "macroDstLoc");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocBetween(String value1, String value2) {

            addCriterion("MACRO_DST_LOC between", value1, value2, "macroDstLoc");
            return (Criteria) this;
        }

        public Criteria andMacroDstLocNotBetween(String value1, String value2) {

            addCriterion("MACRO_DST_LOC not between", value1, value2, "macroDstLoc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table DESTINATION
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {

            return condition;
        }

        public Object getValue() {

            return value;
        }

        public Object getSecondValue() {

            return secondValue;
        }

        public boolean isNoValue() {

            return noValue;
        }

        public boolean isSingleValue() {

            return singleValue;
        }

        public boolean isBetweenValue() {

            return betweenValue;
        }

        public boolean isListValue() {

            return listValue;
        }

        public String getTypeHandler() {

            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * DESTINATION
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 07 15:13:24 JST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}
