package net.muratec.mcs.model;

import java.util.ArrayList;
import java.util.List;

public class EmptyCarrierDistributionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    public EmptyCarrierDistributionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andControllerIdIsNull() {
            addCriterion("CONTROLLER_ID is null");
            return (Criteria) this;
        }

        public Criteria andControllerIdIsNotNull() {
            addCriterion("CONTROLLER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andControllerIdEqualTo(String value) {
            addCriterion("CONTROLLER_ID =", value, "controllerId");
            return (Criteria) this;
        }

        public Criteria andControllerIdNotEqualTo(String value) {
            addCriterion("CONTROLLER_ID <>", value, "controllerId");
            return (Criteria) this;
        }

        public Criteria andControllerIdGreaterThan(String value) {
            addCriterion("CONTROLLER_ID >", value, "controllerId");
            return (Criteria) this;
        }

        public Criteria andControllerIdGreaterThanOrEqualTo(String value) {
            addCriterion("CONTROLLER_ID >=", value, "controllerId");
            return (Criteria) this;
        }

        public Criteria andControllerIdLessThan(String value) {
            addCriterion("CONTROLLER_ID <", value, "controllerId");
            return (Criteria) this;
        }

        public Criteria andControllerIdLessThanOrEqualTo(String value) {
            addCriterion("CONTROLLER_ID <=", value, "controllerId");
            return (Criteria) this;
        }

        public Criteria andControllerIdLike(String value) {
            addCriterion("CONTROLLER_ID like", value, "controllerId");
            return (Criteria) this;
        }

        public Criteria andControllerIdNotLike(String value) {
            addCriterion("CONTROLLER_ID not like", value, "controllerId");
            return (Criteria) this;
        }

        public Criteria andControllerIdIn(List<String> values) {
            addCriterion("CONTROLLER_ID in", values, "controllerId");
            return (Criteria) this;
        }

        public Criteria andControllerIdNotIn(List<String> values) {
            addCriterion("CONTROLLER_ID not in", values, "controllerId");
            return (Criteria) this;
        }

        public Criteria andControllerIdBetween(String value1, String value2) {
            addCriterion("CONTROLLER_ID between", value1, value2, "controllerId");
            return (Criteria) this;
        }

        public Criteria andControllerIdNotBetween(String value1, String value2) {
            addCriterion("CONTROLLER_ID not between", value1, value2, "controllerId");
            return (Criteria) this;
        }

        public Criteria andContamiIdIsNull() {
            addCriterion("CONTAMI_ID is null");
            return (Criteria) this;
        }

        public Criteria andContamiIdIsNotNull() {
            addCriterion("CONTAMI_ID is not null");
            return (Criteria) this;
        }

        public Criteria andContamiIdEqualTo(String value) {
            addCriterion("CONTAMI_ID =", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdNotEqualTo(String value) {
            addCriterion("CONTAMI_ID <>", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdGreaterThan(String value) {
            addCriterion("CONTAMI_ID >", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdGreaterThanOrEqualTo(String value) {
            addCriterion("CONTAMI_ID >=", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdLessThan(String value) {
            addCriterion("CONTAMI_ID <", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdLessThanOrEqualTo(String value) {
            addCriterion("CONTAMI_ID <=", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdLike(String value) {
            addCriterion("CONTAMI_ID like", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdNotLike(String value) {
            addCriterion("CONTAMI_ID not like", value, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdIn(List<String> values) {
            addCriterion("CONTAMI_ID in", values, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdNotIn(List<String> values) {
            addCriterion("CONTAMI_ID not in", values, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdBetween(String value1, String value2) {
            addCriterion("CONTAMI_ID between", value1, value2, "contamiId");
            return (Criteria) this;
        }

        public Criteria andContamiIdNotBetween(String value1, String value2) {
            addCriterion("CONTAMI_ID not between", value1, value2, "contamiId");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeIsNull() {
            addCriterion("PURPOSE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeIsNotNull() {
            addCriterion("PURPOSE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeEqualTo(String value) {
            addCriterion("PURPOSE_TYPE =", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeNotEqualTo(String value) {
            addCriterion("PURPOSE_TYPE <>", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeGreaterThan(String value) {
            addCriterion("PURPOSE_TYPE >", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PURPOSE_TYPE >=", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeLessThan(String value) {
            addCriterion("PURPOSE_TYPE <", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeLessThanOrEqualTo(String value) {
            addCriterion("PURPOSE_TYPE <=", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeLike(String value) {
            addCriterion("PURPOSE_TYPE like", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeNotLike(String value) {
            addCriterion("PURPOSE_TYPE not like", value, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeIn(List<String> values) {
            addCriterion("PURPOSE_TYPE in", values, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeNotIn(List<String> values) {
            addCriterion("PURPOSE_TYPE not in", values, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeBetween(String value1, String value2) {
            addCriterion("PURPOSE_TYPE between", value1, value2, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPurposeTypeNotBetween(String value1, String value2) {
            addCriterion("PURPOSE_TYPE not between", value1, value2, "purposeType");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("PRIORITY is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("PRIORITY is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Short value) {
            addCriterion("PRIORITY =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Short value) {
            addCriterion("PRIORITY <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Short value) {
            addCriterion("PRIORITY >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Short value) {
            addCriterion("PRIORITY >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Short value) {
            addCriterion("PRIORITY <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Short value) {
            addCriterion("PRIORITY <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Short> values) {
            addCriterion("PRIORITY in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Short> values) {
            addCriterion("PRIORITY not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Short value1, Short value2) {
            addCriterion("PRIORITY between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Short value1, Short value2) {
            addCriterion("PRIORITY not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdIsNull() {
            addCriterion("DISTRIBUTION_CONTROLLER_ID is null");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdIsNotNull() {
            addCriterion("DISTRIBUTION_CONTROLLER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdEqualTo(String value) {
            addCriterion("DISTRIBUTION_CONTROLLER_ID =", value, "distributionControllerId");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdNotEqualTo(String value) {
            addCriterion("DISTRIBUTION_CONTROLLER_ID <>", value, "distributionControllerId");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdGreaterThan(String value) {
            addCriterion("DISTRIBUTION_CONTROLLER_ID >", value, "distributionControllerId");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdGreaterThanOrEqualTo(String value) {
            addCriterion("DISTRIBUTION_CONTROLLER_ID >=", value, "distributionControllerId");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdLessThan(String value) {
            addCriterion("DISTRIBUTION_CONTROLLER_ID <", value, "distributionControllerId");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdLessThanOrEqualTo(String value) {
            addCriterion("DISTRIBUTION_CONTROLLER_ID <=", value, "distributionControllerId");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdLike(String value) {
            addCriterion("DISTRIBUTION_CONTROLLER_ID like", value, "distributionControllerId");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdNotLike(String value) {
            addCriterion("DISTRIBUTION_CONTROLLER_ID not like", value, "distributionControllerId");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdIn(List<String> values) {
            addCriterion("DISTRIBUTION_CONTROLLER_ID in", values, "distributionControllerId");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdNotIn(List<String> values) {
            addCriterion("DISTRIBUTION_CONTROLLER_ID not in", values, "distributionControllerId");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdBetween(String value1, String value2) {
            addCriterion("DISTRIBUTION_CONTROLLER_ID between", value1, value2, "distributionControllerId");
            return (Criteria) this;
        }

        public Criteria andDistributionControllerIdNotBetween(String value1, String value2) {
            addCriterion("DISTRIBUTION_CONTROLLER_ID not between", value1, value2, "distributionControllerId");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Short value) {
            addCriterion("FLAG =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Short value) {
            addCriterion("FLAG <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Short value) {
            addCriterion("FLAG >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("FLAG >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Short value) {
            addCriterion("FLAG <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Short value) {
            addCriterion("FLAG <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Short> values) {
            addCriterion("FLAG in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Short> values) {
            addCriterion("FLAG not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Short value1, Short value2) {
            addCriterion("FLAG between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Short value1, Short value2) {
            addCriterion("FLAG not between", value1, value2, "flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EMPTY_CARRIER_DISTRIBUTION
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}