package net.muratec.mcs.model;

public class EmptyCarrierKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPTY_CARRIER.CONTROLLER_ID
     *
     * @mbg.generated
     */
    private String controllerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPTY_CARRIER.CONTAMI_ID
     *
     * @mbg.generated
     */
    private String contamiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPTY_CARRIER.PURPOSE_TYPE
     *
     * @mbg.generated
     */
    private String purposeType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPTY_CARRIER.CONTROLLER_ID
     *
     * @return the value of EMPTY_CARRIER.CONTROLLER_ID
     *
     * @mbg.generated
     */
    public String getControllerId() {
        return controllerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPTY_CARRIER.CONTROLLER_ID
     *
     * @param controllerId the value for EMPTY_CARRIER.CONTROLLER_ID
     *
     * @mbg.generated
     */
    public void setControllerId(String controllerId) {
        this.controllerId = controllerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPTY_CARRIER.CONTAMI_ID
     *
     * @return the value of EMPTY_CARRIER.CONTAMI_ID
     *
     * @mbg.generated
     */
    public String getContamiId() {
        return contamiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPTY_CARRIER.CONTAMI_ID
     *
     * @param contamiId the value for EMPTY_CARRIER.CONTAMI_ID
     *
     * @mbg.generated
     */
    public void setContamiId(String contamiId) {
        this.contamiId = contamiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPTY_CARRIER.PURPOSE_TYPE
     *
     * @return the value of EMPTY_CARRIER.PURPOSE_TYPE
     *
     * @mbg.generated
     */
    public String getPurposeType() {
        return purposeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPTY_CARRIER.PURPOSE_TYPE
     *
     * @param purposeType the value for EMPTY_CARRIER.PURPOSE_TYPE
     *
     * @mbg.generated
     */
    public void setPurposeType(String purposeType) {
        this.purposeType = purposeType;
    }
}