package net.muratec.mcs.model;

public class EmptyCarrierSupplySourceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPTY_CARRIER_SUPPLY_SOURCE.CONTROLLER_ID
     *
     * @mbg.generated
     */
    private String controllerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPTY_CARRIER_SUPPLY_SOURCE.PRIORITY
     *
     * @mbg.generated
     */
    private Short priority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPTY_CARRIER_SUPPLY_SOURCE.CONTROLLER_ID
     *
     * @return the value of EMPTY_CARRIER_SUPPLY_SOURCE.CONTROLLER_ID
     *
     * @mbg.generated
     */
    public String getControllerId() {
        return controllerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPTY_CARRIER_SUPPLY_SOURCE.CONTROLLER_ID
     *
     * @param controllerId the value for EMPTY_CARRIER_SUPPLY_SOURCE.CONTROLLER_ID
     *
     * @mbg.generated
     */
    public void setControllerId(String controllerId) {
        this.controllerId = controllerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPTY_CARRIER_SUPPLY_SOURCE.PRIORITY
     *
     * @return the value of EMPTY_CARRIER_SUPPLY_SOURCE.PRIORITY
     *
     * @mbg.generated
     */
    public Short getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPTY_CARRIER_SUPPLY_SOURCE.PRIORITY
     *
     * @param priority the value for EMPTY_CARRIER_SUPPLY_SOURCE.PRIORITY
     *
     * @mbg.generated
     */
    public void setPriority(Short priority) {
        this.priority = priority;
    }
}