package net.muratec.mcs.model;

import java.util.ArrayList;
import java.util.List;

public class ExerciseExample {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table EXERCISE
     * @mbg.generated
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table EXERCISE
     * @mbg.generated
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table EXERCISE
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE
     * @mbg.generated
     */
    public ExerciseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {

        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE
     * @mbg.generated
     */
    public String getOrderByClause() {

        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {

        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE
     * @mbg.generated
     */
    public boolean isDistinct() {

        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {

        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE
     * @mbg.generated
     */
    public void or(Criteria criteria) {

        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE
     * @mbg.generated
     */
    public Criteria or() {

        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE
     * @mbg.generated
     */
    public Criteria createCriteria() {

        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {

        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE
     * @mbg.generated
     */
    public void clear() {

        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table EXERCISE
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {

            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {

            return criteria;
        }

        public List<Criterion> getCriteria() {

            return criteria;
        }

        protected void addCriterion(String condition) {

            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {

            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {

            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCarrierIdIsNull() {

            addCriterion("CARRIER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCarrierIdIsNotNull() {

            addCriterion("CARRIER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCarrierIdEqualTo(String value) {

            addCriterion("CARRIER_ID =", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdNotEqualTo(String value) {

            addCriterion("CARRIER_ID <>", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdGreaterThan(String value) {

            addCriterion("CARRIER_ID >", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdGreaterThanOrEqualTo(String value) {

            addCriterion("CARRIER_ID >=", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdLessThan(String value) {

            addCriterion("CARRIER_ID <", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdLessThanOrEqualTo(String value) {

            addCriterion("CARRIER_ID <=", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdLike(String value) {

            addCriterion("CARRIER_ID like", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdNotLike(String value) {

            addCriterion("CARRIER_ID not like", value, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdIn(List<String> values) {

            addCriterion("CARRIER_ID in", values, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdNotIn(List<String> values) {

            addCriterion("CARRIER_ID not in", values, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdBetween(String value1, String value2) {

            addCriterion("CARRIER_ID between", value1, value2, "carrierId");
            return (Criteria) this;
        }

        public Criteria andCarrierIdNotBetween(String value1, String value2) {

            addCriterion("CARRIER_ID not between", value1, value2, "carrierId");
            return (Criteria) this;
        }

        public Criteria andPatternIdIsNull() {

            addCriterion("PATTERN_ID is null");
            return (Criteria) this;
        }

        public Criteria andPatternIdIsNotNull() {

            addCriterion("PATTERN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPatternIdEqualTo(String value) {

            addCriterion("PATTERN_ID =", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdNotEqualTo(String value) {

            addCriterion("PATTERN_ID <>", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdGreaterThan(String value) {

            addCriterion("PATTERN_ID >", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdGreaterThanOrEqualTo(String value) {

            addCriterion("PATTERN_ID >=", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdLessThan(String value) {

            addCriterion("PATTERN_ID <", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdLessThanOrEqualTo(String value) {

            addCriterion("PATTERN_ID <=", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdLike(String value) {

            addCriterion("PATTERN_ID like", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdNotLike(String value) {

            addCriterion("PATTERN_ID not like", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdIn(List<String> values) {

            addCriterion("PATTERN_ID in", values, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdNotIn(List<String> values) {

            addCriterion("PATTERN_ID not in", values, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdBetween(String value1, String value2) {

            addCriterion("PATTERN_ID between", value1, value2, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdNotBetween(String value1, String value2) {

            addCriterion("PATTERN_ID not between", value1, value2, "patternId");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {

            addCriterion("ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {

            addCriterion("ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(Short value) {

            addCriterion("ORDER_NO =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(Short value) {

            addCriterion("ORDER_NO <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(Short value) {

            addCriterion("ORDER_NO >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(Short value) {

            addCriterion("ORDER_NO >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(Short value) {

            addCriterion("ORDER_NO <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(Short value) {

            addCriterion("ORDER_NO <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<Short> values) {

            addCriterion("ORDER_NO in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<Short> values) {

            addCriterion("ORDER_NO not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(Short value1, Short value2) {

            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(Short value1, Short value2) {

            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andInitialOrderNoIsNull() {
            addCriterion("INITIAL_ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andInitialOrderNoIsNotNull() {
            addCriterion("INITIAL_ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andInitialOrderNoEqualTo(Short value) {
            addCriterion("INITIAL_ORDER_NO =", value, "initialOrderNo");
            return (Criteria) this;
        }

        public Criteria andInitialOrderNoNotEqualTo(Short value) {
            addCriterion("INITIAL_ORDER_NO <>", value, "initialOrderNo");
            return (Criteria) this;
        }

        public Criteria andInitialOrderNoGreaterThan(Short value) {
            addCriterion("INITIAL_ORDER_NO >", value, "initialOrderNo");
            return (Criteria) this;
        }

        public Criteria andInitialOrderNoGreaterThanOrEqualTo(Short value) {
            addCriterion("INITIAL_ORDER_NO >=", value, "initialOrderNo");
            return (Criteria) this;
        }

        public Criteria andInitialOrderNoLessThan(Short value) {
            addCriterion("INITIAL_ORDER_NO <", value, "initialOrderNo");
            return (Criteria) this;
        }

        public Criteria andInitialOrderNoLessThanOrEqualTo(Short value) {
            addCriterion("INITIAL_ORDER_NO <=", value, "initialOrderNo");
            return (Criteria) this;
        }

        public Criteria andInitialOrderNoIn(List<Short> values) {
            addCriterion("INITIAL_ORDER_NO in", values, "initialOrderNo");
            return (Criteria) this;
        }

        public Criteria andInitialOrderNoNotIn(List<Short> values) {
            addCriterion("INITIAL_ORDER_NO not in", values, "initialOrderNo");
            return (Criteria) this;
        }

        public Criteria andInitialOrderNoBetween(Short value1, Short value2) {
            addCriterion("INITIAL_ORDER_NO between", value1, value2, "initialOrderNo");
            return (Criteria) this;
        }

        public Criteria andInitialOrderNoNotBetween(Short value1, Short value2) {
            addCriterion("INITIAL_ORDER_NO not between", value1, value2, "initialOrderNo");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("PRIORITY is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {

            addCriterion("PRIORITY is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Short value) {

            addCriterion("PRIORITY =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Short value) {

            addCriterion("PRIORITY <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Short value) {

            addCriterion("PRIORITY >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Short value) {

            addCriterion("PRIORITY >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Short value) {

            addCriterion("PRIORITY <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Short value) {

            addCriterion("PRIORITY <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Short> values) {

            addCriterion("PRIORITY in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Short> values) {

            addCriterion("PRIORITY not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Short value1, Short value2) {

            addCriterion("PRIORITY between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Short value1, Short value2) {

            addCriterion("PRIORITY not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {

            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {

            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {

            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {

            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {

            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {

            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {

            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {

            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {

            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {

            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {

            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {

            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTransCountIsNull() {
            addCriterion("TRANS_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andTransCountIsNotNull() {
            addCriterion("TRANS_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTransCountEqualTo(Integer value) {
            addCriterion("TRANS_COUNT =", value, "transCount");
            return (Criteria) this;
        }

        public Criteria andTransCountNotEqualTo(Integer value) {
            addCriterion("TRANS_COUNT <>", value, "transCount");
            return (Criteria) this;
        }

        public Criteria andTransCountGreaterThan(Integer value) {
            addCriterion("TRANS_COUNT >", value, "transCount");
            return (Criteria) this;
        }

        public Criteria andTransCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("TRANS_COUNT >=", value, "transCount");
            return (Criteria) this;
        }

        public Criteria andTransCountLessThan(Integer value) {
            addCriterion("TRANS_COUNT <", value, "transCount");
            return (Criteria) this;
        }

        public Criteria andTransCountLessThanOrEqualTo(Integer value) {
            addCriterion("TRANS_COUNT <=", value, "transCount");
            return (Criteria) this;
        }

        public Criteria andTransCountIn(List<Integer> values) {
            addCriterion("TRANS_COUNT in", values, "transCount");
            return (Criteria) this;
        }

        public Criteria andTransCountNotIn(List<Integer> values) {
            addCriterion("TRANS_COUNT not in", values, "transCount");
            return (Criteria) this;
        }

        public Criteria andTransCountBetween(Integer value1, Integer value2) {
            addCriterion("TRANS_COUNT between", value1, value2, "transCount");
            return (Criteria) this;
        }

        public Criteria andTransCountNotBetween(Integer value1, Integer value2) {
            addCriterion("TRANS_COUNT not between", value1, value2, "transCount");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdIsNull() {
            addCriterion("LAST_EQP_ID is null");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdIsNotNull() {
            addCriterion("LAST_EQP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdEqualTo(String value) {
            addCriterion("LAST_EQP_ID =", value, "lastEqpId");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdNotEqualTo(String value) {
            addCriterion("LAST_EQP_ID <>", value, "lastEqpId");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdGreaterThan(String value) {
            addCriterion("LAST_EQP_ID >", value, "lastEqpId");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_EQP_ID >=", value, "lastEqpId");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdLessThan(String value) {
            addCriterion("LAST_EQP_ID <", value, "lastEqpId");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdLessThanOrEqualTo(String value) {
            addCriterion("LAST_EQP_ID <=", value, "lastEqpId");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdLike(String value) {
            addCriterion("LAST_EQP_ID like", value, "lastEqpId");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdNotLike(String value) {
            addCriterion("LAST_EQP_ID not like", value, "lastEqpId");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdIn(List<String> values) {
            addCriterion("LAST_EQP_ID in", values, "lastEqpId");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdNotIn(List<String> values) {
            addCriterion("LAST_EQP_ID not in", values, "lastEqpId");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdBetween(String value1, String value2) {
            addCriterion("LAST_EQP_ID between", value1, value2, "lastEqpId");
            return (Criteria) this;
        }

        public Criteria andLastEqpIdNotBetween(String value1, String value2) {
            addCriterion("LAST_EQP_ID not between", value1, value2, "lastEqpId");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocIsNull() {
            addCriterion("LAST_EQP_LOC is null");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocIsNotNull() {
            addCriterion("LAST_EQP_LOC is not null");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocEqualTo(String value) {
            addCriterion("LAST_EQP_LOC =", value, "lastEqpLoc");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocNotEqualTo(String value) {
            addCriterion("LAST_EQP_LOC <>", value, "lastEqpLoc");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocGreaterThan(String value) {
            addCriterion("LAST_EQP_LOC >", value, "lastEqpLoc");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_EQP_LOC >=", value, "lastEqpLoc");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocLessThan(String value) {
            addCriterion("LAST_EQP_LOC <", value, "lastEqpLoc");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocLessThanOrEqualTo(String value) {
            addCriterion("LAST_EQP_LOC <=", value, "lastEqpLoc");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocLike(String value) {
            addCriterion("LAST_EQP_LOC like", value, "lastEqpLoc");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocNotLike(String value) {
            addCriterion("LAST_EQP_LOC not like", value, "lastEqpLoc");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocIn(List<String> values) {
            addCriterion("LAST_EQP_LOC in", values, "lastEqpLoc");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocNotIn(List<String> values) {
            addCriterion("LAST_EQP_LOC not in", values, "lastEqpLoc");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocBetween(String value1, String value2) {
            addCriterion("LAST_EQP_LOC between", value1, value2, "lastEqpLoc");
            return (Criteria) this;
        }

        public Criteria andLastEqpLocNotBetween(String value1, String value2) {
            addCriterion("LAST_EQP_LOC not between", value1, value2, "lastEqpLoc");
            return (Criteria) this;
        }

        public Criteria andWaitTimeIsNull() {
            addCriterion("WAIT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andWaitTimeIsNotNull() {
            addCriterion("WAIT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andWaitTimeEqualTo(Short value) {
            addCriterion("WAIT_TIME =", value, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeNotEqualTo(Short value) {
            addCriterion("WAIT_TIME <>", value, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeGreaterThan(Short value) {
            addCriterion("WAIT_TIME >", value, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeGreaterThanOrEqualTo(Short value) {
            addCriterion("WAIT_TIME >=", value, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeLessThan(Short value) {
            addCriterion("WAIT_TIME <", value, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeLessThanOrEqualTo(Short value) {
            addCriterion("WAIT_TIME <=", value, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeIn(List<Short> values) {
            addCriterion("WAIT_TIME in", values, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeNotIn(List<Short> values) {
            addCriterion("WAIT_TIME not in", values, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeBetween(Short value1, Short value2) {
            addCriterion("WAIT_TIME between", value1, value2, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeNotBetween(Short value1, Short value2) {
            addCriterion("WAIT_TIME not between", value1, value2, "waitTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table EXERCISE
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {

            return condition;
        }

        public Object getValue() {

            return value;
        }

        public Object getSecondValue() {

            return secondValue;
        }

        public boolean isNoValue() {

            return noValue;
        }

        public boolean isSingleValue() {

            return singleValue;
        }

        public boolean isBetweenValue() {

            return betweenValue;
        }

        public boolean isListValue() {

            return listValue;
        }

        public String getTypeHandler() {

            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table EXERCISE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}
