package net.muratec.mcs.model;

import java.util.ArrayList;
import java.util.List;

public class ExercisePatternExample {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    public ExercisePatternExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {

        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    public String getOrderByClause() {

        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {

        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    public boolean isDistinct() {

        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {

        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    public void or(Criteria criteria) {

        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    public Criteria or() {

        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    public Criteria createCriteria() {

        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {

        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    public void clear() {

        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {

            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {

            return criteria;
        }

        public List<Criterion> getCriteria() {

            return criteria;
        }

        protected void addCriterion(String condition) {

            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {

            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {

            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPatternIdIsNull() {

            addCriterion("PATTERN_ID is null");
            return (Criteria) this;
        }

        public Criteria andPatternIdIsNotNull() {

            addCriterion("PATTERN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPatternIdEqualTo(String value) {

            addCriterion("PATTERN_ID =", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdNotEqualTo(String value) {

            addCriterion("PATTERN_ID <>", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdGreaterThan(String value) {

            addCriterion("PATTERN_ID >", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdGreaterThanOrEqualTo(String value) {

            addCriterion("PATTERN_ID >=", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdLessThan(String value) {

            addCriterion("PATTERN_ID <", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdLessThanOrEqualTo(String value) {

            addCriterion("PATTERN_ID <=", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdLike(String value) {

            addCriterion("PATTERN_ID like", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdNotLike(String value) {

            addCriterion("PATTERN_ID not like", value, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdIn(List<String> values) {

            addCriterion("PATTERN_ID in", values, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdNotIn(List<String> values) {

            addCriterion("PATTERN_ID not in", values, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdBetween(String value1, String value2) {

            addCriterion("PATTERN_ID between", value1, value2, "patternId");
            return (Criteria) this;
        }

        public Criteria andPatternIdNotBetween(String value1, String value2) {

            addCriterion("PATTERN_ID not between", value1, value2, "patternId");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {

            addCriterion("ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {

            addCriterion("ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(Short value) {

            addCriterion("ORDER_NO =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(Short value) {

            addCriterion("ORDER_NO <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(Short value) {

            addCriterion("ORDER_NO >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(Short value) {

            addCriterion("ORDER_NO >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(Short value) {

            addCriterion("ORDER_NO <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(Short value) {

            addCriterion("ORDER_NO <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<Short> values) {

            addCriterion("ORDER_NO in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<Short> values) {

            addCriterion("ORDER_NO not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(Short value1, Short value2) {

            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(Short value1, Short value2) {

            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdIsNull() {

            addCriterion("DST_GROUP_ID is null");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdIsNotNull() {

            addCriterion("DST_GROUP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdEqualTo(String value) {

            addCriterion("DST_GROUP_ID =", value, "dstGroupId");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdNotEqualTo(String value) {

            addCriterion("DST_GROUP_ID <>", value, "dstGroupId");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdGreaterThan(String value) {

            addCriterion("DST_GROUP_ID >", value, "dstGroupId");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdGreaterThanOrEqualTo(String value) {

            addCriterion("DST_GROUP_ID >=", value, "dstGroupId");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdLessThan(String value) {

            addCriterion("DST_GROUP_ID <", value, "dstGroupId");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdLessThanOrEqualTo(String value) {

            addCriterion("DST_GROUP_ID <=", value, "dstGroupId");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdLike(String value) {

            addCriterion("DST_GROUP_ID like", value, "dstGroupId");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdNotLike(String value) {

            addCriterion("DST_GROUP_ID not like", value, "dstGroupId");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdIn(List<String> values) {

            addCriterion("DST_GROUP_ID in", values, "dstGroupId");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdNotIn(List<String> values) {

            addCriterion("DST_GROUP_ID not in", values, "dstGroupId");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdBetween(String value1, String value2) {

            addCriterion("DST_GROUP_ID between", value1, value2, "dstGroupId");
            return (Criteria) this;
        }

        public Criteria andDstGroupIdNotBetween(String value1, String value2) {

            addCriterion("DST_GROUP_ID not between", value1, value2, "dstGroupId");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdIsNull() {
            addCriterion("DST_EQP_ID is null");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdIsNotNull() {
            addCriterion("DST_EQP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdEqualTo(String value) {
            addCriterion("DST_EQP_ID =", value, "dstEqpId");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdNotEqualTo(String value) {
            addCriterion("DST_EQP_ID <>", value, "dstEqpId");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdGreaterThan(String value) {
            addCriterion("DST_EQP_ID >", value, "dstEqpId");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdGreaterThanOrEqualTo(String value) {
            addCriterion("DST_EQP_ID >=", value, "dstEqpId");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdLessThan(String value) {
            addCriterion("DST_EQP_ID <", value, "dstEqpId");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdLessThanOrEqualTo(String value) {
            addCriterion("DST_EQP_ID <=", value, "dstEqpId");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdLike(String value) {
            addCriterion("DST_EQP_ID like", value, "dstEqpId");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdNotLike(String value) {
            addCriterion("DST_EQP_ID not like", value, "dstEqpId");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdIn(List<String> values) {
            addCriterion("DST_EQP_ID in", values, "dstEqpId");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdNotIn(List<String> values) {
            addCriterion("DST_EQP_ID not in", values, "dstEqpId");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdBetween(String value1, String value2) {
            addCriterion("DST_EQP_ID between", value1, value2, "dstEqpId");
            return (Criteria) this;
        }

        public Criteria andDstEqpIdNotBetween(String value1, String value2) {
            addCriterion("DST_EQP_ID not between", value1, value2, "dstEqpId");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocIsNull() {
            addCriterion("DST_EQP_LOC is null");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocIsNotNull() {
            addCriterion("DST_EQP_LOC is not null");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocEqualTo(String value) {
            addCriterion("DST_EQP_LOC =", value, "dstEqpLoc");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocNotEqualTo(String value) {
            addCriterion("DST_EQP_LOC <>", value, "dstEqpLoc");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocGreaterThan(String value) {
            addCriterion("DST_EQP_LOC >", value, "dstEqpLoc");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocGreaterThanOrEqualTo(String value) {
            addCriterion("DST_EQP_LOC >=", value, "dstEqpLoc");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocLessThan(String value) {
            addCriterion("DST_EQP_LOC <", value, "dstEqpLoc");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocLessThanOrEqualTo(String value) {
            addCriterion("DST_EQP_LOC <=", value, "dstEqpLoc");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocLike(String value) {
            addCriterion("DST_EQP_LOC like", value, "dstEqpLoc");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocNotLike(String value) {
            addCriterion("DST_EQP_LOC not like", value, "dstEqpLoc");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocIn(List<String> values) {
            addCriterion("DST_EQP_LOC in", values, "dstEqpLoc");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocNotIn(List<String> values) {
            addCriterion("DST_EQP_LOC not in", values, "dstEqpLoc");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocBetween(String value1, String value2) {
            addCriterion("DST_EQP_LOC between", value1, value2, "dstEqpLoc");
            return (Criteria) this;
        }

        public Criteria andDstEqpLocNotBetween(String value1, String value2) {
            addCriterion("DST_EQP_LOC not between", value1, value2, "dstEqpLoc");
            return (Criteria) this;
        }

        public Criteria andDstLocTypeIsNull() {
            addCriterion("DST_LOC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDstLocTypeIsNotNull() {
            addCriterion("DST_LOC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDstLocTypeEqualTo(Short value) {
            addCriterion("DST_LOC_TYPE =", value, "dstLocType");
            return (Criteria) this;
        }

        public Criteria andDstLocTypeNotEqualTo(Short value) {
            addCriterion("DST_LOC_TYPE <>", value, "dstLocType");
            return (Criteria) this;
        }

        public Criteria andDstLocTypeGreaterThan(Short value) {
            addCriterion("DST_LOC_TYPE >", value, "dstLocType");
            return (Criteria) this;
        }

        public Criteria andDstLocTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("DST_LOC_TYPE >=", value, "dstLocType");
            return (Criteria) this;
        }

        public Criteria andDstLocTypeLessThan(Short value) {
            addCriterion("DST_LOC_TYPE <", value, "dstLocType");
            return (Criteria) this;
        }

        public Criteria andDstLocTypeLessThanOrEqualTo(Short value) {
            addCriterion("DST_LOC_TYPE <=", value, "dstLocType");
            return (Criteria) this;
        }

        public Criteria andDstLocTypeIn(List<Short> values) {
            addCriterion("DST_LOC_TYPE in", values, "dstLocType");
            return (Criteria) this;
        }

        public Criteria andDstLocTypeNotIn(List<Short> values) {
            addCriterion("DST_LOC_TYPE not in", values, "dstLocType");
            return (Criteria) this;
        }

        public Criteria andDstLocTypeBetween(Short value1, Short value2) {
            addCriterion("DST_LOC_TYPE between", value1, value2, "dstLocType");
            return (Criteria) this;
        }

        public Criteria andDstLocTypeNotBetween(Short value1, Short value2) {
            addCriterion("DST_LOC_TYPE not between", value1, value2, "dstLocType");
            return (Criteria) this;
        }

        public Criteria andWaitTimeIsNull() {

            addCriterion("WAIT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andWaitTimeIsNotNull() {

            addCriterion("WAIT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andWaitTimeEqualTo(Short value) {

            addCriterion("WAIT_TIME =", value, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeNotEqualTo(Short value) {

            addCriterion("WAIT_TIME <>", value, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeGreaterThan(Short value) {

            addCriterion("WAIT_TIME >", value, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeGreaterThanOrEqualTo(Short value) {

            addCriterion("WAIT_TIME >=", value, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeLessThan(Short value) {

            addCriterion("WAIT_TIME <", value, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeLessThanOrEqualTo(Short value) {

            addCriterion("WAIT_TIME <=", value, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeIn(List<Short> values) {

            addCriterion("WAIT_TIME in", values, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeNotIn(List<Short> values) {

            addCriterion("WAIT_TIME not in", values, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeBetween(Short value1, Short value2) {

            addCriterion("WAIT_TIME between", value1, value2, "waitTime");
            return (Criteria) this;
        }

        public Criteria andWaitTimeNotBetween(Short value1, Short value2) {

            addCriterion("WAIT_TIME not between", value1, value2, "waitTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table EXERCISE_PATTERN
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {

            return condition;
        }

        public Object getValue() {

            return value;
        }

        public Object getSecondValue() {

            return secondValue;
        }

        public boolean isNoValue() {

            return noValue;
        }

        public boolean isSingleValue() {

            return singleValue;
        }

        public boolean isBetweenValue() {

            return betweenValue;
        }

        public boolean isListValue() {

            return listValue;
        }

        public String getTypeHandler() {

            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * EXERCISE_PATTERN
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 14 10:45:44 JST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}
