package net.muratec.mcs.model;

import java.util.ArrayList;
import java.util.List;

public class HostAlarmDefineExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	public HostAlarmDefineExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andServerNameIsNull() {
			addCriterion("SERVER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andServerNameIsNotNull() {
			addCriterion("SERVER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andServerNameEqualTo(String value) {
			addCriterion("SERVER_NAME =", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameNotEqualTo(String value) {
			addCriterion("SERVER_NAME <>", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameGreaterThan(String value) {
			addCriterion("SERVER_NAME >", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameGreaterThanOrEqualTo(String value) {
			addCriterion("SERVER_NAME >=", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameLessThan(String value) {
			addCriterion("SERVER_NAME <", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameLessThanOrEqualTo(String value) {
			addCriterion("SERVER_NAME <=", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameLike(String value) {
			addCriterion("SERVER_NAME like", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameNotLike(String value) {
			addCriterion("SERVER_NAME not like", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameIn(List<String> values) {
			addCriterion("SERVER_NAME in", values, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameNotIn(List<String> values) {
			addCriterion("SERVER_NAME not in", values, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameBetween(String value1, String value2) {
			addCriterion("SERVER_NAME between", value1, value2, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameNotBetween(String value1, String value2) {
			addCriterion("SERVER_NAME not between", value1, value2, "serverName");
			return (Criteria) this;
		}

		public Criteria andFactoryIdIsNull() {
			addCriterion("FACTORY_ID is null");
			return (Criteria) this;
		}

		public Criteria andFactoryIdIsNotNull() {
			addCriterion("FACTORY_ID is not null");
			return (Criteria) this;
		}

		public Criteria andFactoryIdEqualTo(String value) {
			addCriterion("FACTORY_ID =", value, "factoryId");
			return (Criteria) this;
		}

		public Criteria andFactoryIdNotEqualTo(String value) {
			addCriterion("FACTORY_ID <>", value, "factoryId");
			return (Criteria) this;
		}

		public Criteria andFactoryIdGreaterThan(String value) {
			addCriterion("FACTORY_ID >", value, "factoryId");
			return (Criteria) this;
		}

		public Criteria andFactoryIdGreaterThanOrEqualTo(String value) {
			addCriterion("FACTORY_ID >=", value, "factoryId");
			return (Criteria) this;
		}

		public Criteria andFactoryIdLessThan(String value) {
			addCriterion("FACTORY_ID <", value, "factoryId");
			return (Criteria) this;
		}

		public Criteria andFactoryIdLessThanOrEqualTo(String value) {
			addCriterion("FACTORY_ID <=", value, "factoryId");
			return (Criteria) this;
		}

		public Criteria andFactoryIdLike(String value) {
			addCriterion("FACTORY_ID like", value, "factoryId");
			return (Criteria) this;
		}

		public Criteria andFactoryIdNotLike(String value) {
			addCriterion("FACTORY_ID not like", value, "factoryId");
			return (Criteria) this;
		}

		public Criteria andFactoryIdIn(List<String> values) {
			addCriterion("FACTORY_ID in", values, "factoryId");
			return (Criteria) this;
		}

		public Criteria andFactoryIdNotIn(List<String> values) {
			addCriterion("FACTORY_ID not in", values, "factoryId");
			return (Criteria) this;
		}

		public Criteria andFactoryIdBetween(String value1, String value2) {
			addCriterion("FACTORY_ID between", value1, value2, "factoryId");
			return (Criteria) this;
		}

		public Criteria andFactoryIdNotBetween(String value1, String value2) {
			addCriterion("FACTORY_ID not between", value1, value2, "factoryId");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdIsNull() {
			addCriterion("SUBSYSTEM_ID is null");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdIsNotNull() {
			addCriterion("SUBSYSTEM_ID is not null");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdEqualTo(String value) {
			addCriterion("SUBSYSTEM_ID =", value, "subsystemId");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdNotEqualTo(String value) {
			addCriterion("SUBSYSTEM_ID <>", value, "subsystemId");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdGreaterThan(String value) {
			addCriterion("SUBSYSTEM_ID >", value, "subsystemId");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdGreaterThanOrEqualTo(String value) {
			addCriterion("SUBSYSTEM_ID >=", value, "subsystemId");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdLessThan(String value) {
			addCriterion("SUBSYSTEM_ID <", value, "subsystemId");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdLessThanOrEqualTo(String value) {
			addCriterion("SUBSYSTEM_ID <=", value, "subsystemId");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdLike(String value) {
			addCriterion("SUBSYSTEM_ID like", value, "subsystemId");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdNotLike(String value) {
			addCriterion("SUBSYSTEM_ID not like", value, "subsystemId");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdIn(List<String> values) {
			addCriterion("SUBSYSTEM_ID in", values, "subsystemId");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdNotIn(List<String> values) {
			addCriterion("SUBSYSTEM_ID not in", values, "subsystemId");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdBetween(String value1, String value2) {
			addCriterion("SUBSYSTEM_ID between", value1, value2, "subsystemId");
			return (Criteria) this;
		}

		public Criteria andSubsystemIdNotBetween(String value1, String value2) {
			addCriterion("SUBSYSTEM_ID not between", value1, value2, "subsystemId");
			return (Criteria) this;
		}

		public Criteria andUnknownIdIsNull() {
			addCriterion("UNKNOWN_ID is null");
			return (Criteria) this;
		}

		public Criteria andUnknownIdIsNotNull() {
			addCriterion("UNKNOWN_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUnknownIdEqualTo(String value) {
			addCriterion("UNKNOWN_ID =", value, "unknownId");
			return (Criteria) this;
		}

		public Criteria andUnknownIdNotEqualTo(String value) {
			addCriterion("UNKNOWN_ID <>", value, "unknownId");
			return (Criteria) this;
		}

		public Criteria andUnknownIdGreaterThan(String value) {
			addCriterion("UNKNOWN_ID >", value, "unknownId");
			return (Criteria) this;
		}

		public Criteria andUnknownIdGreaterThanOrEqualTo(String value) {
			addCriterion("UNKNOWN_ID >=", value, "unknownId");
			return (Criteria) this;
		}

		public Criteria andUnknownIdLessThan(String value) {
			addCriterion("UNKNOWN_ID <", value, "unknownId");
			return (Criteria) this;
		}

		public Criteria andUnknownIdLessThanOrEqualTo(String value) {
			addCriterion("UNKNOWN_ID <=", value, "unknownId");
			return (Criteria) this;
		}

		public Criteria andUnknownIdLike(String value) {
			addCriterion("UNKNOWN_ID like", value, "unknownId");
			return (Criteria) this;
		}

		public Criteria andUnknownIdNotLike(String value) {
			addCriterion("UNKNOWN_ID not like", value, "unknownId");
			return (Criteria) this;
		}

		public Criteria andUnknownIdIn(List<String> values) {
			addCriterion("UNKNOWN_ID in", values, "unknownId");
			return (Criteria) this;
		}

		public Criteria andUnknownIdNotIn(List<String> values) {
			addCriterion("UNKNOWN_ID not in", values, "unknownId");
			return (Criteria) this;
		}

		public Criteria andUnknownIdBetween(String value1, String value2) {
			addCriterion("UNKNOWN_ID between", value1, value2, "unknownId");
			return (Criteria) this;
		}

		public Criteria andUnknownIdNotBetween(String value1, String value2) {
			addCriterion("UNKNOWN_ID not between", value1, value2, "unknownId");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeIsNull() {
			addCriterion("UNKNOWN_EQP_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeIsNotNull() {
			addCriterion("UNKNOWN_EQP_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeEqualTo(String value) {
			addCriterion("UNKNOWN_EQP_TYPE =", value, "unknownEqpType");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeNotEqualTo(String value) {
			addCriterion("UNKNOWN_EQP_TYPE <>", value, "unknownEqpType");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeGreaterThan(String value) {
			addCriterion("UNKNOWN_EQP_TYPE >", value, "unknownEqpType");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeGreaterThanOrEqualTo(String value) {
			addCriterion("UNKNOWN_EQP_TYPE >=", value, "unknownEqpType");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeLessThan(String value) {
			addCriterion("UNKNOWN_EQP_TYPE <", value, "unknownEqpType");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeLessThanOrEqualTo(String value) {
			addCriterion("UNKNOWN_EQP_TYPE <=", value, "unknownEqpType");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeLike(String value) {
			addCriterion("UNKNOWN_EQP_TYPE like", value, "unknownEqpType");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeNotLike(String value) {
			addCriterion("UNKNOWN_EQP_TYPE not like", value, "unknownEqpType");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeIn(List<String> values) {
			addCriterion("UNKNOWN_EQP_TYPE in", values, "unknownEqpType");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeNotIn(List<String> values) {
			addCriterion("UNKNOWN_EQP_TYPE not in", values, "unknownEqpType");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeBetween(String value1, String value2) {
			addCriterion("UNKNOWN_EQP_TYPE between", value1, value2, "unknownEqpType");
			return (Criteria) this;
		}

		public Criteria andUnknownEqpTypeNotBetween(String value1, String value2) {
			addCriterion("UNKNOWN_EQP_TYPE not between", value1, value2, "unknownEqpType");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectSubjectIsNull() {
			addCriterion("UNKNOWN_SELECT_SUBJECT is null");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectSubjectIsNotNull() {
			addCriterion("UNKNOWN_SELECT_SUBJECT is not null");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectSubjectEqualTo(Short value) {
			addCriterion("UNKNOWN_SELECT_SUBJECT =", value, "unknownSelectSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectSubjectNotEqualTo(Short value) {
			addCriterion("UNKNOWN_SELECT_SUBJECT <>", value, "unknownSelectSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectSubjectGreaterThan(Short value) {
			addCriterion("UNKNOWN_SELECT_SUBJECT >", value, "unknownSelectSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectSubjectGreaterThanOrEqualTo(Short value) {
			addCriterion("UNKNOWN_SELECT_SUBJECT >=", value, "unknownSelectSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectSubjectLessThan(Short value) {
			addCriterion("UNKNOWN_SELECT_SUBJECT <", value, "unknownSelectSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectSubjectLessThanOrEqualTo(Short value) {
			addCriterion("UNKNOWN_SELECT_SUBJECT <=", value, "unknownSelectSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectSubjectIn(List<Short> values) {
			addCriterion("UNKNOWN_SELECT_SUBJECT in", values, "unknownSelectSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectSubjectNotIn(List<Short> values) {
			addCriterion("UNKNOWN_SELECT_SUBJECT not in", values, "unknownSelectSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectSubjectBetween(Short value1, Short value2) {
			addCriterion("UNKNOWN_SELECT_SUBJECT between", value1, value2, "unknownSelectSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectSubjectNotBetween(Short value1, Short value2) {
			addCriterion("UNKNOWN_SELECT_SUBJECT not between", value1, value2, "unknownSelectSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectIsNull() {
			addCriterion("UNKNOWN_HOST_SUBJECT is null");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectIsNotNull() {
			addCriterion("UNKNOWN_HOST_SUBJECT is not null");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectEqualTo(String value) {
			addCriterion("UNKNOWN_HOST_SUBJECT =", value, "unknownHostSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectNotEqualTo(String value) {
			addCriterion("UNKNOWN_HOST_SUBJECT <>", value, "unknownHostSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectGreaterThan(String value) {
			addCriterion("UNKNOWN_HOST_SUBJECT >", value, "unknownHostSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectGreaterThanOrEqualTo(String value) {
			addCriterion("UNKNOWN_HOST_SUBJECT >=", value, "unknownHostSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectLessThan(String value) {
			addCriterion("UNKNOWN_HOST_SUBJECT <", value, "unknownHostSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectLessThanOrEqualTo(String value) {
			addCriterion("UNKNOWN_HOST_SUBJECT <=", value, "unknownHostSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectLike(String value) {
			addCriterion("UNKNOWN_HOST_SUBJECT like", value, "unknownHostSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectNotLike(String value) {
			addCriterion("UNKNOWN_HOST_SUBJECT not like", value, "unknownHostSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectIn(List<String> values) {
			addCriterion("UNKNOWN_HOST_SUBJECT in", values, "unknownHostSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectNotIn(List<String> values) {
			addCriterion("UNKNOWN_HOST_SUBJECT not in", values, "unknownHostSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectBetween(String value1, String value2) {
			addCriterion("UNKNOWN_HOST_SUBJECT between", value1, value2, "unknownHostSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownHostSubjectNotBetween(String value1, String value2) {
			addCriterion("UNKNOWN_HOST_SUBJECT not between", value1, value2, "unknownHostSubject");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectContentIsNull() {
			addCriterion("UNKNOWN_SELECT_CONTENT is null");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectContentIsNotNull() {
			addCriterion("UNKNOWN_SELECT_CONTENT is not null");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectContentEqualTo(Short value) {
			addCriterion("UNKNOWN_SELECT_CONTENT =", value, "unknownSelectContent");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectContentNotEqualTo(Short value) {
			addCriterion("UNKNOWN_SELECT_CONTENT <>", value, "unknownSelectContent");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectContentGreaterThan(Short value) {
			addCriterion("UNKNOWN_SELECT_CONTENT >", value, "unknownSelectContent");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectContentGreaterThanOrEqualTo(Short value) {
			addCriterion("UNKNOWN_SELECT_CONTENT >=", value, "unknownSelectContent");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectContentLessThan(Short value) {
			addCriterion("UNKNOWN_SELECT_CONTENT <", value, "unknownSelectContent");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectContentLessThanOrEqualTo(Short value) {
			addCriterion("UNKNOWN_SELECT_CONTENT <=", value, "unknownSelectContent");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectContentIn(List<Short> values) {
			addCriterion("UNKNOWN_SELECT_CONTENT in", values, "unknownSelectContent");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectContentNotIn(List<Short> values) {
			addCriterion("UNKNOWN_SELECT_CONTENT not in", values, "unknownSelectContent");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectContentBetween(Short value1, Short value2) {
			addCriterion("UNKNOWN_SELECT_CONTENT between", value1, value2, "unknownSelectContent");
			return (Criteria) this;
		}

		public Criteria andUnknownSelectContentNotBetween(Short value1, Short value2) {
			addCriterion("UNKNOWN_SELECT_CONTENT not between", value1, value2, "unknownSelectContent");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentIsNull() {
			addCriterion("UNKNOWN_HOST_CONTENT is null");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentIsNotNull() {
			addCriterion("UNKNOWN_HOST_CONTENT is not null");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentEqualTo(String value) {
			addCriterion("UNKNOWN_HOST_CONTENT =", value, "unknownHostContent");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentNotEqualTo(String value) {
			addCriterion("UNKNOWN_HOST_CONTENT <>", value, "unknownHostContent");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentGreaterThan(String value) {
			addCriterion("UNKNOWN_HOST_CONTENT >", value, "unknownHostContent");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentGreaterThanOrEqualTo(String value) {
			addCriterion("UNKNOWN_HOST_CONTENT >=", value, "unknownHostContent");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentLessThan(String value) {
			addCriterion("UNKNOWN_HOST_CONTENT <", value, "unknownHostContent");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentLessThanOrEqualTo(String value) {
			addCriterion("UNKNOWN_HOST_CONTENT <=", value, "unknownHostContent");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentLike(String value) {
			addCriterion("UNKNOWN_HOST_CONTENT like", value, "unknownHostContent");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentNotLike(String value) {
			addCriterion("UNKNOWN_HOST_CONTENT not like", value, "unknownHostContent");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentIn(List<String> values) {
			addCriterion("UNKNOWN_HOST_CONTENT in", values, "unknownHostContent");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentNotIn(List<String> values) {
			addCriterion("UNKNOWN_HOST_CONTENT not in", values, "unknownHostContent");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentBetween(String value1, String value2) {
			addCriterion("UNKNOWN_HOST_CONTENT between", value1, value2, "unknownHostContent");
			return (Criteria) this;
		}

		public Criteria andUnknownHostContentNotBetween(String value1, String value2) {
			addCriterion("UNKNOWN_HOST_CONTENT not between", value1, value2, "unknownHostContent");
			return (Criteria) this;
		}

		public Criteria andUnknownEnableIsNull() {
			addCriterion("UNKNOWN_ENABLE is null");
			return (Criteria) this;
		}

		public Criteria andUnknownEnableIsNotNull() {
			addCriterion("UNKNOWN_ENABLE is not null");
			return (Criteria) this;
		}

		public Criteria andUnknownEnableEqualTo(Short value) {
			addCriterion("UNKNOWN_ENABLE =", value, "unknownEnable");
			return (Criteria) this;
		}

		public Criteria andUnknownEnableNotEqualTo(Short value) {
			addCriterion("UNKNOWN_ENABLE <>", value, "unknownEnable");
			return (Criteria) this;
		}

		public Criteria andUnknownEnableGreaterThan(Short value) {
			addCriterion("UNKNOWN_ENABLE >", value, "unknownEnable");
			return (Criteria) this;
		}

		public Criteria andUnknownEnableGreaterThanOrEqualTo(Short value) {
			addCriterion("UNKNOWN_ENABLE >=", value, "unknownEnable");
			return (Criteria) this;
		}

		public Criteria andUnknownEnableLessThan(Short value) {
			addCriterion("UNKNOWN_ENABLE <", value, "unknownEnable");
			return (Criteria) this;
		}

		public Criteria andUnknownEnableLessThanOrEqualTo(Short value) {
			addCriterion("UNKNOWN_ENABLE <=", value, "unknownEnable");
			return (Criteria) this;
		}

		public Criteria andUnknownEnableIn(List<Short> values) {
			addCriterion("UNKNOWN_ENABLE in", values, "unknownEnable");
			return (Criteria) this;
		}

		public Criteria andUnknownEnableNotIn(List<Short> values) {
			addCriterion("UNKNOWN_ENABLE not in", values, "unknownEnable");
			return (Criteria) this;
		}

		public Criteria andUnknownEnableBetween(Short value1, Short value2) {
			addCriterion("UNKNOWN_ENABLE between", value1, value2, "unknownEnable");
			return (Criteria) this;
		}

		public Criteria andUnknownEnableNotBetween(Short value1, Short value2) {
			addCriterion("UNKNOWN_ENABLE not between", value1, value2, "unknownEnable");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table HOST_ALARM_DEFINE
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HOST_ALARM_DEFINE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}