package net.muratec.mcs.model;

public class HostReportInfoKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HOST_REPORT_INFO.HOST_NAME
     * @mbg.generated
     */
    private String hostName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HOST_REPORT_INFO.TRANSACTION
     * @mbg.generated
     */
    private Short transaction;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HOST_REPORT_INFO.HOST_NAME
     * @return  the value of HOST_REPORT_INFO.HOST_NAME
     * @mbg.generated
     */
    public String getHostName() {

        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HOST_REPORT_INFO.HOST_NAME
     * @param hostName  the value for HOST_REPORT_INFO.HOST_NAME
     * @mbg.generated
     */
    public void setHostName(String hostName) {

        this.hostName = hostName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HOST_REPORT_INFO.TRANSACTION
     * @return  the value of HOST_REPORT_INFO.TRANSACTION
     * @mbg.generated
     */
    public Short getTransaction() {

        return transaction;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HOST_REPORT_INFO.TRANSACTION
     * @param transaction  the value for HOST_REPORT_INFO.TRANSACTION
     * @mbg.generated
     */
    public void setTransaction(Short transaction) {

        this.transaction = transaction;
    }
}
