package net.muratec.mcs.model;

import java.sql.Timestamp;

public class HostlogHistory {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HOSTLOG_HISTORY.TIME
     * @mbg.generated
     */
    private Timestamp time;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HOSTLOG_HISTORY.HOST_NAME
     * @mbg.generated
     */
    private String hostName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HOSTLOG_HISTORY.TRANSACTION_ID
     * @mbg.generated
     */
    private String transactionId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HOSTLOG_HISTORY.DIRECTION
     * @mbg.generated
     */
    private Short direction;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HOSTLOG_HISTORY.RES_SEC
     * @mbg.generated
     */
    private Integer resSec;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HOSTLOG_HISTORY.TIME
     * @return  the value of HOSTLOG_HISTORY.TIME
     * @mbg.generated
     */
    public Timestamp getTime() {

        return time;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HOSTLOG_HISTORY.TIME
     * @param time  the value for HOSTLOG_HISTORY.TIME
     * @mbg.generated
     */
    public void setTime(Timestamp time) {

        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HOSTLOG_HISTORY.HOST_NAME
     * @return  the value of HOSTLOG_HISTORY.HOST_NAME
     * @mbg.generated
     */
    public String getHostName() {

        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HOSTLOG_HISTORY.HOST_NAME
     * @param hostName  the value for HOSTLOG_HISTORY.HOST_NAME
     * @mbg.generated
     */
    public void setHostName(String hostName) {

        this.hostName = hostName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HOSTLOG_HISTORY.TRANSACTION_ID
     * @return  the value of HOSTLOG_HISTORY.TRANSACTION_ID
     * @mbg.generated
     */
    public String getTransactionId() {

        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HOSTLOG_HISTORY.TRANSACTION_ID
     * @param transactionId  the value for HOSTLOG_HISTORY.TRANSACTION_ID
     * @mbg.generated
     */
    public void setTransactionId(String transactionId) {

        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HOSTLOG_HISTORY.DIRECTION
     * @return  the value of HOSTLOG_HISTORY.DIRECTION
     * @mbg.generated
     */
    public Short getDirection() {

        return direction;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HOSTLOG_HISTORY.DRECTION
     * @param direction  the value for HOSTLOG_HISTORY.DIRECTION
     * @mbg.generated
     */
    public void setDirection(Short direction) {

        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HOSTLOG_HISTORY.RES_SEC
     * @return  the value of HOSTLOG_HISTORY.RES_SEC
     * @mbg.generated
     */
    public Integer getResSec() {

        return resSec;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HOSTLOG_HISTORY.RES_SEC
     * @param resSec  the value for HOSTLOG_HISTORY.RES_SEC
     * @mbg.generated
     */
    public void setResSec(Integer resSec) {

        this.resSec = resSec;
    }
}
