package net.muratec.mcs.model;

public class OhbZone extends OhbZoneKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB_ZONE.OHB_ZONE_NAME
     *
     * @mbg.generated
     */
    private String ohbZoneName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB_ZONE.TOTAL_SHELVES
     *
     * @mbg.generated
     */
    private Integer totalShelves;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB_ZONE.EMPTY_SHELVES
     *
     * @mbg.generated
     */
    private Integer emptyShelves;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB_ZONE.OHB_ZONE_NAME
     *
     * @return the value of OHB_ZONE.OHB_ZONE_NAME
     *
     * @mbg.generated
     */
    public String getOhbZoneName() {
        return ohbZoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB_ZONE.OHB_ZONE_NAME
     *
     * @param ohbZoneName the value for OHB_ZONE.OHB_ZONE_NAME
     *
     * @mbg.generated
     */
    public void setOhbZoneName(String ohbZoneName) {
        this.ohbZoneName = ohbZoneName == null ? null : ohbZoneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB_ZONE.TOTAL_SHELVES
     *
     * @return the value of OHB_ZONE.TOTAL_SHELVES
     *
     * @mbg.generated
     */
    public Integer getTotalShelves() {
        return totalShelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB_ZONE.TOTAL_SHELVES
     *
     * @param totalShelves the value for OHB_ZONE.TOTAL_SHELVES
     *
     * @mbg.generated
     */
    public void setTotalShelves(Integer totalShelves) {
        this.totalShelves = totalShelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB_ZONE.EMPTY_SHELVES
     *
     * @return the value of OHB_ZONE.EMPTY_SHELVES
     *
     * @mbg.generated
     */
    public Integer getEmptyShelves() {
        return emptyShelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB_ZONE.EMPTY_SHELVES
     *
     * @param emptyShelves the value for OHB_ZONE.EMPTY_SHELVES
     *
     * @mbg.generated
     */
    public void setEmptyShelves(Integer emptyShelves) {
        this.emptyShelves = emptyShelves;
    }
}