package net.muratec.mcs.model;

public class Vehicle extends VehicleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.VEHICLE_TYPE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    private String vehicleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.VEHICLE_STATE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    private String vehicleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.VEHICLE_ALARM_STATE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    private String vehicleAlarmState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.CURRENT_PORT_ID
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    private String currentPortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.TOTAL_OPE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    private Short totalOpe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.TOTAL_ERR
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    private Short totalErr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.INSTALLED_TIME
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    private String installedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.REMOVED_TIME
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    private String removedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.RTM_TSC_ID
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    private String rtmTscId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.VEHICLE_CARRIER_TYPE_ID
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    private String vehicleCarrierTypeId;
    
	// STD APL 2020.03.03 董 天津村研  MCSV4　GUI開発  Ver3.0 Rev.000 
    private String llcId;
    private String llcName;
    private String alarmText;
    private String vehicleKind;

    public String getLlcId() {
		return llcId;
	}

	public void setLlcId(String llcId) {
		this.llcId = llcId;
	}

	public String getLlcName() {
		return llcName;
	}

	public void setLlcName(String llcName) {
		this.llcName = llcName;
	}

	public String getAlarmText() {
		return alarmText;
	}

	public void setAlarmText(String alarmText) {
		this.alarmText = alarmText;
	}
	// END APL 2020.03.03 董 天津村研  MCSV4　GUI開発  Ver3.0 Rev.000 

	public String getVehicleKind() {
		return vehicleKind;
	}

	public void setVehicleKind(String vehicleKind) {
		this.vehicleKind = vehicleKind;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.VEHICLE_TYPE
     *
     * @return the value of VEHICLE.VEHICLE_TYPE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.VEHICLE_TYPE
     *
     * @param vehicleType the value for VEHICLE.VEHICLE_TYPE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType == null ? null : vehicleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.VEHICLE_STATE
     *
     * @return the value of VEHICLE.VEHICLE_STATE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public String getVehicleState() {
        return vehicleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.VEHICLE_STATE
     *
     * @param vehicleState the value for VEHICLE.VEHICLE_STATE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public void setVehicleState(String vehicleState) {
        this.vehicleState = vehicleState == null ? null : vehicleState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.VEHICLE_ALARM_STATE
     *
     * @return the value of VEHICLE.VEHICLE_ALARM_STATE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public String getVehicleAlarmState() {
        return vehicleAlarmState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.VEHICLE_ALARM_STATE
     *
     * @param vehicleAlarmState the value for VEHICLE.VEHICLE_ALARM_STATE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public void setVehicleAlarmState(String vehicleAlarmState) {
        this.vehicleAlarmState = vehicleAlarmState == null ? null : vehicleAlarmState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.CURRENT_PORT_ID
     *
     * @return the value of VEHICLE.CURRENT_PORT_ID
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public String getCurrentPortId() {
        return currentPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.CURRENT_PORT_ID
     *
     * @param currentPortId the value for VEHICLE.CURRENT_PORT_ID
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public void setCurrentPortId(String currentPortId) {
        this.currentPortId = currentPortId == null ? null : currentPortId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.TOTAL_OPE
     *
     * @return the value of VEHICLE.TOTAL_OPE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public Short getTotalOpe() {
        return totalOpe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.TOTAL_OPE
     *
     * @param totalOpe the value for VEHICLE.TOTAL_OPE
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public void setTotalOpe(Short totalOpe) {
        this.totalOpe = totalOpe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.TOTAL_ERR
     *
     * @return the value of VEHICLE.TOTAL_ERR
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public Short getTotalErr() {
        return totalErr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.TOTAL_ERR
     *
     * @param totalErr the value for VEHICLE.TOTAL_ERR
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public void setTotalErr(Short totalErr) {
        this.totalErr = totalErr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.INSTALLED_TIME
     *
     * @return the value of VEHICLE.INSTALLED_TIME
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public String getInstalledTime() {
        return installedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.INSTALLED_TIME
     *
     * @param installedTime the value for VEHICLE.INSTALLED_TIME
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public void setInstalledTime(String installedTime) {
        this.installedTime = installedTime == null ? null : installedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.REMOVED_TIME
     *
     * @return the value of VEHICLE.REMOVED_TIME
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public String getRemovedTime() {
        return removedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.REMOVED_TIME
     *
     * @param removedTime the value for VEHICLE.REMOVED_TIME
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public void setRemovedTime(String removedTime) {
        this.removedTime = removedTime == null ? null : removedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.RTM_TSC_ID
     *
     * @return the value of VEHICLE.RTM_TSC_ID
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public String getRtmTscId() {
        return rtmTscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.RTM_TSC_ID
     *
     * @param rtmTscId the value for VEHICLE.RTM_TSC_ID
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public void setRtmTscId(String rtmTscId) {
        this.rtmTscId = rtmTscId == null ? null : rtmTscId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.VEHICLE_CARRIER_TYPE_ID
     *
     * @return the value of VEHICLE.VEHICLE_CARRIER_TYPE_ID
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public String getVehicleCarrierTypeId() {
        return vehicleCarrierTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.VEHICLE_CARRIER_TYPE_ID
     *
     * @param vehicleCarrierTypeId the value for VEHICLE.VEHICLE_CARRIER_TYPE_ID
     *
     * @mbggenerated Tue Mar 03 10:44:35 CST 2020
     */
    public void setVehicleCarrierTypeId(String vehicleCarrierTypeId) {
        this.vehicleCarrierTypeId = vehicleCarrierTypeId == null ? null : vehicleCarrierTypeId.trim();
    }
}