package net.muratec.mcs.model;

import java.util.ArrayList;
import java.util.List;

public class VehicleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    public VehicleExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVehicleIdIsNull() {
            addCriterion("VEHICLE_ID is null");
            return (Criteria) this;
        }

        public Criteria andVehicleIdIsNotNull() {
            addCriterion("VEHICLE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andVehicleIdEqualTo(String value) {
            addCriterion("VEHICLE_ID =", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdNotEqualTo(String value) {
            addCriterion("VEHICLE_ID <>", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdGreaterThan(String value) {
            addCriterion("VEHICLE_ID >", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdGreaterThanOrEqualTo(String value) {
            addCriterion("VEHICLE_ID >=", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdLessThan(String value) {
            addCriterion("VEHICLE_ID <", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdLessThanOrEqualTo(String value) {
            addCriterion("VEHICLE_ID <=", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdLike(String value) {
            addCriterion("VEHICLE_ID like", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdNotLike(String value) {
            addCriterion("VEHICLE_ID not like", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdIn(List<String> values) {
            addCriterion("VEHICLE_ID in", values, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdNotIn(List<String> values) {
            addCriterion("VEHICLE_ID not in", values, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdBetween(String value1, String value2) {
            addCriterion("VEHICLE_ID between", value1, value2, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdNotBetween(String value1, String value2) {
            addCriterion("VEHICLE_ID not between", value1, value2, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andLlcIdIsNull() {
            addCriterion("LLC_ID is null");
            return (Criteria) this;
        }

        public Criteria andLlcIdIsNotNull() {
            addCriterion("LLC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLlcIdEqualTo(String value) {
            addCriterion("LLC_ID =", value, "llcId");
            return (Criteria) this;
        }

        public Criteria andLlcIdNotEqualTo(String value) {
            addCriterion("LLC_ID <>", value, "llcId");
            return (Criteria) this;
        }

        public Criteria andLlcIdGreaterThan(String value) {
            addCriterion("LLC_ID >", value, "llcId");
            return (Criteria) this;
        }

        public Criteria andLlcIdGreaterThanOrEqualTo(String value) {
            addCriterion("LLC_ID >=", value, "llcId");
            return (Criteria) this;
        }

        public Criteria andLlcIdLessThan(String value) {
            addCriterion("LLC_ID <", value, "llcId");
            return (Criteria) this;
        }

        public Criteria andLlcIdLessThanOrEqualTo(String value) {
            addCriterion("LLC_ID <=", value, "llcId");
            return (Criteria) this;
        }

        public Criteria andLlcIdLike(String value) {
            addCriterion("LLC_ID like", value, "llcId");
            return (Criteria) this;
        }

        public Criteria andLlcIdNotLike(String value) {
            addCriterion("LLC_ID not like", value, "llcId");
            return (Criteria) this;
        }

        public Criteria andLlcIdIn(List<String> values) {
            addCriterion("LLC_ID in", values, "llcId");
            return (Criteria) this;
        }

        public Criteria andLlcIdNotIn(List<String> values) {
            addCriterion("LLC_ID not in", values, "llcId");
            return (Criteria) this;
        }

        public Criteria andLlcIdBetween(String value1, String value2) {
            addCriterion("LLC_ID between", value1, value2, "llcId");
            return (Criteria) this;
        }

        public Criteria andLlcIdNotBetween(String value1, String value2) {
            addCriterion("LLC_ID not between", value1, value2, "llcId");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeIsNull() {
            addCriterion("VEHICLE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeIsNotNull() {
            addCriterion("VEHICLE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeEqualTo(String value) {
            addCriterion("VEHICLE_TYPE =", value, "vehicleType");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeNotEqualTo(String value) {
            addCriterion("VEHICLE_TYPE <>", value, "vehicleType");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeGreaterThan(String value) {
            addCriterion("VEHICLE_TYPE >", value, "vehicleType");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("VEHICLE_TYPE >=", value, "vehicleType");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeLessThan(String value) {
            addCriterion("VEHICLE_TYPE <", value, "vehicleType");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeLessThanOrEqualTo(String value) {
            addCriterion("VEHICLE_TYPE <=", value, "vehicleType");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeLike(String value) {
            addCriterion("VEHICLE_TYPE like", value, "vehicleType");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeNotLike(String value) {
            addCriterion("VEHICLE_TYPE not like", value, "vehicleType");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeIn(List<String> values) {
            addCriterion("VEHICLE_TYPE in", values, "vehicleType");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeNotIn(List<String> values) {
            addCriterion("VEHICLE_TYPE not in", values, "vehicleType");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeBetween(String value1, String value2) {
            addCriterion("VEHICLE_TYPE between", value1, value2, "vehicleType");
            return (Criteria) this;
        }

        public Criteria andVehicleTypeNotBetween(String value1, String value2) {
            addCriterion("VEHICLE_TYPE not between", value1, value2, "vehicleType");
            return (Criteria) this;
        }

        public Criteria andVehicleStateIsNull() {
            addCriterion("VEHICLE_STATE is null");
            return (Criteria) this;
        }

        public Criteria andVehicleStateIsNotNull() {
            addCriterion("VEHICLE_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andVehicleStateEqualTo(String value) {
            addCriterion("VEHICLE_STATE =", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateNotEqualTo(String value) {
            addCriterion("VEHICLE_STATE <>", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateGreaterThan(String value) {
            addCriterion("VEHICLE_STATE >", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateGreaterThanOrEqualTo(String value) {
            addCriterion("VEHICLE_STATE >=", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateLessThan(String value) {
            addCriterion("VEHICLE_STATE <", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateLessThanOrEqualTo(String value) {
            addCriterion("VEHICLE_STATE <=", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateLike(String value) {
            addCriterion("VEHICLE_STATE like", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateNotLike(String value) {
            addCriterion("VEHICLE_STATE not like", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateIn(List<String> values) {
            addCriterion("VEHICLE_STATE in", values, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateNotIn(List<String> values) {
            addCriterion("VEHICLE_STATE not in", values, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateBetween(String value1, String value2) {
            addCriterion("VEHICLE_STATE between", value1, value2, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateNotBetween(String value1, String value2) {
            addCriterion("VEHICLE_STATE not between", value1, value2, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateIsNull() {
            addCriterion("VEHICLE_ALARM_STATE is null");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateIsNotNull() {
            addCriterion("VEHICLE_ALARM_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateEqualTo(String value) {
            addCriterion("VEHICLE_ALARM_STATE =", value, "vehicleAlarmState");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateNotEqualTo(String value) {
            addCriterion("VEHICLE_ALARM_STATE <>", value, "vehicleAlarmState");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateGreaterThan(String value) {
            addCriterion("VEHICLE_ALARM_STATE >", value, "vehicleAlarmState");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateGreaterThanOrEqualTo(String value) {
            addCriterion("VEHICLE_ALARM_STATE >=", value, "vehicleAlarmState");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateLessThan(String value) {
            addCriterion("VEHICLE_ALARM_STATE <", value, "vehicleAlarmState");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateLessThanOrEqualTo(String value) {
            addCriterion("VEHICLE_ALARM_STATE <=", value, "vehicleAlarmState");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateLike(String value) {
            addCriterion("VEHICLE_ALARM_STATE like", value, "vehicleAlarmState");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateNotLike(String value) {
            addCriterion("VEHICLE_ALARM_STATE not like", value, "vehicleAlarmState");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateIn(List<String> values) {
            addCriterion("VEHICLE_ALARM_STATE in", values, "vehicleAlarmState");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateNotIn(List<String> values) {
            addCriterion("VEHICLE_ALARM_STATE not in", values, "vehicleAlarmState");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateBetween(String value1, String value2) {
            addCriterion("VEHICLE_ALARM_STATE between", value1, value2, "vehicleAlarmState");
            return (Criteria) this;
        }

        public Criteria andVehicleAlarmStateNotBetween(String value1, String value2) {
            addCriterion("VEHICLE_ALARM_STATE not between", value1, value2, "vehicleAlarmState");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdIsNull() {
            addCriterion("CURRENT_PORT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdIsNotNull() {
            addCriterion("CURRENT_PORT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdEqualTo(String value) {
            addCriterion("CURRENT_PORT_ID =", value, "currentPortId");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdNotEqualTo(String value) {
            addCriterion("CURRENT_PORT_ID <>", value, "currentPortId");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdGreaterThan(String value) {
            addCriterion("CURRENT_PORT_ID >", value, "currentPortId");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENT_PORT_ID >=", value, "currentPortId");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdLessThan(String value) {
            addCriterion("CURRENT_PORT_ID <", value, "currentPortId");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdLessThanOrEqualTo(String value) {
            addCriterion("CURRENT_PORT_ID <=", value, "currentPortId");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdLike(String value) {
            addCriterion("CURRENT_PORT_ID like", value, "currentPortId");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdNotLike(String value) {
            addCriterion("CURRENT_PORT_ID not like", value, "currentPortId");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdIn(List<String> values) {
            addCriterion("CURRENT_PORT_ID in", values, "currentPortId");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdNotIn(List<String> values) {
            addCriterion("CURRENT_PORT_ID not in", values, "currentPortId");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdBetween(String value1, String value2) {
            addCriterion("CURRENT_PORT_ID between", value1, value2, "currentPortId");
            return (Criteria) this;
        }

        public Criteria andCurrentPortIdNotBetween(String value1, String value2) {
            addCriterion("CURRENT_PORT_ID not between", value1, value2, "currentPortId");
            return (Criteria) this;
        }

        public Criteria andTotalOpeIsNull() {
            addCriterion("TOTAL_OPE is null");
            return (Criteria) this;
        }

        public Criteria andTotalOpeIsNotNull() {
            addCriterion("TOTAL_OPE is not null");
            return (Criteria) this;
        }

        public Criteria andTotalOpeEqualTo(Short value) {
            addCriterion("TOTAL_OPE =", value, "totalOpe");
            return (Criteria) this;
        }

        public Criteria andTotalOpeNotEqualTo(Short value) {
            addCriterion("TOTAL_OPE <>", value, "totalOpe");
            return (Criteria) this;
        }

        public Criteria andTotalOpeGreaterThan(Short value) {
            addCriterion("TOTAL_OPE >", value, "totalOpe");
            return (Criteria) this;
        }

        public Criteria andTotalOpeGreaterThanOrEqualTo(Short value) {
            addCriterion("TOTAL_OPE >=", value, "totalOpe");
            return (Criteria) this;
        }

        public Criteria andTotalOpeLessThan(Short value) {
            addCriterion("TOTAL_OPE <", value, "totalOpe");
            return (Criteria) this;
        }

        public Criteria andTotalOpeLessThanOrEqualTo(Short value) {
            addCriterion("TOTAL_OPE <=", value, "totalOpe");
            return (Criteria) this;
        }

        public Criteria andTotalOpeIn(List<Short> values) {
            addCriterion("TOTAL_OPE in", values, "totalOpe");
            return (Criteria) this;
        }

        public Criteria andTotalOpeNotIn(List<Short> values) {
            addCriterion("TOTAL_OPE not in", values, "totalOpe");
            return (Criteria) this;
        }

        public Criteria andTotalOpeBetween(Short value1, Short value2) {
            addCriterion("TOTAL_OPE between", value1, value2, "totalOpe");
            return (Criteria) this;
        }

        public Criteria andTotalOpeNotBetween(Short value1, Short value2) {
            addCriterion("TOTAL_OPE not between", value1, value2, "totalOpe");
            return (Criteria) this;
        }

        public Criteria andTotalErrIsNull() {
            addCriterion("TOTAL_ERR is null");
            return (Criteria) this;
        }

        public Criteria andTotalErrIsNotNull() {
            addCriterion("TOTAL_ERR is not null");
            return (Criteria) this;
        }

        public Criteria andTotalErrEqualTo(Short value) {
            addCriterion("TOTAL_ERR =", value, "totalErr");
            return (Criteria) this;
        }

        public Criteria andTotalErrNotEqualTo(Short value) {
            addCriterion("TOTAL_ERR <>", value, "totalErr");
            return (Criteria) this;
        }

        public Criteria andTotalErrGreaterThan(Short value) {
            addCriterion("TOTAL_ERR >", value, "totalErr");
            return (Criteria) this;
        }

        public Criteria andTotalErrGreaterThanOrEqualTo(Short value) {
            addCriterion("TOTAL_ERR >=", value, "totalErr");
            return (Criteria) this;
        }

        public Criteria andTotalErrLessThan(Short value) {
            addCriterion("TOTAL_ERR <", value, "totalErr");
            return (Criteria) this;
        }

        public Criteria andTotalErrLessThanOrEqualTo(Short value) {
            addCriterion("TOTAL_ERR <=", value, "totalErr");
            return (Criteria) this;
        }

        public Criteria andTotalErrIn(List<Short> values) {
            addCriterion("TOTAL_ERR in", values, "totalErr");
            return (Criteria) this;
        }

        public Criteria andTotalErrNotIn(List<Short> values) {
            addCriterion("TOTAL_ERR not in", values, "totalErr");
            return (Criteria) this;
        }

        public Criteria andTotalErrBetween(Short value1, Short value2) {
            addCriterion("TOTAL_ERR between", value1, value2, "totalErr");
            return (Criteria) this;
        }

        public Criteria andTotalErrNotBetween(Short value1, Short value2) {
            addCriterion("TOTAL_ERR not between", value1, value2, "totalErr");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeIsNull() {
            addCriterion("INSTALLED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeIsNotNull() {
            addCriterion("INSTALLED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeEqualTo(String value) {
            addCriterion("INSTALLED_TIME =", value, "installedTime");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeNotEqualTo(String value) {
            addCriterion("INSTALLED_TIME <>", value, "installedTime");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeGreaterThan(String value) {
            addCriterion("INSTALLED_TIME >", value, "installedTime");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeGreaterThanOrEqualTo(String value) {
            addCriterion("INSTALLED_TIME >=", value, "installedTime");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeLessThan(String value) {
            addCriterion("INSTALLED_TIME <", value, "installedTime");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeLessThanOrEqualTo(String value) {
            addCriterion("INSTALLED_TIME <=", value, "installedTime");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeLike(String value) {
            addCriterion("INSTALLED_TIME like", value, "installedTime");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeNotLike(String value) {
            addCriterion("INSTALLED_TIME not like", value, "installedTime");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeIn(List<String> values) {
            addCriterion("INSTALLED_TIME in", values, "installedTime");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeNotIn(List<String> values) {
            addCriterion("INSTALLED_TIME not in", values, "installedTime");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeBetween(String value1, String value2) {
            addCriterion("INSTALLED_TIME between", value1, value2, "installedTime");
            return (Criteria) this;
        }

        public Criteria andInstalledTimeNotBetween(String value1, String value2) {
            addCriterion("INSTALLED_TIME not between", value1, value2, "installedTime");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeIsNull() {
            addCriterion("REMOVED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeIsNotNull() {
            addCriterion("REMOVED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeEqualTo(String value) {
            addCriterion("REMOVED_TIME =", value, "removedTime");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeNotEqualTo(String value) {
            addCriterion("REMOVED_TIME <>", value, "removedTime");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeGreaterThan(String value) {
            addCriterion("REMOVED_TIME >", value, "removedTime");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeGreaterThanOrEqualTo(String value) {
            addCriterion("REMOVED_TIME >=", value, "removedTime");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeLessThan(String value) {
            addCriterion("REMOVED_TIME <", value, "removedTime");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeLessThanOrEqualTo(String value) {
            addCriterion("REMOVED_TIME <=", value, "removedTime");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeLike(String value) {
            addCriterion("REMOVED_TIME like", value, "removedTime");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeNotLike(String value) {
            addCriterion("REMOVED_TIME not like", value, "removedTime");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeIn(List<String> values) {
            addCriterion("REMOVED_TIME in", values, "removedTime");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeNotIn(List<String> values) {
            addCriterion("REMOVED_TIME not in", values, "removedTime");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeBetween(String value1, String value2) {
            addCriterion("REMOVED_TIME between", value1, value2, "removedTime");
            return (Criteria) this;
        }

        public Criteria andRemovedTimeNotBetween(String value1, String value2) {
            addCriterion("REMOVED_TIME not between", value1, value2, "removedTime");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdIsNull() {
            addCriterion("RTM_TSC_ID is null");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdIsNotNull() {
            addCriterion("RTM_TSC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdEqualTo(String value) {
            addCriterion("RTM_TSC_ID =", value, "rtmTscId");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdNotEqualTo(String value) {
            addCriterion("RTM_TSC_ID <>", value, "rtmTscId");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdGreaterThan(String value) {
            addCriterion("RTM_TSC_ID >", value, "rtmTscId");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdGreaterThanOrEqualTo(String value) {
            addCriterion("RTM_TSC_ID >=", value, "rtmTscId");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdLessThan(String value) {
            addCriterion("RTM_TSC_ID <", value, "rtmTscId");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdLessThanOrEqualTo(String value) {
            addCriterion("RTM_TSC_ID <=", value, "rtmTscId");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdLike(String value) {
            addCriterion("RTM_TSC_ID like", value, "rtmTscId");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdNotLike(String value) {
            addCriterion("RTM_TSC_ID not like", value, "rtmTscId");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdIn(List<String> values) {
            addCriterion("RTM_TSC_ID in", values, "rtmTscId");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdNotIn(List<String> values) {
            addCriterion("RTM_TSC_ID not in", values, "rtmTscId");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdBetween(String value1, String value2) {
            addCriterion("RTM_TSC_ID between", value1, value2, "rtmTscId");
            return (Criteria) this;
        }

        public Criteria andRtmTscIdNotBetween(String value1, String value2) {
            addCriterion("RTM_TSC_ID not between", value1, value2, "rtmTscId");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdIsNull() {
            addCriterion("VEHICLE_CARRIER_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdIsNotNull() {
            addCriterion("VEHICLE_CARRIER_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdEqualTo(String value) {
            addCriterion("VEHICLE_CARRIER_TYPE_ID =", value, "vehicleCarrierTypeId");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdNotEqualTo(String value) {
            addCriterion("VEHICLE_CARRIER_TYPE_ID <>", value, "vehicleCarrierTypeId");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdGreaterThan(String value) {
            addCriterion("VEHICLE_CARRIER_TYPE_ID >", value, "vehicleCarrierTypeId");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("VEHICLE_CARRIER_TYPE_ID >=", value, "vehicleCarrierTypeId");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdLessThan(String value) {
            addCriterion("VEHICLE_CARRIER_TYPE_ID <", value, "vehicleCarrierTypeId");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdLessThanOrEqualTo(String value) {
            addCriterion("VEHICLE_CARRIER_TYPE_ID <=", value, "vehicleCarrierTypeId");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdLike(String value) {
            addCriterion("VEHICLE_CARRIER_TYPE_ID like", value, "vehicleCarrierTypeId");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdNotLike(String value) {
            addCriterion("VEHICLE_CARRIER_TYPE_ID not like", value, "vehicleCarrierTypeId");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdIn(List<String> values) {
            addCriterion("VEHICLE_CARRIER_TYPE_ID in", values, "vehicleCarrierTypeId");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdNotIn(List<String> values) {
            addCriterion("VEHICLE_CARRIER_TYPE_ID not in", values, "vehicleCarrierTypeId");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdBetween(String value1, String value2) {
            addCriterion("VEHICLE_CARRIER_TYPE_ID between", value1, value2, "vehicleCarrierTypeId");
            return (Criteria) this;
        }

        public Criteria andVehicleCarrierTypeIdNotBetween(String value1, String value2) {
            addCriterion("VEHICLE_CARRIER_TYPE_ID not between", value1, value2, "vehicleCarrierTypeId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VEHICLE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}