package net.muratec.mcs.model;

public class Vehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.VEHICLE_ID
     *
     * @mbg.generated
     */
    private String vehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.LLC_ID
     *
     * @mbg.generated
     */
    private String llcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.VEHICLE_TYPE
     *
     * @mbg.generated
     */
    private String vehicleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.VEHICLE_STATE
     *
     * @mbg.generated
     */
    private String vehicleState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.VEHICLE_ALARM_STATE
     *
     * @mbg.generated
     */
    private String vehicleAlarmState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.CURRENT_PORT_ID
     *
     * @mbg.generated
     */
    private String currentPortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.TOTAL_OPE
     *
     * @mbg.generated
     */
    private Short totalOpe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.TOTAL_ERR
     *
     * @mbg.generated
     */
    private Short totalErr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.INSTALLED_TIME
     *
     * @mbg.generated
     */
    private String installedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.REMOVED_TIME
     *
     * @mbg.generated
     */
    private String removedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.RTM_TSC_ID
     *
     * @mbg.generated
     */
    private String rtmTscId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VEHICLE.VEHICLE_CARRIER_TYPE_ID
     *
     * @mbg.generated
     */
    private String vehicleCarrierTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.VEHICLE_ID
     *
     * @return the value of VEHICLE.VEHICLE_ID
     *
     * @mbg.generated
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.VEHICLE_ID
     *
     * @param vehicleId the value for VEHICLE.VEHICLE_ID
     *
     * @mbg.generated
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.LLC_ID
     *
     * @return the value of VEHICLE.LLC_ID
     *
     * @mbg.generated
     */
    public String getLlcId() {
        return llcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.LLC_ID
     *
     * @param llcId the value for VEHICLE.LLC_ID
     *
     * @mbg.generated
     */
    public void setLlcId(String llcId) {
        this.llcId = llcId == null ? null : llcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.VEHICLE_TYPE
     *
     * @return the value of VEHICLE.VEHICLE_TYPE
     *
     * @mbg.generated
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.VEHICLE_TYPE
     *
     * @param vehicleType the value for VEHICLE.VEHICLE_TYPE
     *
     * @mbg.generated
     */
    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType == null ? null : vehicleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.VEHICLE_STATE
     *
     * @return the value of VEHICLE.VEHICLE_STATE
     *
     * @mbg.generated
     */
    public String getVehicleState() {
        return vehicleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.VEHICLE_STATE
     *
     * @param vehicleState the value for VEHICLE.VEHICLE_STATE
     *
     * @mbg.generated
     */
    public void setVehicleState(String vehicleState) {
        this.vehicleState = vehicleState == null ? null : vehicleState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.VEHICLE_ALARM_STATE
     *
     * @return the value of VEHICLE.VEHICLE_ALARM_STATE
     *
     * @mbg.generated
     */
    public String getVehicleAlarmState() {
        return vehicleAlarmState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.VEHICLE_ALARM_STATE
     *
     * @param vehicleAlarmState the value for VEHICLE.VEHICLE_ALARM_STATE
     *
     * @mbg.generated
     */
    public void setVehicleAlarmState(String vehicleAlarmState) {
        this.vehicleAlarmState = vehicleAlarmState == null ? null : vehicleAlarmState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.CURRENT_PORT_ID
     *
     * @return the value of VEHICLE.CURRENT_PORT_ID
     *
     * @mbg.generated
     */
    public String getCurrentPortId() {
        return currentPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.CURRENT_PORT_ID
     *
     * @param currentPortId the value for VEHICLE.CURRENT_PORT_ID
     *
     * @mbg.generated
     */
    public void setCurrentPortId(String currentPortId) {
        this.currentPortId = currentPortId == null ? null : currentPortId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.TOTAL_OPE
     *
     * @return the value of VEHICLE.TOTAL_OPE
     *
     * @mbg.generated
     */
    public Short getTotalOpe() {
        return totalOpe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.TOTAL_OPE
     *
     * @param totalOpe the value for VEHICLE.TOTAL_OPE
     *
     * @mbg.generated
     */
    public void setTotalOpe(Short totalOpe) {
        this.totalOpe = totalOpe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.TOTAL_ERR
     *
     * @return the value of VEHICLE.TOTAL_ERR
     *
     * @mbg.generated
     */
    public Short getTotalErr() {
        return totalErr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.TOTAL_ERR
     *
     * @param totalErr the value for VEHICLE.TOTAL_ERR
     *
     * @mbg.generated
     */
    public void setTotalErr(Short totalErr) {
        this.totalErr = totalErr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.INSTALLED_TIME
     *
     * @return the value of VEHICLE.INSTALLED_TIME
     *
     * @mbg.generated
     */
    public String getInstalledTime() {
        return installedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.INSTALLED_TIME
     *
     * @param installedTime the value for VEHICLE.INSTALLED_TIME
     *
     * @mbg.generated
     */
    public void setInstalledTime(String installedTime) {
        this.installedTime = installedTime == null ? null : installedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.REMOVED_TIME
     *
     * @return the value of VEHICLE.REMOVED_TIME
     *
     * @mbg.generated
     */
    public String getRemovedTime() {
        return removedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.REMOVED_TIME
     *
     * @param removedTime the value for VEHICLE.REMOVED_TIME
     *
     * @mbg.generated
     */
    public void setRemovedTime(String removedTime) {
        this.removedTime = removedTime == null ? null : removedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.RTM_TSC_ID
     *
     * @return the value of VEHICLE.RTM_TSC_ID
     *
     * @mbg.generated
     */
    public String getRtmTscId() {
        return rtmTscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.RTM_TSC_ID
     *
     * @param rtmTscId the value for VEHICLE.RTM_TSC_ID
     *
     * @mbg.generated
     */
    public void setRtmTscId(String rtmTscId) {
        this.rtmTscId = rtmTscId == null ? null : rtmTscId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VEHICLE.VEHICLE_CARRIER_TYPE_ID
     *
     * @return the value of VEHICLE.VEHICLE_CARRIER_TYPE_ID
     *
     * @mbg.generated
     */
    public String getVehicleCarrierTypeId() {
        return vehicleCarrierTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VEHICLE.VEHICLE_CARRIER_TYPE_ID
     *
     * @param vehicleCarrierTypeId the value for VEHICLE.VEHICLE_CARRIER_TYPE_ID
     *
     * @mbg.generated
     */
    public void setVehicleCarrierTypeId(String vehicleCarrierTypeId) {
        this.vehicleCarrierTypeId = vehicleCarrierTypeId == null ? null : vehicleCarrierTypeId.trim();
    }
}